/*
 * Copyright 2026 HM Revenue & Customs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package uk.gov.hmrc.ui.specs

import org.scalatest.featurespec.AnyFeatureSpec
import org.scalatest.verbs.ShouldVerb
import org.scalatest.{BeforeAndAfterAll, BeforeAndAfterEach, GivenWhenThen}
import uk.gov.hmrc.selenium.webdriver.{Browser, ScreenshotOnFailure}
import uk.gov.hmrc.ui.pages.*
import uk.gov.hmrc.ui.util.Users.LoginTypes.HASDIRECT
import uk.gov.hmrc.ui.util.Users.UserTypes.Agent

class AgentDeclarationJourneySpec
    extends AnyFeatureSpec
    with BaseSpec
    with GivenWhenThen
    with ShouldVerb
    with BeforeAndAfterAll
    with BeforeAndAfterEach
    with Browser
    with ScreenshotOnFailure {

  Feature("Charities - Agent - Declaration Page Validations") {
    Scenario(
      "User navigates to the 'What adjustments have you made to this claim?' page from the Gift Aid flow and validates the page elements"
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.loginAgent(HASDIRECT, Agent, "Agent", "HMRC-CHAR-AGENT", "AGENTCHARID", "TESTAGENTADJ")
      Then("User navigates to 'Manage charity repayment claims' page and validates navigation")
      CharitiesManagementAgent.validateNavigationAgent()
      And(
        "User clicks the link 'Use the charities online service' to navigate to task list 'Make a charity repayment claim' page"
      )
      CharitiesManagementAgent.clickUseTheCharitiesLink()
      Then("User navigates and validates the 'Repayment claim details' page")
      RepaymentClaimDetailsPage.validateNavigationAgent()
      Then("User Clicks Continue and navigates to 'Enter HMRC Charities Reference' page")
      RepaymentClaimDetailsPage.clickContinue()
      And("User Validates Navigation/hint for the 'Enter HMRC Charities Reference' page")
      WhatIsYourHMRCReferenceNumberPage.validateNavigationAgent()
      Then("User Inputs a Charity Reference Number on 'Enter HMRC Charities Reference' page and clicks CONTINUE")
      WhatIsYourHMRCReferenceNumberPage.enterCharitiesReferenceNumber("X12345")
      And("User Navigates to 'What is the Name of your Charity or CASC' page and validates the page elements and text")
      WhatIsTheNameOfCharityOrCASC.validateNavigationAgent()
      Then("User Inputs a Charity Reference Number on 'Enter HMRC Charities Reference' page and clicks CONTINUE")
      WhatIsTheNameOfCharityOrCASC.enterCharityName("TEST AGENT CASC")
      Then("User navigates to 'Which type of repayment claim do you want to make?' page")
      RepaymentCheckboxPage.validateNavigationAgent()
      And("User selects 'Tax Repayments on Gift Aid donations' checkbox and clicks continue")
      RepaymentCheckboxPage.checkbox(RepaymentCheckboxPage.GiftAid, true)
      RepaymentCheckboxPage.clickContinue()
      Then("User navigates to 'Do you have a claim reference number?' page")
      DoYouHaveAClaimReferenceNumberPage.validateNavigationAgent()
      And("User selects 'No' and clicks continue on 'Do you have a claim reference number?' page")
      DoYouHaveAClaimReferenceNumberPage.radioButton(DoYouHaveAClaimReferenceNumberPage.no)
      DoYouHaveAClaimReferenceNumberPage.clickContinue()
      Then("User navigates to 'Check your repayment claim' page")
      CheckYourRepaymentClaimPage.validateNavigationAgent()
      CheckYourRepaymentClaimPage.clickContinue()
      Then("User navigates to 'Make a charity repayment claim' page")
      ClaimsTaskListPage_InProgress.validateNavigationAgent()
      And("User clicks the link to navigate to 'About the organisation' page")
      ClaimsTaskListPage_InProgress.clickProvideOrganisationDetails()
      AboutTheOrganisationPage.validateNavigationAgent()
      Then("User selects continue on 'About the organisation' page")
      AboutTheOrganisationPage.clickContinue()
      And("User navigates to 'What is the name of the charity regulator?' page")
      WhatIsTheNameOfTheCharityRegulatorPage.validateNavigationAgent()
      And("User selects they are not registered with a regulator")
      WhatIsTheNameOfTheCharityRegulatorPage.radioButton(WhatIsTheNameOfTheCharityRegulatorPage.None)
      WhatIsTheNameOfTheCharityRegulatorPage.clickContinue()
      And("User navigates to 'Why is the charity not registered with a regulator?' page")
      WhyIsTheCharityNotRegisteredPage.validateNavigationAgent()
      And("User selects they are excepted")
      WhyIsTheCharityNotRegisteredPage.radioButton(WhyIsTheCharityNotRegisteredPage.Excepted)
      WhyIsTheCharityNotRegisteredPage.clickContinue()
      And("User navigates to 'Your charity is excepted' page")
      YourCharityIsExceptedPage.validateNavigationAgent()
      Then("User selects continue on 'Your charity is excepted' page")
      YourCharityIsExceptedPage.clickContinue()
      And("User navigates to 'Is a corporate trustee making this claim?' page")
      IsACorporateTrusteeMakingThisClaimPage.validateNavigationAgent()
      And("User selects a corporate trustee is making this claim")
      IsACorporateTrusteeMakingThisClaimPage.radioButton(IsACorporateTrusteeMakingThisClaimPage.yes)
      IsACorporateTrusteeMakingThisClaimPage.clickContinue()
      And("User navigates to 'Does the corporate trustee have a UK address?' page")
      DoesTheCorporateTrusteeHaveAUKAddressPage.validateNavigationAgent()
      And("User selects a corporate trustee does not have a UK address")
      DoesTheCorporateTrusteeHaveAUKAddressPage.radioButton(DoesTheCorporateTrusteeHaveAUKAddressPage.no)
      DoesTheCorporateTrusteeHaveAUKAddressPage.clickContinue()
      And("User navigates to 'What are the corporate trustee details?' page")
      CorporateTrusteeDetailsPage.validateNavigationAgent()
      And("User enters their Non UK Trustee details and clicks continue")
      CorporateTrusteeDetailsPage.enterNonUKTrusteeDetails("TEST TRUSTEE", "00-1-332-555-2368")
      And("User navigates to 'Check your organisation details' page")
      CheckYourOrganisationDetailsPage.validateNavigationAgent()
      Then("User navigates to 'Make a charity repayment claim' page")
      CheckYourOrganisationDetailsPage.clickContinue()
      ClaimsTaskListPage_InProgress.validateNavigationAgent()
      And("User clicks the link to navigate to 'Add Gift Aid schedule' page")
      ClaimsTaskListPage_InProgress.clickAddGiftAidSchedule()
      Then("User navigates to 'About Gift Aid schedule' page")
      AboutGiftAidSchedulePage.validateNavigationAgent()
      AboutGiftAidSchedulePage.clickContinue()
      Then("User navigates to 'Upload a Gift Aid schedule' page")
      UploadAGiftAidSchedulePage.validateNavigationAgent()
      Then("User selects a file to upload in the 'Upload a Gift Aid schedule' page")
      UploadAGiftAidSchedulePage.selectFile("GiftAidSpreadsheets/Gift-Aid-Schedule-SIMPLEPASS_MAX_ROWS_OVERCLAIMED")
      UploadAGiftAidSchedulePage.clickContinue()
      Then("User navigates to 'Your Gift Aid schedule upload' page")
      YourGiftAidScheduleUploadPage.validateNavigationAgent()
      YourGiftAidScheduleUploadPage.waitForFileUpload()
      YourGiftAidScheduleUploadPage.clickContinue()
      Then("User navigates to 'Check your Gift Aid schedule' page")
      CheckYourGiftAidSchedulePage.validateNavigationAgent()
      CheckYourGiftAidSchedulePage.radioButton(CheckYourGiftAidSchedulePage.no)
      CheckYourGiftAidSchedulePage.clickContinue()
      Then("User navigates to 'Successful Gift Aid Upload' page")
      GiftAidUploadSuccessfulPage.validateNavigationAgent()
      Then("User navigates to 'Make a charity repayment claim' page")
      GiftAidUploadSuccessfulPage.clickContinue()
      ClaimsTaskListPage_InProgress.validateNavigationAgent()
      Then("User navigates to 'What adjustments have you made to this claim?' page")
      ClaimsTaskListPage_InProgress.clickReadDeclaration()
      WhatAdjustmentsHaveYouMadeToThisClaimPage.validateNavigationAgent()
      And("User validates 'What adjustments have you made to this claim?' page elements")
      WhatAdjustmentsHaveYouMadeToThisClaimPage.validatePageContentAgent()
      And("User validates 'What adjustments have you made to this claim?' page error message")
      WhatAdjustmentsHaveYouMadeToThisClaimPage.validateErrorMessage()
    }
//
//    Scenario(
//      "User navigates to the 'What adjustments have you made to this claim?' page from the Other Income flow and validates the page elements"
//    ) {
//      Given("the user logs in through the Authority Wizard page")
//      AuthWizard.login(HASDIRECT, Organisation, "Organisation", "HMRC-CHAR-ORG", "CHARID", "PAGE-TEST-D11-OI")
//      Then("User navigates to 'Manage charity repayment claims' page and validates navigation")
//      CharitiesManagementPlaceholder.validateNavigationAgent()
//      And(
//        "User clicks the link 'Use the charities online service' to navigate to task list 'Make a charity repayment claim' page"
//      )
//      CharitiesManagementPlaceholder.clickUseTheCharitiesLink()
//      Then("User navigates to 'Make a charity repayment claim' page")
//      ClaimsTaskListPage_Empty.validateNavigationAgent()
//      And("User clicks the link to navigate to 'Repayment claim details' page")
//      ClaimsTaskListPage_Empty.clickProvideRepaymentClaimDetails()
//      Then("User validates the 'Repayment claim details' page")
//      RepaymentClaimDetailsPage.validateNavigationAgent()
//      And("User clicks continue on 'Repayment claim details' page")
//      RepaymentClaimDetailsPage.clickContinue()
//      Then("User navigates to 'Which type of repayment claim do you want to make?' page")
//      RepaymentCheckboxPage.validateNavigationAgent()
//      And("User selects 'Uk tax deducted from Other Income' checkbox and clicks continue")
//      RepaymentCheckboxPage.checkbox(RepaymentCheckboxPage.OtherIncome, true)
//      RepaymentCheckboxPage.clickContinue()
//      Then("User navigates to 'Do you have a claim reference number?' page")
//      DoYouHaveAClaimReferenceNumberPage.validateNavigationAgent()
//      And("User selects 'No' and clicks continue on 'Do you have a claim reference number?' page")
//      DoYouHaveAClaimReferenceNumberPage.radioButton(DoYouHaveAClaimReferenceNumberPage.no)
//      DoYouHaveAClaimReferenceNumberPage.clickContinue()
//      Then("User navigates to 'Check your repayment claim' page")
//      CheckYourRepaymentClaimPage.validateNavigationAgent()
//      CheckYourRepaymentClaimPage.clickContinue()
//      Then("User navigates to 'Make a charity repayment claim' page")
//      ClaimsTaskListPage_InProgress.validateNavigationAgent()
//      And("User clicks the link to navigate to 'About the organisation' page")
//      ClaimsTaskListPage_InProgress.clickProvideOrganisationDetails()
//      AboutTheOrganisationPage.validateNavigationAgent()
//      Then("User selects continue on 'About the organisation' page")
//      AboutTheOrganisationPage.clickContinue()
//      And("User navigates to 'What is the name of the charity regulator?' page")
//      WhatIsTheNameOfTheCharityRegulatorPage.validateNavigationAgent()
//      And("User selects they are not registered with a regulator")
//      WhatIsTheNameOfTheCharityRegulatorPage.radioButton(WhatIsTheNameOfTheCharityRegulatorPage.None)
//      WhatIsTheNameOfTheCharityRegulatorPage.clickContinue()
//      And("User navigates to 'Why is the charity not registered with a regulator?' page")
//      WhyIsTheCharityNotRegisteredPage.validateNavigationAgent()
//      And("User selects they are excepted")
//      WhyIsTheCharityNotRegisteredPage.radioButton(WhyIsTheCharityNotRegisteredPage.LowIncome)
//      WhyIsTheCharityNotRegisteredPage.clickContinue()
//      And("User navigates to 'Is a corporate trustee making this claim?' page")
//      IsACorporateTrusteeMakingThisClaimPage.validateNavigationAgent()
//      And("User selects a corporate trustee is making this claim")
//      IsACorporateTrusteeMakingThisClaimPage.radioButton(IsACorporateTrusteeMakingThisClaimPage.yes)
//      IsACorporateTrusteeMakingThisClaimPage.clickContinue()
//      And("User navigates to 'Does the corporate trustee have a UK address?' page")
//      DoesTheCorporateTrusteeHaveAUKAddressPage.validateNavigationAgent()
//      And("User selects a corporate trustee does not have a UK address")
//      DoesTheCorporateTrusteeHaveAUKAddressPage.radioButton(DoesTheCorporateTrusteeHaveAUKAddressPage.yes)
//      DoesTheCorporateTrusteeHaveAUKAddressPage.clickContinue()
//      And("User navigates to 'What are the corporate trustee details?' page")
//      CorporateTrusteeDetailsPage.validateNavigationAgent()
//      And("User enters their Non UK Trustee details and clicks continue")
//      CorporateTrusteeDetailsPage.enterUKTrusteeDetails("TEST TRUSTEE", "01632 960999", "WG7 7FU")
//      And("User navigates to 'Check your organisation details' page")
//      CheckYourOrganisationDetailsPage.validateNavigationAgent()
//      Then("User navigates to 'Make a charity repayment claim' page")
//      CheckYourOrganisationDetailsPage.clickContinue()
//      ClaimsTaskListPage_InProgress.validateNavigationAgent()
//      And("User clicks the link to navigate to 'Add Other Income schedule' page")
//      ClaimsTaskListPage_InProgress.clickAddOtherIncomeSchedule()
//      Then("User navigates to 'About Other Income schedule' page")
//      AboutOtherIncomeSchedulePage.validateNavigationAgent()
//      AboutOtherIncomeSchedulePage.clickContinue()
//      Then("User navigates to 'Upload a Other Income schedule' page")
//      UploadAnOtherIncomeSchedulePage.validateNavigationAgent()
//      Then("User selects a file to upload in the 'Upload a Other Income schedule' page")
//      UploadAnOtherIncomeSchedulePage.selectFile("OtherIncomeSpreadsheets/Other-Income-Schedule-GoodData")
//      UploadAnOtherIncomeSchedulePage.clickContinue()
//      Then("User navigates to 'Your Other Income schedule upload' page")
//      YourOtherIncomeScheduleUploadPage.validateNavigationAgent()
//      YourOtherIncomeScheduleUploadPage.waitForFileUpload()
//      YourOtherIncomeScheduleUploadPage.clickContinue()
//      Then("User navigates to 'Check your Other Income schedule' page")
//      CheckYourOtherIncomeSchedulePage.validateNavigationAgent()
//      CheckYourOtherIncomeSchedulePage.radioButton(CheckYourOtherIncomeSchedulePage.no)
//      CheckYourOtherIncomeSchedulePage.clickContinue()
//      Then("User navigates to 'Successful Other Income Upload' page")
//      OtherIncomeUploadSuccessfulPage.validateNavigationAgent()
//      Then("User navigates to 'Make a charity repayment claim' page")
//      OtherIncomeUploadSuccessfulPage.clickContinue()
//      ClaimsTaskListPage_InProgress.validateNavigationAgent()
//      Then("User navigates to 'What adjustments have you made to this claim?' page")
//      ClaimsTaskListPage_InProgress.clickReadDeclaration()
//      WhatAdjustmentsHaveYouMadeToThisClaimPage.validateNavigationAgent()
//      And("User validates 'What adjustments have you made to this claim?' page elements")
//      WhatAdjustmentsHaveYouMadeToThisClaimPage.validatePageContentAgent()
//      And("User validates 'What adjustments have you made to this claim?' page error message")
//      WhatAdjustmentsHaveYouMadeToThisClaimPage.validateErrorMessage()
//    }
//
//    Scenario(
//      "User navigates to the 'What adjustments have you made to this claim?' page from the GASDS flow and validates the page elements"
//    ) {
//      Given("the user logs in through the Authority Wizard page")
//      AuthWizard.login(HASDIRECT, Organisation, "Organisation", "HMRC-CHAR-ORG", "CHARID", "PAGE-TEST-D11-GASDS")
//      Then("User navigates to 'Manage charity repayment claims' page and validates navigation")
//      CharitiesManagementPlaceholder.validateNavigationAgent()
//      And(
//        "User clicks the link 'Use the charities online service' to navigate to task list 'Make a charity repayment claim' page"
//      )
//      CharitiesManagementPlaceholder.clickUseTheCharitiesLink()
//      Then("User navigates to 'Make a charity repayment claim' page")
//      ClaimsTaskListPage_Empty.validateNavigationAgent()
//      And("User clicks the link to navigate to 'Repayment claim details' page")
//      ClaimsTaskListPage_Empty.clickProvideRepaymentClaimDetails()
//      Then("User validates the 'Repayment claim details' page")
//      RepaymentClaimDetailsPage.validateNavigationAgent()
//      And("User clicks continue on 'Repayment claim details' page")
//      RepaymentClaimDetailsPage.clickContinue()
//      Then("User navigates to 'Which type of repayment claim do you want to make?' page")
//      RepaymentCheckboxPage.validateNavigationAgent()
//      And("User selects 'GASDS' checkbox and clicks continue")
//      RepaymentCheckboxPage.checkbox(RepaymentCheckboxPage.GASDSclaim, true)
//      RepaymentCheckboxPage.clickContinue()
//      And("User navigates to 'Gift Aid Small Donations Scheme (GASDS) details' checkbox page")
//      GASDSCheckboxPage.validateNavigationAgent()
//      Then("User validates entire page content on the 'Gift Aid Small Donations Scheme (GASDS) details' checkbox page")
//      GASDSCheckboxPage.validatePageContentAgent()
//      And("User selects 'GASDS top-up' checkbox and clicks continue")
//      GASDSCheckboxPage.checkbox(GASDSCheckboxPage.GASDSTopUp, true)
//      GASDSCheckboxPage.clickContinue()
//      Then("User navigates to 'Gift Aid Small Donations Scheme claim' page")
//      GiftAidSmallDonationsSchemeClaimPage.validateNavigationAgent()
//      And("User selects 'Yes' and clicks continue on 'Gift Aid Small Donations Scheme claim' page")
//      GiftAidSmallDonationsSchemeClaimPage.radioButton(GiftAidSmallDonationsSchemeClaimPage.yes)
//      GiftAidSmallDonationsSchemeClaimPage.clickContinue()
//      Then("User navigates to 'Do you have a claim reference number?' page")
//      DoYouHaveAClaimReferenceNumberPage.validateNavigationAgent()
//      And("User selects 'No' and clicks continue on 'Do you have a claim reference number?' page")
//      DoYouHaveAClaimReferenceNumberPage.radioButton(DoYouHaveAClaimReferenceNumberPage.no)
//      DoYouHaveAClaimReferenceNumberPage.clickContinue()
//      Then("User navigates to 'Check your repayment claim' page")
//      CheckYourRepaymentClaimPage.validateNavigationAgent()
//      CheckYourRepaymentClaimPage.clickContinue()
//      Then("User navigates to 'Make a charity repayment claim' page")
//      ClaimsTaskListPage_InProgress.validateNavigationGASDSOnlyComplete()
//      And("User clicks the link to navigate to 'About the organisation' page")
//      ClaimsTaskListPage_InProgress.clickProvideOrganisationDetails()
//      AboutTheOrganisationPage.validateNavigationAgent()
//      Then("User selects continue on 'About the organisation' page")
//      AboutTheOrganisationPage.clickContinue()
//      And("User navigates to 'What is the name of the charity regulator?' page")
//      WhatIsTheNameOfTheCharityRegulatorPage.validateNavigationAgent()
//      And("User selects they are not registered with a regulator")
//      WhatIsTheNameOfTheCharityRegulatorPage.radioButton(WhatIsTheNameOfTheCharityRegulatorPage.None)
//      WhatIsTheNameOfTheCharityRegulatorPage.clickContinue()
//      And("User navigates to 'Why is the charity not registered with a regulator?' page")
//      WhyIsTheCharityNotRegisteredPage.validateNavigationAgent()
//      And("User selects they are excepted")
//      WhyIsTheCharityNotRegisteredPage.radioButton(WhyIsTheCharityNotRegisteredPage.LowIncome)
//      WhyIsTheCharityNotRegisteredPage.clickContinue()
//      And("User navigates to 'Is a corporate trustee making this claim?' page")
//      IsACorporateTrusteeMakingThisClaimPage.validateNavigationAgent()
//      And("User selects a corporate trustee is making this claim")
//      IsACorporateTrusteeMakingThisClaimPage.radioButton(IsACorporateTrusteeMakingThisClaimPage.yes)
//      IsACorporateTrusteeMakingThisClaimPage.clickContinue()
//      And("User navigates to 'Does the corporate trustee have a UK address?' page")
//      DoesTheCorporateTrusteeHaveAUKAddressPage.validateNavigationAgent()
//      And("User selects a corporate trustee does not have a UK address")
//      DoesTheCorporateTrusteeHaveAUKAddressPage.radioButton(DoesTheCorporateTrusteeHaveAUKAddressPage.no)
//      DoesTheCorporateTrusteeHaveAUKAddressPage.clickContinue()
//      And("User navigates to 'What are the corporate trustee details?' page")
//      CorporateTrusteeDetailsPage.validateNavigationAgent()
//      And("User enters their Non UK Trustee details and clicks continue")
//      CorporateTrusteeDetailsPage.enterNonUKTrusteeDetails("TEST TRUSTEE", "01632 960999")
//      And("User navigates to 'Check your organisation details' page")
//      CheckYourOrganisationDetailsPage.validateNavigationAgent()
//      Then("User navigates to 'Make a charity repayment claim' page")
//      CheckYourOrganisationDetailsPage.clickContinue()
//      ClaimsTaskListPage_InProgress.validateNavigationGASDSOnlyComplete()
//      And("User clicks the link to navigate to 'About Gift Aid Small Donations Scheme schedule' page")
//      ClaimsTaskListPage_InProgress.clickProvideGASDSDetails()
//      And("User Validates the navigation to 'About Gift Aid Small Donations Scheme schedule' page")
//      AboutGASDSPage.validateNavigationAgent()
//      Then("User navigates to 'What is the adjustment amount for Gift Aid previously overclaimed?' page")
//      AboutGASDSPage.clickContinue()
//      WhatIsTheAdjustmentAmountForGiftAidPreviouslyOverclaimedPage.validateNavigationAgent()
//      Then("User navigates to 'Check your GASDS adjustment amount' page")
//      WhatIsTheAdjustmentAmountForGiftAidPreviouslyOverclaimedPage.enterAdjustmentAmountValue("123.45")
//      CheckYourGASDSAdjustmentAmountPage.validateNavigationAgent()
//      Then("User navigates to 'Which tax year are you claiming for?' year 1 page")
//      CheckYourGASDSAdjustmentAmountPage.clickContinue()
//      WhichTaxYearAreYouClaimingForPage.validateNavigation1()
//      Then(
//        s"User navigates to 'Which tax year are you claiming for?' page and inputs: " + WhichTaxYearAreYouClaimingForPage.earliestTaxYear
//      )
//      WhichTaxYearAreYouClaimingForPage.enterValidTaxYear(WhichTaxYearAreYouClaimingForPage.earliestTaxYear)
//      Then("User navigates to 'What donation amount are you claiming under GASDS, in pounds?' for the first year page")
//      WhatDonationAmountAreYouClaimingUnderGASDSPage.validateNavigation_Year1()
//      Then(
//        "User inputs a value on 'What donation amount are you claiming under GASDS, in pounds?' for the first year page"
//      )
//      WhatDonationAmountAreYouClaimingUnderGASDSPage.enterDonationAmount("543.21")
//      Then("User navigates to 'Check your claim details for tax year 1' page")
//      CheckYourClaimDetailsForTaxYearPage.validateNavigation1()
//      Then("User navigates to 'You have added a claim for 1 tax year' page")
//      CheckYourClaimDetailsForTaxYearPage.clickContinue()
//      YouHaveAddedAClaimForXTaxYearPage.validateNavigation1()
//      Then("User selects 'Yes' on 'You have added a claim for 1 tax year' page to add another tax year")
//      YouHaveAddedAClaimForXTaxYearPage.radioButton(YouHaveAddedAClaimForXTaxYearPage.yes)
//      YouHaveAddedAClaimForXTaxYearPage.clickContinue()
//      Then("User navigates to 'Which tax year are you claiming for?' year 2 page")
//      WhichTaxYearAreYouClaimingForPage.validateNavigation2()
//      Then(
//        s"User navigates to 'Which tax year are you claiming for?' page and inputs: " + WhichTaxYearAreYouClaimingForPage.secondEarliestTaxYear
//      )
//      WhichTaxYearAreYouClaimingForPage.enterValidTaxYear(WhichTaxYearAreYouClaimingForPage.secondEarliestTaxYear)
//      Then("User navigates to 'What donation amount are you claiming under GASDS, in pounds?' for the second year page")
//      WhatDonationAmountAreYouClaimingUnderGASDSPage.validateNavigation_Year2()
//      Then(
//        "User inputs a value on 'What donation amount are you claiming under GASDS, in pounds?' for the second year page"
//      )
//      WhatDonationAmountAreYouClaimingUnderGASDSPage.enterDonationAmount("111.11")
//      Then("User navigates to 'Check your claim details for tax year 2' page")
//      CheckYourClaimDetailsForTaxYearPage.validateNavigation2()
//      Then("User navigates to 'You have added a claim for 2 tax years' page")
//      CheckYourClaimDetailsForTaxYearPage.clickContinue()
//      YouHaveAddedAClaimForXTaxYearPage.validateNavigation2()
//      Then("User selects 'Yes' on 'You have added a claim for 2 tax year' page to add another tax year")
//      YouHaveAddedAClaimForXTaxYearPage.radioButton(YouHaveAddedAClaimForXTaxYearPage.yes)
//      YouHaveAddedAClaimForXTaxYearPage.clickContinue()
//      Then("User navigates to 'Which tax year are you claiming for?' year 3 page")
//      WhichTaxYearAreYouClaimingForPage.validateNavigation3()
//      Then(
//        s"User navigates to 'Which tax year are you claiming for?' page and inputs: " + WhichTaxYearAreYouClaimingForPage.recentTaxYear
//      )
//      WhichTaxYearAreYouClaimingForPage.enterValidTaxYear(WhichTaxYearAreYouClaimingForPage.recentTaxYear)
//      Then("User navigates to 'What donation amount are you claiming under GASDS, in pounds?' for the third year page")
//      WhatDonationAmountAreYouClaimingUnderGASDSPage.validateNavigation_Year3()
//      Then(
//        "User inputs a value on 'What donation amount are you claiming under GASDS, in pounds?' for the third year page"
//      )
//      WhatDonationAmountAreYouClaimingUnderGASDSPage.enterDonationAmount("3.33")
//      Then("User navigates to 'Check your claim details for tax year 3' page")
//      CheckYourClaimDetailsForTaxYearPage.validateNavigation3()
//      Then("User navigates to 'You have added a claim for 3 tax years' page and validates navigation")
//      CheckYourClaimDetailsForTaxYearPage.clickContinue()
//      YouHaveAddedAClaimForXTaxYearPage.validateNavigation3()
//      And("User Clicks Continue on 'You have added a claim for 3 tax years' page")
//      YouHaveAddedAClaimForXTaxYearPage.clickContinue()
//      Then("User navigates to 'Check your GASDS donation details' page and validates page details")
//      CheckYourGASDSDonationDetailsPage.validateNavigationAgent()
//      Then("User clicks CONTINUE to reach task list: 'Make a repayment Claim' Page")
//      CheckYourGASDSDonationDetailsPage.clickContinue()
//      And("User validates navigation to 'Make a repayment Claim' Page")
//      ClaimsTaskListPage_InProgress.validateNavigationGASDSOnlyComplete()
//      Then("User navigates to 'What adjustments have you made to this claim?' page")
//      ClaimsTaskListPage_InProgress.clickReadDeclaration()
//      WhatAdjustmentsHaveYouMadeToThisClaimPage.validateNavigationAgent()
//      And("User validates 'What adjustments have you made to this claim?' page elements")
//      WhatAdjustmentsHaveYouMadeToThisClaimPage.validatePageContentAgent()
//      And("User validates 'What adjustments have you made to this claim?' page error message")
//      WhatAdjustmentsHaveYouMadeToThisClaimPage.validateErrorMessage()
//    }
//
//    Scenario(
//      "User navigates to the 'Declaration' page from the Gift Aid flow and validates the page elements"
//    ) {
//      Given("the user logs in through the Authority Wizard page")
//      AuthWizard.login(HASDIRECT, Organisation, "Organisation", "HMRC-CHAR-ORG", "CHARID", "PAGE-TEST-D11-GA")
//      Then("User navigates to 'Manage charity repayment claims' page and validates navigation")
//      CharitiesManagementPlaceholder.validateNavigationAgent()
//      And(
//        "User clicks the link 'Use the charities online service' to navigate to task list 'Make a charity repayment claim' page"
//      )
//      CharitiesManagementPlaceholder.clickUseTheCharitiesLink()
//      Then("User navigates to 'Make a charity repayment claim' page")
//      ClaimsTaskListPage_Empty.validateNavigationAgent()
//      And("User clicks the link to navigate to 'Repayment claim details' page")
//      ClaimsTaskListPage_Empty.clickProvideRepaymentClaimDetails()
//      Then("User validates the 'Repayment claim details' page")
//      RepaymentClaimDetailsPage.validateNavigationAgent()
//      And("User clicks continue on 'Repayment claim details' page")
//      RepaymentClaimDetailsPage.clickContinue()
//      Then("User navigates to 'Which type of repayment claim do you want to make?' page")
//      RepaymentCheckboxPage.validateNavigationAgent()
//      And("User selects 'Tax Repayments on Gift Aid donations' checkbox and clicks continue")
//      RepaymentCheckboxPage.checkbox(RepaymentCheckboxPage.GiftAid, true)
//      RepaymentCheckboxPage.clickContinue()
//      Then("User navigates to 'Do you have a claim reference number?' page")
//      DoYouHaveAClaimReferenceNumberPage.validateNavigationAgent()
//      And("User selects 'No' and clicks continue on 'Do you have a claim reference number?' page")
//      DoYouHaveAClaimReferenceNumberPage.radioButton(DoYouHaveAClaimReferenceNumberPage.no)
//      DoYouHaveAClaimReferenceNumberPage.clickContinue()
//      Then("User navigates to 'Check your repayment claim' page")
//      CheckYourRepaymentClaimPage.validateNavigationAgent()
//      CheckYourRepaymentClaimPage.clickContinue()
//      Then("User navigates to 'Make a charity repayment claim' page")
//      ClaimsTaskListPage_InProgress.validateNavigationAgent()
//      And("User clicks the link to navigate to 'About the organisation' page")
//      ClaimsTaskListPage_InProgress.clickProvideOrganisationDetails()
//      AboutTheOrganisationPage.validateNavigationAgent()
//      Then("User selects continue on 'About the organisation' page")
//      AboutTheOrganisationPage.clickContinue()
//      And("User navigates to 'What is the name of the charity regulator?' page")
//      WhatIsTheNameOfTheCharityRegulatorPage.validateNavigationAgent()
//      And("User selects they are not registered with a regulator")
//      WhatIsTheNameOfTheCharityRegulatorPage.radioButton(WhatIsTheNameOfTheCharityRegulatorPage.None)
//      WhatIsTheNameOfTheCharityRegulatorPage.clickContinue()
//      And("User navigates to 'Why is the charity not registered with a regulator?' page")
//      WhyIsTheCharityNotRegisteredPage.validateNavigationAgent()
//      And("User selects they are excepted")
//      WhyIsTheCharityNotRegisteredPage.radioButton(WhyIsTheCharityNotRegisteredPage.Excepted)
//      WhyIsTheCharityNotRegisteredPage.clickContinue()
//      And("User navigates to 'Your charity is excepted' page")
//      YourCharityIsExceptedPage.validateNavigationAgent()
//      Then("User selects continue on 'Your charity is excepted' page")
//      YourCharityIsExceptedPage.clickContinue()
//      And("User navigates to 'Is a corporate trustee making this claim?' page")
//      IsACorporateTrusteeMakingThisClaimPage.validateNavigationAgent()
//      And("User selects a corporate trustee is making this claim")
//      IsACorporateTrusteeMakingThisClaimPage.radioButton(IsACorporateTrusteeMakingThisClaimPage.yes)
//      IsACorporateTrusteeMakingThisClaimPage.clickContinue()
//      And("User navigates to 'Does the corporate trustee have a UK address?' page")
//      DoesTheCorporateTrusteeHaveAUKAddressPage.validateNavigationAgent()
//      And("User selects a corporate trustee does not have a UK address")
//      DoesTheCorporateTrusteeHaveAUKAddressPage.radioButton(DoesTheCorporateTrusteeHaveAUKAddressPage.no)
//      DoesTheCorporateTrusteeHaveAUKAddressPage.clickContinue()
//      And("User navigates to 'What are the corporate trustee details?' page")
//      CorporateTrusteeDetailsPage.validateNavigationAgent()
//      And("User enters their Non UK Trustee details and clicks continue")
//      CorporateTrusteeDetailsPage.enterNonUKTrusteeDetails("TEST TRUSTEE", "00-1-332-555-2368")
//      And("User navigates to 'Check your organisation details' page")
//      CheckYourOrganisationDetailsPage.validateNavigationAgent()
//      Then("User navigates to 'Make a charity repayment claim' page")
//      CheckYourOrganisationDetailsPage.clickContinue()
//      ClaimsTaskListPage_InProgress.validateNavigationAgent()
//      And("User clicks the link to navigate to 'Add Gift Aid schedule' page")
//      ClaimsTaskListPage_InProgress.clickAddGiftAidSchedule()
//      Then("User navigates to 'About Gift Aid schedule' page")
//      AboutGiftAidSchedulePage.validateNavigationAgent()
//      AboutGiftAidSchedulePage.clickContinue()
//      Then("User navigates to 'Upload a Gift Aid schedule' page")
//      UploadAGiftAidSchedulePage.validateNavigationAgent()
//      Then("User selects a file to upload in the 'Upload a Gift Aid schedule' page")
//      UploadAGiftAidSchedulePage.selectFile("GiftAidSpreadsheets/Gift-Aid-Schedule-SIMPLEPASS_MAX_ROWS")
//      UploadAGiftAidSchedulePage.clickContinue()
//      Then("User navigates to 'Your Gift Aid schedule upload' page")
//      YourGiftAidScheduleUploadPage.validateNavigationAgent()
//      YourGiftAidScheduleUploadPage.waitForFileUpload()
//      YourGiftAidScheduleUploadPage.clickContinue()
//      Then("User navigates to 'Check your Gift Aid schedule' page")
//      CheckYourGiftAidSchedulePage.validateNavigationAgent()
//      CheckYourGiftAidSchedulePage.radioButton(CheckYourGiftAidSchedulePage.no)
//      CheckYourGiftAidSchedulePage.clickContinue()
//      Then("User navigates to 'Successful Gift Aid Upload' page")
//      GiftAidUploadSuccessfulPage.validateNavigationAgent()
//      Then("User navigates to 'Make a charity repayment claim' page")
//      GiftAidUploadSuccessfulPage.clickContinue()
//      ClaimsTaskListPage_InProgress.validateNavigationAgent()
//      Then("User navigates to 'What adjustments have you made to this claim?' page")
//      ClaimsTaskListPage_InProgress.clickReadDeclaration()
//      WhatAdjustmentsHaveYouMadeToThisClaimPage.validateNavigationAgent()
//      Then("User navigates to 'Declaration' page")
//      WhatAdjustmentsHaveYouMadeToThisClaimPage.clickContinue()
//      DeclarationPage.validateNavigationAgent()
//      And("User validates 'Declaration' page elements")
//      DeclarationPage.validatePageContentAgent()
//    }
//
//    Scenario(
//      "User navigates to the 'Declaration' page from the Other Income flow and validates the page elements"
//    ) {
//      Given("the user logs in through the Authority Wizard page")
//      AuthWizard.login(HASDIRECT, Organisation, "Organisation", "HMRC-CHAR-ORG", "CHARID", "PAGE-TEST-D12-OI")
//      Then("User navigates to 'Manage charity repayment claims' page and validates navigation")
//      CharitiesManagementPlaceholder.validateNavigationAgent()
//      And(
//        "User clicks the link 'Use the charities online service' to navigate to task list 'Make a charity repayment claim' page"
//      )
//      CharitiesManagementPlaceholder.clickUseTheCharitiesLink()
//      Then("User navigates to 'Make a charity repayment claim' page")
//      ClaimsTaskListPage_Empty.validateNavigationAgent()
//      And("User clicks the link to navigate to 'Repayment claim details' page")
//      ClaimsTaskListPage_Empty.clickProvideRepaymentClaimDetails()
//      Then("User validates the 'Repayment claim details' page")
//      RepaymentClaimDetailsPage.validateNavigationAgent()
//      And("User clicks continue on 'Repayment claim details' page")
//      RepaymentClaimDetailsPage.clickContinue()
//      Then("User navigates to 'Which type of repayment claim do you want to make?' page")
//      RepaymentCheckboxPage.validateNavigationAgent()
//      And("User selects 'UK tax deducted from Other Income' checkbox and clicks continue")
//      RepaymentCheckboxPage.checkbox(RepaymentCheckboxPage.OtherIncome, true)
//      RepaymentCheckboxPage.clickContinue()
//      Then("User navigates to 'Do you have a claim reference number?' page")
//      DoYouHaveAClaimReferenceNumberPage.validateNavigationAgent()
//      And("User selects 'No' and clicks continue on 'Do you have a claim reference number?' page")
//      DoYouHaveAClaimReferenceNumberPage.radioButton(DoYouHaveAClaimReferenceNumberPage.no)
//      DoYouHaveAClaimReferenceNumberPage.clickContinue()
//      Then("User navigates to 'Check your repayment claim' page")
//      CheckYourRepaymentClaimPage.validateNavigationAgent()
//      CheckYourRepaymentClaimPage.clickContinue()
//      Then("User navigates to 'Make a charity repayment claim' page")
//      ClaimsTaskListPage_InProgress.validateNavigationAgent()
//      And("User clicks the link to navigate to 'About the organisation' page")
//      ClaimsTaskListPage_InProgress.clickProvideOrganisationDetails()
//      AboutTheOrganisationPage.validateNavigationAgent()
//      Then("User selects continue on 'About the organisation' page")
//      AboutTheOrganisationPage.clickContinue()
//      And("User navigates to 'What is the name of the charity regulator?' page")
//      WhatIsTheNameOfTheCharityRegulatorPage.validateNavigationAgent()
//      And("User selects they are not registered with a regulator")
//      WhatIsTheNameOfTheCharityRegulatorPage.radioButton(WhatIsTheNameOfTheCharityRegulatorPage.None)
//      WhatIsTheNameOfTheCharityRegulatorPage.clickContinue()
//      And("User navigates to 'Why is the charity not registered with a regulator?' page")
//      WhyIsTheCharityNotRegisteredPage.validateNavigationAgent()
//      And("User selects they are excepted")
//      WhyIsTheCharityNotRegisteredPage.radioButton(WhyIsTheCharityNotRegisteredPage.LowIncome)
//      WhyIsTheCharityNotRegisteredPage.clickContinue()
//      And("User navigates to 'Is a corporate trustee making this claim?' page")
//      IsACorporateTrusteeMakingThisClaimPage.validateNavigationAgent()
//      And("User selects a corporate trustee is making this claim")
//      IsACorporateTrusteeMakingThisClaimPage.radioButton(IsACorporateTrusteeMakingThisClaimPage.yes)
//      IsACorporateTrusteeMakingThisClaimPage.clickContinue()
//      And("User navigates to 'Does the corporate trustee have a UK address?' page")
//      DoesTheCorporateTrusteeHaveAUKAddressPage.validateNavigationAgent()
//      And("User selects a corporate trustee does not have a UK address")
//      DoesTheCorporateTrusteeHaveAUKAddressPage.radioButton(DoesTheCorporateTrusteeHaveAUKAddressPage.yes)
//      DoesTheCorporateTrusteeHaveAUKAddressPage.clickContinue()
//      And("User navigates to 'What are the corporate trustee details?' page")
//      CorporateTrusteeDetailsPage.validateNavigationAgent()
//      And("User enters their Non UK Trustee details and clicks continue")
//      CorporateTrusteeDetailsPage.enterUKTrusteeDetails("TEST TRUSTEE", "01632 960999", "WG7 7FU")
//      And("User navigates to 'Check your organisation details' page")
//      CheckYourOrganisationDetailsPage.validateNavigationAgent()
//      Then("User navigates to 'Make a charity repayment claim' page")
//      CheckYourOrganisationDetailsPage.clickContinue()
//      ClaimsTaskListPage_InProgress.validateNavigationAgent()
//      And("User clicks the link to navigate to 'Add Other Income schedule' page")
//      ClaimsTaskListPage_InProgress.clickAddOtherIncomeSchedule()
//      Then("User navigates to 'About Other Income schedule' page")
//      AboutOtherIncomeSchedulePage.validateNavigationAgent()
//      AboutOtherIncomeSchedulePage.clickContinue()
//      Then("User navigates to 'Upload a Other Income schedule' page")
//      UploadAnOtherIncomeSchedulePage.validateNavigationAgent()
//      Then("User selects a file to upload in the 'Upload a Other Income schedule' page")
//      UploadAnOtherIncomeSchedulePage.selectFile("OtherIncomeSpreadsheets/Other-Income-Schedule-GoodData")
//      UploadAnOtherIncomeSchedulePage.clickContinue()
//      Then("User navigates to 'Your Other Income schedule upload' page")
//      YourOtherIncomeScheduleUploadPage.validateNavigationAgent()
//      YourOtherIncomeScheduleUploadPage.waitForFileUpload()
//      YourOtherIncomeScheduleUploadPage.clickContinue()
//      Then("User navigates to 'Check your Other Income schedule' page")
//      CheckYourOtherIncomeSchedulePage.validateNavigationAgent()
//      CheckYourOtherIncomeSchedulePage.radioButton(CheckYourOtherIncomeSchedulePage.no)
//      CheckYourOtherIncomeSchedulePage.clickContinue()
//      Then("User navigates to 'Successful Other Income Upload' page")
//      OtherIncomeUploadSuccessfulPage.validateNavigationAgent()
//      Then("User navigates to 'Make a charity repayment claim' page")
//      OtherIncomeUploadSuccessfulPage.clickContinue()
//      ClaimsTaskListPage_InProgress.validateNavigationAgent()
//      Then("User navigates to 'What adjustments have you made to this claim?' page")
//      ClaimsTaskListPage_InProgress.clickReadDeclaration()
//      WhatAdjustmentsHaveYouMadeToThisClaimPage.validateNavigationAgent()
//      Then("User navigates to 'Declaration' page")
//      WhatAdjustmentsHaveYouMadeToThisClaimPage.enterAdjustmentDetails("TEST ADJUSTMENT INPUT")
//      DeclarationPage.validateNavigationAgent()
//      And("User validates 'Declaration' page elements")
//      DeclarationPage.validatePageContentAgent()
//    }
//
//    Scenario(
//      "User navigates to the 'Claim complete' page from the Gift Aid flow and validates the page elements"
//    ) {
//      Given("the user logs in through the Authority Wizard page")
//      AuthWizard.login(HASDIRECT, Organisation, "Organisation", "HMRC-CHAR-ORG", "CHARID", "XR4010")
//      Then("User navigates to 'Manage charity repayment claims' page and validates navigation")
//      CharitiesManagementPlaceholder.validateNavigationAgent()
//      And(
//        "User clicks the link 'Use the charities online service' to navigate to task list 'Make a charity repayment claim' page"
//      )
//      CharitiesManagementPlaceholder.clickUseTheCharitiesLink()
//      Then("User navigates to 'Make a charity repayment claim' page")
//      ClaimsTaskListPage_Empty.validateNavigationAgent()
//      And("User clicks the link to navigate to 'Repayment claim details' page")
//      ClaimsTaskListPage_Empty.clickProvideRepaymentClaimDetails()
//      Then("User validates the 'Repayment claim details' page")
//      RepaymentClaimDetailsPage.validateNavigationAgent()
//      And("User clicks continue on 'Repayment claim details' page")
//      RepaymentClaimDetailsPage.clickContinue()
//      Then("User navigates to 'Which type of repayment claim do you want to make?' page")
//      RepaymentCheckboxPage.validateNavigationAgent()
//      And("User selects 'Tax Repayments on Gift Aid donations' checkbox and clicks continue")
//      RepaymentCheckboxPage.checkbox(RepaymentCheckboxPage.GiftAid, true)
//      RepaymentCheckboxPage.clickContinue()
//      Then("User navigates to 'Do you have a claim reference number?' page")
//      DoYouHaveAClaimReferenceNumberPage.validateNavigationAgent()
//      And("User selects 'No' and clicks continue on 'Do you have a claim reference number?' page")
//      DoYouHaveAClaimReferenceNumberPage.radioButton(DoYouHaveAClaimReferenceNumberPage.no)
//      DoYouHaveAClaimReferenceNumberPage.clickContinue()
//      Then("User navigates to 'Check your repayment claim' page")
//      CheckYourRepaymentClaimPage.validateNavigationAgent()
//      CheckYourRepaymentClaimPage.clickContinue()
//      Then("User navigates to 'Make a charity repayment claim' page")
//      ClaimsTaskListPage_InProgress.validateNavigationAgent()
//      And("User clicks the link to navigate to 'About the organisation' page")
//      ClaimsTaskListPage_InProgress.clickProvideOrganisationDetails()
//      AboutTheOrganisationPage.validateNavigationAgent()
//      Then("User selects continue on 'About the organisation' page")
//      AboutTheOrganisationPage.clickContinue()
//      And("User navigates to 'What is the name of the charity regulator?' page")
//      WhatIsTheNameOfTheCharityRegulatorPage.validateNavigationAgent()
//      And("User selects they are not registered with a regulator")
//      WhatIsTheNameOfTheCharityRegulatorPage.radioButton(WhatIsTheNameOfTheCharityRegulatorPage.EngWal)
//      WhatIsTheNameOfTheCharityRegulatorPage.clickContinue()
//      And("User navigates to 'Why is the charity not registered with a regulator?' page")
//      WhatIsYourCharityRegulatorNumberPage.validateNavigationAgent()
//      And("User inputs a Charity Regulator number")
//      WhatIsYourCharityRegulatorNumberPage.enterCharityRegulatorNumber("123456")
//      And("User navigates to 'Is a corporate trustee making this claim?' page")
//      IsACorporateTrusteeMakingThisClaimPage.validateNavigationAgent()
//      And("User selects a corporate trustee is making this claim")
//      IsACorporateTrusteeMakingThisClaimPage.radioButton(IsACorporateTrusteeMakingThisClaimPage.yes)
//      IsACorporateTrusteeMakingThisClaimPage.clickContinue()
//      And("User navigates to 'Does the corporate trustee have a UK address?' page")
//      DoesTheCorporateTrusteeHaveAUKAddressPage.validateNavigationAgent()
//      And("User selects a corporate trustee does not have a UK address")
//      DoesTheCorporateTrusteeHaveAUKAddressPage.radioButton(DoesTheCorporateTrusteeHaveAUKAddressPage.no)
//      DoesTheCorporateTrusteeHaveAUKAddressPage.clickContinue()
//      And("User navigates to 'What are the corporate trustee details?' page")
//      CorporateTrusteeDetailsPage.validateNavigationAgent()
//      And("User enters their Non UK Trustee details and clicks continue")
//      CorporateTrusteeDetailsPage.enterNonUKTrusteeDetails("TEST TRUSTEE", "00-1-332-555-2368")
//      And("User navigates to 'Check your organisation details' page")
//      CheckYourOrganisationDetailsPage.validateNavigationAgent()
//      Then("User navigates to 'Make a charity repayment claim' page")
//      CheckYourOrganisationDetailsPage.clickContinue()
//      ClaimsTaskListPage_InProgress.validateNavigationAgent()
//      And("User clicks the link to navigate to 'Add Gift Aid schedule' page")
//      ClaimsTaskListPage_InProgress.clickAddGiftAidSchedule()
//      Then("User navigates to 'About Gift Aid schedule' page")
//      AboutGiftAidSchedulePage.validateNavigationAgent()
//      AboutGiftAidSchedulePage.clickContinue()
//      Then("User navigates to 'Upload a Gift Aid schedule' page")
//      UploadAGiftAidSchedulePage.validateNavigationAgent()
//      Then("User selects a file to upload in the 'Upload a Gift Aid schedule' page")
//      UploadAGiftAidSchedulePage.selectFile("GiftAidSpreadsheets/Gift-Aid-Schedule-SIMPLEPASS_MAX_ROWS")
//      UploadAGiftAidSchedulePage.clickContinue()
//      Then("User navigates to 'Your Gift Aid schedule upload' page")
//      YourGiftAidScheduleUploadPage.validateNavigationAgent()
//      YourGiftAidScheduleUploadPage.waitForFileUpload()
//      YourGiftAidScheduleUploadPage.clickContinue()
//      Then("User navigates to 'Check your Gift Aid schedule' page")
//      CheckYourGiftAidSchedulePage.validateNavigationAgent()
//      CheckYourGiftAidSchedulePage.radioButton(CheckYourGiftAidSchedulePage.no)
//      CheckYourGiftAidSchedulePage.clickContinue()
//      Then("User navigates to 'Successful Gift Aid Upload' page")
//      GiftAidUploadSuccessfulPage.validateNavigationAgent()
//      Then("User navigates to 'Make a charity repayment claim' page")
//      GiftAidUploadSuccessfulPage.clickContinue()
//      ClaimsTaskListPage_InProgress.validateNavigationAgent()
//      Then("User navigates to 'What adjustments have you made to this claim?' page")
//      ClaimsTaskListPage_InProgress.clickReadDeclaration()
//      WhatAdjustmentsHaveYouMadeToThisClaimPage.validateNavigationAgent()
//      Then("User navigates to 'Declaration' page")
//      WhatAdjustmentsHaveYouMadeToThisClaimPage.clickContinue()
//      DeclarationPage.validateNavigationAgent()
//      Then("User navigates to 'Claim complete' page")
//      DeclarationPage.clickContinue()
//      ClaimCompletePage.validateNavigationAgent()
//      And("User validates 'Claim complete' page elements")
//      ClaimCompletePage.validatePageContentAgent()
//      And("User validates Submission Reference Number is in BASE32 format")
//      ClaimCompletePage.verifySubmissionReferenceBase32()
//    }
//
//    Scenario(
//      "User navigates to the 'Charity Repayment Claim Summary' page from the Gift Aid/Other Income/Adjustments and validates the page elements"
//    ) {
//      Given("the user logs in through the Authority Wizard page")
//      AuthWizard.login(HASDIRECT, Organisation, "Organisation", "HMRC-CHAR-ORG", "CHARID", "IT00078")
//      Then("User navigates to 'Manage charity repayment claims' page and validates navigation")
//      CharitiesManagementPlaceholder.validateNavigationAgent()
//      And(
//        "User clicks the link 'Use the charities online service' to navigate to task list 'Make a charity repayment claim' page"
//      )
//      CharitiesManagementPlaceholder.clickUseTheCharitiesLink()
//      Then("User navigates to 'Make a charity repayment claim' page")
//      ClaimsTaskListPage_Empty.validateNavigationAgent()
//      And("User clicks the link to navigate to 'Repayment claim details' page")
//      ClaimsTaskListPage_Empty.clickProvideRepaymentClaimDetails()
//      Then("User validates the 'Repayment claim details' page")
//      RepaymentClaimDetailsPage.validateNavigationAgent()
//      And("User clicks continue on 'Repayment claim details' page")
//      RepaymentClaimDetailsPage.clickContinue()
//      Then("User navigates to 'Which type of repayment claim do you want to make?' page")
//      RepaymentCheckboxPage.validateNavigationAgent()
//      And(
//        "User selects 'Tax repayments on Gift Aid donations' and 'UK tax deducted from Other Income' checkboxes and clicks continue"
//      )
//      RepaymentCheckboxPage.checkbox(RepaymentCheckboxPage.GiftAid, true)
//      RepaymentCheckboxPage.checkbox(RepaymentCheckboxPage.OtherIncome, true)
//      RepaymentCheckboxPage.clickContinue()
//      Then("User navigates to 'Do you have a claim reference number?' page")
//      DoYouHaveAClaimReferenceNumberPage.validateNavigationAgent()
//      And("User selects 'No' and clicks continue on 'Do you have a claim reference number?' page")
//      DoYouHaveAClaimReferenceNumberPage.radioButton(DoYouHaveAClaimReferenceNumberPage.no)
//      DoYouHaveAClaimReferenceNumberPage.clickContinue()
//      Then("User navigates to 'Check your repayment claim' page")
//      CheckYourRepaymentClaimPage.validateNavigationAgent()
//      CheckYourRepaymentClaimPage.clickContinue()
//      Then("User navigates to 'Make a charity repayment claim' page")
//      ClaimsTaskListPage_InProgress.validateNavigationAgent()
//      And("User clicks the link to navigate to 'About the organisation' page")
//      ClaimsTaskListPage_InProgress.clickProvideOrganisationDetails()
//      AboutTheOrganisationPage.validateNavigationAgent()
//      Then("User selects continue on 'About the organisation' page")
//      AboutTheOrganisationPage.clickContinue()
//      And("User navigates to 'What is the name of the charity regulator?' page")
//      WhatIsTheNameOfTheCharityRegulatorPage.validateNavigationAgent()
//      And("User selects they are not registered with a regulator")
//      WhatIsTheNameOfTheCharityRegulatorPage.radioButton(WhatIsTheNameOfTheCharityRegulatorPage.EngWal)
//      WhatIsTheNameOfTheCharityRegulatorPage.clickContinue()
//      And("User navigates to 'Why is the charity not registered with a regulator?' page")
//      WhatIsYourCharityRegulatorNumberPage.validateNavigationAgent()
//      And("User inputs a Charity Regulator number")
//      WhatIsYourCharityRegulatorNumberPage.enterCharityRegulatorNumber("123456")
//      And("User navigates to 'Is a corporate trustee making this claim?' page")
//      IsACorporateTrusteeMakingThisClaimPage.validateNavigationAgent()
//      And("User selects a corporate trustee is making this claim")
//      IsACorporateTrusteeMakingThisClaimPage.radioButton(IsACorporateTrusteeMakingThisClaimPage.yes)
//      IsACorporateTrusteeMakingThisClaimPage.clickContinue()
//      And("User navigates to 'Does the corporate trustee have a UK address?' page")
//      DoesTheCorporateTrusteeHaveAUKAddressPage.validateNavigationAgent()
//      And("User selects a corporate trustee does not have a UK address")
//      DoesTheCorporateTrusteeHaveAUKAddressPage.radioButton(DoesTheCorporateTrusteeHaveAUKAddressPage.no)
//      DoesTheCorporateTrusteeHaveAUKAddressPage.clickContinue()
//      And("User navigates to 'What are the corporate trustee details?' page")
//      CorporateTrusteeDetailsPage.validateNavigationAgent()
//      And("User enters their Non UK Trustee details and clicks continue")
//      CorporateTrusteeDetailsPage.enterNonUKTrusteeDetails("TEST TRUSTEE", "00-1-332-555-2368")
//      And("User navigates to 'Check your organisation details' page")
//      CheckYourOrganisationDetailsPage.validateNavigationAgent()
//      Then("User navigates to 'Make a charity repayment claim' page")
//      CheckYourOrganisationDetailsPage.clickContinue()
//      ClaimsTaskListPage_InProgress.validateNavigationAgent()
//      And("User clicks the link to navigate to 'Add Gift Aid schedule' page")
//      ClaimsTaskListPage_InProgress.clickAddGiftAidSchedule()
//      Then("User navigates to 'About Gift Aid schedule' page")
//      AboutGiftAidSchedulePage.validateNavigationAgent()
//      AboutGiftAidSchedulePage.clickContinue()
//      Then("User navigates to 'Upload a Gift Aid schedule' page")
//      UploadAGiftAidSchedulePage.validateNavigationAgent()
//      Then("User selects a file to upload in the 'Upload a Gift Aid schedule' page")
//      UploadAGiftAidSchedulePage.selectFile("GiftAidSpreadsheets/Gift-Aid-Schedule-summary")
//      UploadAGiftAidSchedulePage.clickContinue()
//      Then("User navigates to 'Your Gift Aid schedule upload' page")
//      YourGiftAidScheduleUploadPage.validateNavigationAgent()
//      YourGiftAidScheduleUploadPage.waitForFileUpload()
//      YourGiftAidScheduleUploadPage.clickContinue()
//      Then("User navigates to 'Check your Gift Aid schedule' page")
//      CheckYourGiftAidSchedulePage.validateNavigationAgent()
//      CheckYourGiftAidSchedulePage.radioButton(CheckYourGiftAidSchedulePage.no)
//      CheckYourGiftAidSchedulePage.clickContinue()
//      Then("User navigates to 'Successful Gift Aid Upload' page")
//      GiftAidUploadSuccessfulPage.validateNavigationAgent()
//      Then("User navigates to 'Make a charity repayment claim' page")
//      GiftAidUploadSuccessfulPage.clickContinue()
//      ClaimsTaskListPage_InProgress.validateNavigationAgent()
//      And("User clicks the link to navigate to 'Add Other Income schedule' page")
//      ClaimsTaskListPage_InProgress.clickAddOtherIncomeSchedule()
//      Then("User navigates to 'About Other Income schedule' page")
//      AboutOtherIncomeSchedulePage.validateNavigationAgent()
//      AboutOtherIncomeSchedulePage.clickContinue()
//      Then("User navigates to 'Upload a Other Income schedule' page")
//      UploadAnOtherIncomeSchedulePage.validateNavigationAgent()
//      Then("User selects a file to upload in the 'Upload a Other Income schedule' page")
//      UploadAnOtherIncomeSchedulePage.selectFile("OtherIncomeSpreadsheets/Other-Income-Summary")
//      UploadAnOtherIncomeSchedulePage.clickContinue()
//      Then("User navigates to 'Your Other Income schedule upload' page")
//      YourOtherIncomeScheduleUploadPage.validateNavigationAgent()
//      YourOtherIncomeScheduleUploadPage.waitForFileUpload()
//      YourOtherIncomeScheduleUploadPage.clickContinue()
//      Then("User navigates to 'Check your Other Income schedule' page")
//      CheckYourOtherIncomeSchedulePage.validateNavigationAgent()
//      CheckYourOtherIncomeSchedulePage.radioButton(CheckYourOtherIncomeSchedulePage.no)
//      CheckYourOtherIncomeSchedulePage.clickContinue()
//      Then("User navigates and validates 'Successful Other Income Upload' page")
//      OtherIncomeUploadSuccessfulPage.validateNavigationAgent()
//      OtherIncomeUploadSuccessfulPage.validatePageContentAgent()
//      Then("User navigates to 'Make a charity repayment claim' page")
//      GiftAidUploadSuccessfulPage.clickContinue()
//      ClaimsTaskListPage_InProgress.validateNavigationAgent()
//      Then("User navigates to 'What adjustments have you made to this claim?' page")
//      ClaimsTaskListPage_InProgress.clickReadDeclaration()
//      WhatAdjustmentsHaveYouMadeToThisClaimPage.validateNavigationAgent()
//      And("User enters details on adjustments page and navigates to Declaration Page")
//      WhatAdjustmentsHaveYouMadeToThisClaimPage.enterAdjustmentDetails("TEST ADJUSTMENT INPUT")
//      DeclarationPage.validateNavigationAgent()
//      Then("User navigates to 'Claim complete' page")
//      DeclarationPage.clickContinue()
//      ClaimCompletePage.validateNavigationAgent()
//      And("User validates 'Claim complete' page elements")
//      ClaimCompletePage.validatePageContentAgent()
//      Then("User navigates to 'Charity repayment claim summary' page")
//      ClaimCompletePage.clickPrintClaimSummaryLink()
//      And("User validates Static 'Headers' in Summary page ")
//      CharityRepaymentClaimSummaryPage.validateNavigationAgent()
//      And("User validates Submission Reference Number is in BASE32 format")
//      CharityRepaymentClaimSummaryPage.verifySubmissionReferenceBase32()
//      And("User validates Gift Aid, Other Income and Adjustment Headings on Page")
//      CharityRepaymentClaimSummaryPage.validateGiftAidHeading()
//      CharityRepaymentClaimSummaryPage.validateOtherIncomeHeading()
//      CharityRepaymentClaimSummaryPage.validateAdjustmentHeading()
//      Then("User Validates the Gift aid data extracted from GA ODS")
//      CharityRepaymentClaimSummaryPage.assertAllSummaryPairsExactlyAt(1)(
//        "Number of Gift Aid donations"                              -> "1000",
//        "Total value of Gift Aid donations claimed"                 -> "£1000.00"
//      )
//      Then("User Validates the Other Income data extracted from OI ODS")
//      CharityRepaymentClaimSummaryPage.assertAllSummaryPairsExactlyAt(2)(
//        "Number of Other Income items"                              -> "5",
//        "Total value of Other Income claimed"                       -> "£126.00"
//      )
//      And("User Validates the Adjustment overclaimed amount summation of GA and OI")
//      CharityRepaymentClaimSummaryPage.assertAllSummaryPairsExactlyAt(3)(
//        "Total tax relief overclaimed in Gift Aid and Other Income" -> "£1000000000.00"
//      )
//      Then(
//        "User Validates the 3 links: 'Print Summary', 'Log out and go back HMRC online services' and 'Go to Your HMRC services exist'"
//      )
//      CharityRepaymentClaimSummaryPage.validateSummaryPageLinks()
//    }
//
//    Scenario(
//      "User navigates to the 'Charity Repayment Claim Summary' page from the GASDS Only, NO Adjustments, and validates the page elements"
//    ) {
//      Given("the user logs in through the Authority Wizard page")
//      AuthWizard.login(HASDIRECT, Organisation, "Organisation", "HMRC-CHAR-ORG", "CHARID", "XR4010")
//      Then("User navigates to 'Manage charity repayment claims' page and validates navigation")
//      CharitiesManagementPlaceholder.validateNavigationAgent()
//      And(
//        "User clicks the link 'Use the charities online service' to navigate to task list 'Make a charity repayment claim' page"
//      )
//      CharitiesManagementPlaceholder.clickUseTheCharitiesLink()
//      Then("User navigates to 'Make a charity repayment claim' page")
//      ClaimsTaskListPage_Empty.validateNavigationAgent()
//      And("User clicks the link to navigate to 'Repayment claim details' page")
//      ClaimsTaskListPage_Empty.clickProvideRepaymentClaimDetails()
//      Then("User validates the 'Repayment claim details' page")
//      RepaymentClaimDetailsPage.validateNavigationAgent()
//      And("User clicks continue on 'Repayment claim details' page")
//      RepaymentClaimDetailsPage.clickContinue()
//      Then("User navigates to 'Which type of repayment claim do you want to make?' page")
//      RepaymentCheckboxPage.validateNavigationAgent()
//      And("User selects 'GASDS' checkbox and clicks continue")
//      RepaymentCheckboxPage.checkbox(RepaymentCheckboxPage.GASDSclaim, true)
//      RepaymentCheckboxPage.clickContinue()
//      And("User navigates to 'Gift Aid Small Donations Scheme (GASDS) details' checkbox page")
//      GASDSCheckboxPage.validateNavigationAgent()
//      Then("User validates entire page content on the 'Gift Aid Small Donations Scheme (GASDS) details' checkbox page")
//      GASDSCheckboxPage.validatePageContentAgent()
//      And("User selects 'GASDS top-up' checkbox and clicks continue")
//      GASDSCheckboxPage.checkbox(GASDSCheckboxPage.GASDSTopUp, true)
//      GASDSCheckboxPage.clickContinue()
//      Then("User navigates to 'Gift Aid Small Donations Scheme claim' page")
//      GiftAidSmallDonationsSchemeClaimPage.validateNavigationAgent()
//      And("User selects 'Yes' and clicks continue on 'Gift Aid Small Donations Scheme claim' page")
//      GiftAidSmallDonationsSchemeClaimPage.radioButton(GiftAidSmallDonationsSchemeClaimPage.no)
//      GiftAidSmallDonationsSchemeClaimPage.clickContinue()
//      Then("User navigates to 'Do you have a claim reference number?' page")
//      DoYouHaveAClaimReferenceNumberPage.validateNavigationAgent()
//      And("User selects 'No' and clicks continue on 'Do you have a claim reference number?' page")
//      DoYouHaveAClaimReferenceNumberPage.radioButton(DoYouHaveAClaimReferenceNumberPage.no)
//      DoYouHaveAClaimReferenceNumberPage.clickContinue()
//      Then("User navigates to 'Check your repayment claim' page")
//      CheckYourRepaymentClaimPage.validateNavigationAgent()
//      CheckYourRepaymentClaimPage.clickContinue()
//      Then("User navigates to 'Make a charity repayment claim' page")
//      ClaimsTaskListPage_InProgress.validateNavigationGASDSOnlyComplete()
//      And("User clicks the link to navigate to 'About the organisation' page")
//      ClaimsTaskListPage_InProgress.clickProvideOrganisationDetails()
//      AboutTheOrganisationPage.validateNavigationAgent()
//      Then("User selects continue on 'About the organisation' page")
//      AboutTheOrganisationPage.clickContinue()
//      And("User navigates to 'What is the name of the charity regulator?' page")
//      WhatIsTheNameOfTheCharityRegulatorPage.validateNavigationAgent()
//      And("User selects they are not registered with a regulator")
//      WhatIsTheNameOfTheCharityRegulatorPage.radioButton(WhatIsTheNameOfTheCharityRegulatorPage.None)
//      WhatIsTheNameOfTheCharityRegulatorPage.clickContinue()
//      And("User navigates to 'Why is the charity not registered with a regulator?' page")
//      WhyIsTheCharityNotRegisteredPage.validateNavigationAgent()
//      And("User selects they are excepted")
//      WhyIsTheCharityNotRegisteredPage.radioButton(WhyIsTheCharityNotRegisteredPage.LowIncome)
//      WhyIsTheCharityNotRegisteredPage.clickContinue()
//      And("User navigates to 'Is a corporate trustee making this claim?' page")
//      IsACorporateTrusteeMakingThisClaimPage.validateNavigationAgent()
//      And("User selects a corporate trustee is making this claim")
//      IsACorporateTrusteeMakingThisClaimPage.radioButton(IsACorporateTrusteeMakingThisClaimPage.yes)
//      IsACorporateTrusteeMakingThisClaimPage.clickContinue()
//      And("User navigates to 'Does the corporate trustee have a UK address?' page")
//      DoesTheCorporateTrusteeHaveAUKAddressPage.validateNavigationAgent()
//      And("User selects a corporate trustee does not have a UK address")
//      DoesTheCorporateTrusteeHaveAUKAddressPage.radioButton(DoesTheCorporateTrusteeHaveAUKAddressPage.no)
//      DoesTheCorporateTrusteeHaveAUKAddressPage.clickContinue()
//      And("User navigates to 'What are the corporate trustee details?' page")
//      CorporateTrusteeDetailsPage.validateNavigationAgent()
//      And("User enters their Non UK Trustee details and clicks continue")
//      CorporateTrusteeDetailsPage.enterNonUKTrusteeDetails("TEST TRUSTEE", "01632 960999")
//      And("User navigates to 'Check your organisation details' page")
//      CheckYourOrganisationDetailsPage.validateNavigationAgent()
//      Then("User navigates to 'Make a charity repayment claim' page")
//      CheckYourOrganisationDetailsPage.clickContinue()
//      ClaimsTaskListPage_InProgress.validateNavigationGASDSOnlyComplete()
//      And("User clicks the link to navigate to 'About Gift Aid Small Donations Scheme schedule' page")
//      ClaimsTaskListPage_InProgress.clickProvideGASDSDetails()
//      And("User Validates the navigation to 'About Gift Aid Small Donations Scheme schedule' page")
//      AboutGASDSPage.validateNavigationAgent()
//      Then("User navigates to 'Which tax year are you claiming for?' year 1 page")
//      AboutGASDSPage.clickContinue()
//      WhichTaxYearAreYouClaimingForPage.validateNavigation1()
//      Then(
//        s"User navigates to 'Which tax year are you claiming for?' page and inputs: " + WhichTaxYearAreYouClaimingForPage.earliestTaxYear
//      )
//      WhichTaxYearAreYouClaimingForPage.enterValidTaxYear(WhichTaxYearAreYouClaimingForPage.earliestTaxYear)
//      Then("User navigates to 'What donation amount are you claiming under GASDS, in pounds?' for the first year page")
//      WhatDonationAmountAreYouClaimingUnderGASDSPage.validateNavigation_Year1()
//      Then(
//        "User inputs a value on 'What donation amount are you claiming under GASDS, in pounds?' for the first year page"
//      )
//      WhatDonationAmountAreYouClaimingUnderGASDSPage.enterDonationAmount("543.21")
//      Then("User navigates to 'Check your claim details for tax year 1' page")
//      CheckYourClaimDetailsForTaxYearPage.validateNavigation1()
//      Then("User navigates to 'You have added a claim for 1 tax year' page")
//      CheckYourClaimDetailsForTaxYearPage.clickContinue()
//      YouHaveAddedAClaimForXTaxYearPage.validateNavigation1()
//      Then("User selects 'Yes' on 'You have added a claim for 1 tax year' page to add another tax year")
//      YouHaveAddedAClaimForXTaxYearPage.radioButton(YouHaveAddedAClaimForXTaxYearPage.yes)
//      YouHaveAddedAClaimForXTaxYearPage.clickContinue()
//      Then("User navigates to 'Which tax year are you claiming for?' year 2 page")
//      WhichTaxYearAreYouClaimingForPage.validateNavigation2()
//      Then(
//        s"User navigates to 'Which tax year are you claiming for?' page and inputs: " + WhichTaxYearAreYouClaimingForPage.secondEarliestTaxYear
//      )
//      WhichTaxYearAreYouClaimingForPage.enterValidTaxYear(WhichTaxYearAreYouClaimingForPage.secondEarliestTaxYear)
//      Then("User navigates to 'What donation amount are you claiming under GASDS, in pounds?' for the second year page")
//      WhatDonationAmountAreYouClaimingUnderGASDSPage.validateNavigation_Year2()
//      Then(
//        "User inputs a value on 'What donation amount are you claiming under GASDS, in pounds?' for the second year page"
//      )
//      WhatDonationAmountAreYouClaimingUnderGASDSPage.enterDonationAmount("111.11")
//      Then("User navigates to 'Check your claim details for tax year 2' page")
//      CheckYourClaimDetailsForTaxYearPage.validateNavigation2()
//      Then("User navigates to 'You have added a claim for 2 tax years' page")
//      CheckYourClaimDetailsForTaxYearPage.clickContinue()
//      YouHaveAddedAClaimForXTaxYearPage.validateNavigation2()
//      Then("User selects 'Yes' on 'You have added a claim for 2 tax year' page to add another tax year")
//      YouHaveAddedAClaimForXTaxYearPage.radioButton(YouHaveAddedAClaimForXTaxYearPage.yes)
//      YouHaveAddedAClaimForXTaxYearPage.clickContinue()
//      Then("User navigates to 'Which tax year are you claiming for?' year 3 page")
//      WhichTaxYearAreYouClaimingForPage.validateNavigation3()
//      Then(
//        s"User navigates to 'Which tax year are you claiming for?' page and inputs: " + WhichTaxYearAreYouClaimingForPage.recentTaxYear
//      )
//      WhichTaxYearAreYouClaimingForPage.enterValidTaxYear(WhichTaxYearAreYouClaimingForPage.recentTaxYear)
//      Then("User navigates to 'What donation amount are you claiming under GASDS, in pounds?' for the third year page")
//      WhatDonationAmountAreYouClaimingUnderGASDSPage.validateNavigation_Year3()
//      Then(
//        "User inputs a value on 'What donation amount are you claiming under GASDS, in pounds?' for the third year page"
//      )
//      WhatDonationAmountAreYouClaimingUnderGASDSPage.enterDonationAmount("3.33")
//      Then("User navigates to 'Check your claim details for tax year 3' page")
//      CheckYourClaimDetailsForTaxYearPage.validateNavigation3()
//      Then("User navigates to 'You have added a claim for 3 tax years' page and validates navigation")
//      CheckYourClaimDetailsForTaxYearPage.clickContinue()
//      YouHaveAddedAClaimForXTaxYearPage.validateNavigation3()
//      And("User Clicks Continue on 'You have added a claim for 3 tax years' page")
//      YouHaveAddedAClaimForXTaxYearPage.clickContinue()
//      Then("User navigates to 'Check your GASDS donation details' page and validates page details")
//      CheckYourGASDSDonationDetailsPage.validateNavigationAgent()
//      Then("User clicks CONTINUE to reach task list: 'Make a repayment Claim' Page")
//      CheckYourGASDSDonationDetailsPage.clickContinue()
//      And("User validates navigation to 'Make a repayment Claim' Page")
//      ClaimsTaskListPage_InProgress.validateNavigationGASDSOnlyComplete()
//      Then("User navigates to 'What adjustments have you made to this claim?' page")
//      ClaimsTaskListPage_InProgress.clickReadDeclaration()
//      WhatAdjustmentsHaveYouMadeToThisClaimPage.validateNavigationAgent()
//      And("User enters details on adjustments page and navigates to Declaration Page")
//      WhatAdjustmentsHaveYouMadeToThisClaimPage.enterAdjustmentDetails("TEST ADJUSTMENT INPUT")
//      DeclarationPage.validateNavigationAgent()
//      Then("User navigates to 'Claim complete' page")
//      DeclarationPage.clickContinue()
//      ClaimCompletePage.validateNavigationAgent()
//      And("User validates 'Claim complete' page elements")
//      ClaimCompletePage.validatePageContentAgent()
//      Then("User navigates to 'Charity repayment claim summary' page")
//      ClaimCompletePage.clickPrintClaimSummaryLink()
//      And("User validates Static 'Headers' in Summary page")
//      CharityRepaymentClaimSummaryPage.validateNavigationAgent()
//      And("User validates Submission Reference Number is in BASE32 format")
//      CharityRepaymentClaimSummaryPage.verifySubmissionReferenceBase32()
//      And("User validates GASDS Heading on Page")
//      CharityRepaymentClaimSummaryPage.validateGASDSHeading()
//      Then("User Validates the GASDS data extracted from User Input")
//      CharityRepaymentClaimSummaryPage.assertAllSummaryPairsExactlyAt(1)(
//        "Total value of GASDS donations (not collected in a Community Building)" -> "£657.65"
//      )
//      Then(
//        "User Validates the 3 links: 'Print Summary', 'Log out and go back HMRC online services' and 'Go to Your HMRC services exist'"
//      )
//      CharityRepaymentClaimSummaryPage.validateSummaryPageLinks()
//    }
    
  }
}
