/*
 * Copyright 2026 HM Revenue & Customs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package uk.gov.hmrc.ui.specs

import org.scalatest.featurespec.AnyFeatureSpec
import org.scalatest.verbs.ShouldVerb
import org.scalatest.{BeforeAndAfterAll, BeforeAndAfterEach, GivenWhenThen}
import uk.gov.hmrc.selenium.webdriver.{Browser, ScreenshotOnFailure}
import uk.gov.hmrc.ui.pages.*
import uk.gov.hmrc.ui.util.Users.LoginTypes.HASDIRECT
import uk.gov.hmrc.ui.util.Users.UserTypes.Agent
import uk.gov.hmrc.ui.util.Users.UserTypes.Organisation

class DataGuardSpec
    extends AnyFeatureSpec
    with BaseSpec
    with GivenWhenThen
    with ShouldVerb
    with BeforeAndAfterAll
    with BeforeAndAfterEach
    with Browser
    with ScreenshotOnFailure {

  Feature("Charities - Organisation&Agent - Dataguard checks") {
    Scenario(
      "User URL hops to 'Charity Name' page whilst being an org user"
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.login(HASDIRECT, Organisation, "Organisation", "HMRC-CHAR-ORG", "CHARID", "DATAGUARD-AGENT")
      Then("User navigates to 'Manage charity repayment claims' page and validates navigation")
      CharitiesManagementPlaceholder.validateNavigation()
      And(
        "User clicks the link 'Use the charities online service' to navigate to task list 'Make a charity repayment claim' page"
      )
      CharitiesManagementPlaceholder.clickUseTheCharitiesLink()
      Then("User navigates to 'Make a charity repayment claim' page")
      ClaimsTaskListPage_Empty.validateNavigation()
      Then("User URL hops to 'Charity name' page")
      WhatIsTheNameOfCharityOrCASC.navigateToPage(WhatIsTheNameOfTheCharityRegulatorPage.pageUrl)
      Then("User validates the 'Claims task lisk' Page")
      ClaimsTaskListPage_Empty.validateNavigation()

    }
    Scenario(
      "User URL hops to 'HMRC Charities ref number' page whilst being an org user"
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.login(HASDIRECT, Organisation, "Organisation", "HMRC-CHAR-ORG", "CHARID", "DATAGUARD-AGENT")
      Then("User navigates to 'Manage charity repayment claims' page and validates navigation")
      CharitiesManagementPlaceholder.validateNavigation()
      And(
        "User clicks the link 'Use the charities online service' to navigate to task list 'Make a charity repayment claim' page"
      )
      CharitiesManagementPlaceholder.clickUseTheCharitiesLink()
      Then("User navigates to 'Make a charity repayment claim' page")
      ClaimsTaskListPage_Empty.validateNavigation()
      Then("User URL hops to 'HMRC charities ref number' page")
      WhatIsYourHMRCReferenceNumberPage.navigateToPage(WhatIsYourHMRCReferenceNumberPage.pageUrl)
      Then("User validates the 'Claims task lisk' Page")
      ClaimsTaskListPage_Empty.validateNavigation()

    }

    Scenario(
      "User URL hops to 'Who should we send the payment to' page whilst being an org user"
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.login(HASDIRECT, Organisation, "Organisation", "HMRC-CHAR-ORG", "CHARID", "DATAGUARD-AGENT")
      Then("User navigates to 'Manage charity repayment claims' page and validates navigation")
      CharitiesManagementPlaceholder.validateNavigation()
      And(
        "User clicks the link 'Use the charities online service' to navigate to task list 'Make a charity repayment claim' page"
      )
      CharitiesManagementPlaceholder.clickUseTheCharitiesLink()
      Then("User navigates to 'Make a charity repayment claim' page")
      ClaimsTaskListPage_Empty.validateNavigation()
      Then("User URL hops to 'Who should we send the payment to' page")
      WhoShouldHMRCSendPaymentToPage.navigateToPage(WhoShouldHMRCSendPaymentToPage.pageUrl)
      Then("User validates the 'Claims task lisk' Page")
      ClaimsTaskListPage_Empty.validateNavigation()

    }

    Scenario(
      "User URL hops to 'Agent's telephone number' page whilst being an org user"
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.login(HASDIRECT, Organisation, "Organisation", "HMRC-CHAR-ORG", "CHARID", "DATAGUARD-AGENT")
      Then("User navigates to 'Manage charity repayment claims' page and validates navigation")
      CharitiesManagementPlaceholder.validateNavigation()
      And(
        "User clicks the link 'Use the charities online service' to navigate to task list 'Make a charity repayment claim' page"
      )
      CharitiesManagementPlaceholder.clickUseTheCharitiesLink()
      Then("User navigates to 'Make a charity repayment claim' page")
      ClaimsTaskListPage_Empty.validateNavigation()
      Then("User URL hops to 'Agent's telephone number' page")
      WhatIsYourTelephoneNumberPage.navigateToPage(WhatIsYourTelephoneNumberPage.pageUrl)
      Then("User validates the 'Claims task lisk' Page")
      ClaimsTaskListPage_Empty.validateNavigation()

    }
    Scenario(
      "User URL hops to 'Agent UK address' page whilst being an org user"
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.login(HASDIRECT, Organisation, "Organisation", "HMRC-CHAR-ORG", "CHARID", "DATAGUARD-AGENT")
      Then("User navigates to 'Manage charity repayment claims' page and validates navigation")
      CharitiesManagementPlaceholder.validateNavigation()
      And(
        "User clicks the link 'Use the charities online service' to navigate to task list 'Make a charity repayment claim' page"
      )
      CharitiesManagementPlaceholder.clickUseTheCharitiesLink()
      Then("User navigates to 'Make a charity repayment claim' page")
      ClaimsTaskListPage_Empty.validateNavigation()
      Then("User URL hops to 'Agent Uk Address' page")
      DoYouHaveAUKAddressPage.navigateToPage(DoYouHaveAUKAddressPage.pageUrl)
      Then("User validates the 'Claims task lisk' Page")
      ClaimsTaskListPage_Empty.validateNavigation()

    }
    Scenario(
      "User URL hops to 'Agent Postcode' page whilst being an org user"
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.login(HASDIRECT, Organisation, "Organisation", "HMRC-CHAR-ORG", "CHARID", "DATAGUARD-AGENT")
      Then("User navigates to 'Manage charity repayment claims' page and validates navigation")
      CharitiesManagementPlaceholder.validateNavigation()
      And(
        "User clicks the link 'Use the charities online service' to navigate to task list 'Make a charity repayment claim' page"
      )
      CharitiesManagementPlaceholder.clickUseTheCharitiesLink()
      Then("User navigates to 'Make a charity repayment claim' page")
      ClaimsTaskListPage_Empty.validateNavigation()
      Then("User URL hops to 'Agent Postcode' page")
      WhatIsYourPostcodePage.navigateToPage(WhatIsYourPostcodePage.pageUrl)
      Then("User validates the 'Claims task lisk' Page")
      ClaimsTaskListPage_Empty.validateNavigation()

    }
    Scenario(
      "User URL hops to 'Delete Repayment Claim ' page whilst being an org user"
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.login(HASDIRECT, Organisation, "Organisation", "HMRC-CHAR-ORG", "CHARID", "DATAGUARD-AGENT")
      Then("User navigates to 'Manage charity repayment claims' page and validates navigation")
      CharitiesManagementPlaceholder.validateNavigation()
      And(
        "User clicks the link 'Use the charities online service' to navigate to task list 'Make a charity repayment claim' page"
      )
      CharitiesManagementPlaceholder.clickUseTheCharitiesLink()
      Then("User navigates to 'Make a charity repayment claim' page")
      ClaimsTaskListPage_Empty.validateNavigation()
      Then("User URL hops to 'Agent Postcode' page")
      DeleteCharityRepaymentAgentPage.navigateToPage(DeleteCharityRepaymentAgentPage.pageUrl)
      Then("User validates the 'Claims task lisk' Page")
      ClaimsTaskListPage_Empty.validateNavigation()

    }
    Scenario(
      "User URL hops to 'Corporate trustee' page whilst being an agent user"
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.loginAgent(HASDIRECT, Agent, "Agent", "HMRC-CHAR-AGENT", "AGENTCHARID", "DATAGUARD-ORGANISATION")
      Then("User navigates to 'Manage charity repayment claims' page and validates navigation")
      CharitiesManagementAgent.validateNavigationAgent()
      And(
        "User clicks the link 'Use the charities online service' to navigate to task list 'Make a charity repayment claim' page"
      )
      CharitiesManagementAgent.clickUseTheCharitiesLink()
      Then("User navigates and validates the 'Repayment claim details' page")
      RepaymentClaimDetailsPage.validateNavigationAgent()
      RepaymentClaimDetailsPage.validateParagraphAgent()
      Then("User URL hops to 'Corporate trustee' page")
      IsACorporateTrusteeMakingThisClaimPage.navigateToPage(IsACorporateTrusteeMakingThisClaimPage.pageUrl)
      Then("User validates the 'Charities Management' Page")
      CharitiesManagementAgent.validateNavigationAgent()

    }

    Scenario(
      "User URL hops to 'Corporate trustee address' page whilst being an agent user"
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.loginAgent(HASDIRECT, Agent, "Agent", "HMRC-CHAR-AGENT", "AGENTCHARID", "DATAGUARD-ORGANISATION")
      Then("User navigates to 'Manage charity repayment claims' page and validates navigation")
      CharitiesManagementAgent.validateNavigationAgent()
      And(
        "User clicks the link 'Use the charities online service' to navigate to task list 'Make a charity repayment claim' page"
      )
      CharitiesManagementAgent.clickUseTheCharitiesLink()
      Then("User navigates and validates the 'Repayment claim details' page")
      RepaymentClaimDetailsPage.validateNavigationAgent()
      RepaymentClaimDetailsPage.validateParagraphAgent()
      Then("User URL hops to 'Corporate trustee address' page")
      DoesTheCorporateTrusteeHaveAUKAddressPage.navigateToPage(DoesTheCorporateTrusteeHaveAUKAddressPage.pageUrl)
      Then("User validates the 'Charities Management' Page")
      CharitiesManagementAgent.validateNavigationAgent()

    }
    Scenario(
      "User URL hops to 'Authorised Official Details' page whilst being an agent user"
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.loginAgent(HASDIRECT, Agent, "Agent", "HMRC-CHAR-AGENT", "AGENTCHARID", "DATAGUARD-ORGANISATION")
      Then("User navigates to 'Manage charity repayment claims' page and validates navigation")
      CharitiesManagementAgent.validateNavigationAgent()
      And(
        "User clicks the link 'Use the charities online service' to navigate to task list 'Make a charity repayment claim' page"
      )
      CharitiesManagementAgent.clickUseTheCharitiesLink()
      Then("User navigates and validates the 'Repayment claim details' page")
      RepaymentClaimDetailsPage.validateNavigationAgent()
      RepaymentClaimDetailsPage.validateParagraphAgent()
      Then("User URL hops to 'Authorised Offical Details' page")
      AuthorisedOfficialDetailsPage.navigateToPage(AuthorisedOfficialDetailsPage.pageUrl)
      Then("User validates the 'Charities Management' Page")
      CharitiesManagementAgent.validateNavigationAgent()

    }
    Scenario(
      "User URL hops to 'Corporate trustee details' page whilst being an agent user"
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.loginAgent(HASDIRECT, Agent, "Agent", "HMRC-CHAR-AGENT", "AGENTCHARID", "DATAGUARD-ORGANISATION")
      Then("User navigates to 'Manage charity repayment claims' page and validates navigation")
      CharitiesManagementAgent.validateNavigationAgent()
      And(
        "User clicks the link 'Use the charities online service' to navigate to task list 'Make a charity repayment claim' page"
      )
      CharitiesManagementAgent.clickUseTheCharitiesLink()
      Then("User navigates and validates the 'Repayment claim details' page")
      RepaymentClaimDetailsPage.validateNavigationAgent()
      RepaymentClaimDetailsPage.validateParagraphAgent()
      Then("User URL hops to 'Corporate Trustee Details' page")
      CorporateTrusteeDetailsPage.navigateToPage(CorporateTrusteeDetailsPage.pageUrl)
      Then("User validates the 'Charities Management' Page")
      CharitiesManagementAgent.validateNavigationAgent()

    }

    Scenario(
      "User URL hops to 'Authorised Details' page whilst being an agent user"
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.loginAgent(HASDIRECT, Agent, "Agent", "HMRC-CHAR-AGENT", "AGENTCHARID", "DATAGUARD-ORGANISATION")
      Then("User navigates to 'Manage charity repayment claims' page and validates navigation")
      CharitiesManagementAgent.validateNavigationAgent()
      And(
        "User clicks the link 'Use the charities online service' to navigate to task list 'Make a charity repayment claim' page"
      )
      CharitiesManagementAgent.clickUseTheCharitiesLink()
      Then("User navigates and validates the 'Repayment claim details' page")
      RepaymentClaimDetailsPage.validateNavigationAgent()
      RepaymentClaimDetailsPage.validateParagraphAgent()
      Then("User URL hops to 'Authorised Official Details' page")
      AuthorisedOfficialDetailsPage.navigateToPage(AuthorisedOfficialDetailsPage.pageUrl)
      Then("User validates the 'Charities Management' Page")
      CharitiesManagementAgent.validateNavigationAgent()

    }

    Scenario(
      "User URL hops to 'Delete Repayment Claim' page whilst being an agent user"
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.loginAgent(HASDIRECT, Agent, "Agent", "HMRC-CHAR-AGENT", "AGENTCHARID", "DATAGUARD-ORGANISATION")
      Then("User navigates to 'Manage charity repayment claims' page and validates navigation")
      CharitiesManagementAgent.validateNavigationAgent()
      And(
        "User clicks the link 'Use the charities online service' to navigate to task list 'Make a charity repayment claim' page"
      )
      CharitiesManagementAgent.clickUseTheCharitiesLink()
      Then("User navigates and validates the 'Repayment claim details' page")
      RepaymentClaimDetailsPage.validateNavigationAgent()
      RepaymentClaimDetailsPage.validateParagraphAgent()
      Then("User URL hops to 'Delete Repayment Claim' page")
      DeleteRepaymentClaimPage.navigateToPage(DeleteRepaymentClaimPage.pageUrl)
      Then("User validates the 'Charities Management' Page")
      CharitiesManagementAgent.validateNavigationAgent()

    }

    Scenario(
      "User URL hops to 'Make a charity repayment claim' page whilst being on the 'about repayment' page"
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.loginAgent(HASDIRECT, Agent, "Agent", "HMRC-CHAR-AGENT", "AGENTCHARID", "DATAGUARD-R2")
      Then("User navigates to 'Manage charity repayment claims' page and validates navigation")
      CharitiesManagementAgent.validateNavigationAgent()
      And(
        "User clicks the link 'Use the charities online service' to navigate to task list 'Make a charity repayment claim' page"
      )
      CharitiesManagementAgent.clickUseTheCharitiesLink()
      Then("User navigates and validates the 'Repayment claim details' page")
      RepaymentClaimDetailsPage.validateNavigationAgent()
      RepaymentClaimDetailsPage.validateParagraphAgent()
      Then("User URL hops to 'Claims task list' page")
      ClaimsTaskListPage_InProgress.navigateToPage(ClaimsTaskListPage_InProgress.pageUrl)
      Then("User validates the 'Charities Management' Page")
      CharitiesManagementAgent.validateNavigationAgent()
    }

    Scenario(
      "User URL hops to 'Make a charity repayment claim' page whilst being on the 'HMRC charities ref number' page"
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.loginAgent(HASDIRECT, Agent, "Agent", "HMRC-CHAR-AGENT", "AGENTCHARID", "DATAGUARD-R2")
      Then("User navigates to 'Manage charity repayment claims' page and validates navigation")
      CharitiesManagementAgent.validateNavigationAgent()
      And(
        "User clicks the link 'Use the charities online service' to navigate to task list 'Make a charity repayment claim' page"
      )
      CharitiesManagementAgent.clickUseTheCharitiesLink()
      Then("User navigates and validates the 'Repayment claim details' page")
      RepaymentClaimDetailsPage.validateNavigationAgent()
      RepaymentClaimDetailsPage.validateParagraphAgent()
      RepaymentClaimDetailsPage.clickContinue()
      Then("User navigates to 'HMRC charities ref number' page")
      WhatIsYourHMRCReferenceNumberPage.validateNavigationAgent()
      Then("User URL hops to 'Claims task list' page")
      ClaimsTaskListPage_InProgress.navigateToPage(ClaimsTaskListPage_InProgress.pageUrl)
      Then("User validates the 'Charities Management' Page")
      CharitiesManagementAgent.validateNavigationAgent()
    }

    Scenario(
      "User URL hops to 'Make a charity repayment claim' page whilst being on the 'HMRC charities name' page"
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.loginAgent(HASDIRECT, Agent, "Agent", "HMRC-CHAR-AGENT", "AGENTCHARID", "DATAGUARD-R2")
      Then("User navigates to 'Manage charity repayment claims' page and validates navigation")
      CharitiesManagementAgent.validateNavigationAgent()
      And(
        "User clicks the link 'Use the charities online service' to navigate to task list 'Make a charity repayment claim' page"
      )
      CharitiesManagementAgent.clickUseTheCharitiesLink()
      Then("User navigates and validates the 'Repayment claim details' page")
      RepaymentClaimDetailsPage.validateNavigationAgent()
      RepaymentClaimDetailsPage.validateParagraphAgent()
      RepaymentClaimDetailsPage.clickContinue()
      Then("User navigates to 'HMRC charities ref number' page")
      WhatIsYourHMRCReferenceNumberPage.validateNavigationAgent()
      WhatIsYourHMRCReferenceNumberPage.enterCharitiesReferenceNumber("XF101")
      Then("User navigates to 'HMRC charities name' page")
      WhatIsTheNameOfCharityOrCASC.validateNavigationAgent()
      Then("User URL hops to 'Claims task list' page")
      ClaimsTaskListPage_InProgress.navigateToPage(ClaimsTaskListPage_InProgress.pageUrl)
      Then("User validates the 'Charities Management' Page")
      CharitiesManagementAgent.validateNavigationAgent()
    }

    Scenario(
      "User URL hops to 'Make a charity repayment claim' page whilst being on the 'Repayment claim checkbox' page"
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.loginAgent(HASDIRECT, Agent, "Agent", "HMRC-CHAR-AGENT", "AGENTCHARID", "DATAGUARD-R2")
      Then("User navigates to 'Manage charity repayment claims' page and validates navigation")
      CharitiesManagementAgent.validateNavigationAgent()
      And(
        "User clicks the link 'Use the charities online service' to navigate to task list 'Make a charity repayment claim' page"
      )
      CharitiesManagementAgent.clickUseTheCharitiesLink()
      Then("User navigates and validates the 'Repayment claim details' page")
      RepaymentClaimDetailsPage.validateNavigationAgent()
      RepaymentClaimDetailsPage.validateParagraphAgent()
      RepaymentClaimDetailsPage.clickContinue()
      Then("User navigates to 'HMRC charities ref number' page")
      WhatIsYourHMRCReferenceNumberPage.validateNavigationAgent()
      WhatIsYourHMRCReferenceNumberPage.enterCharitiesReferenceNumber("XF101")
      Then("User navigates to 'HMRC charities name' page")
      WhatIsTheNameOfCharityOrCASC.validateNavigationAgent()
      WhatIsTheNameOfCharityOrCASC.enterCharityName("X1")
      Then("User navigates to 'Repayment claim checkbox' page")
      RepaymentCheckboxPage.validateNavigationAgent()
      Then("User URL hops to 'Claims task list' page")
      ClaimsTaskListPage_InProgress.navigateToPage(ClaimsTaskListPage_InProgress.pageUrl)
      Then("User validates the 'Charities Management' Page")
      CharitiesManagementAgent.validateNavigationAgent()
    }

    Scenario(
      "User URL hops to 'Make a charity repayment claim' page whilst being on the 'GASDS checkbox' page"
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.loginAgent(HASDIRECT, Agent, "Agent", "HMRC-CHAR-AGENT", "AGENTCHARID", "DATAGUARD-R2")
      Then("User navigates to 'Manage charity repayment claims' page and validates navigation")
      CharitiesManagementAgent.validateNavigationAgent()
      And(
        "User clicks the link 'Use the charities online service' to navigate to task list 'Make a charity repayment claim' page"
      )
      CharitiesManagementAgent.clickUseTheCharitiesLink()
      Then("User navigates and validates the 'Repayment claim details' page")
      RepaymentClaimDetailsPage.validateNavigationAgent()
      RepaymentClaimDetailsPage.validateParagraphAgent()
      RepaymentClaimDetailsPage.clickContinue()
      Then("User navigates to 'HMRC charities ref number' page")
      WhatIsYourHMRCReferenceNumberPage.validateNavigationAgent()
      WhatIsYourHMRCReferenceNumberPage.enterCharitiesReferenceNumber("XF101")
      Then("User navigates to 'HMRC charities name' page")
      WhatIsTheNameOfCharityOrCASC.validateNavigationAgent()
      WhatIsTheNameOfCharityOrCASC.enterCharityName("X1")
      Then("User navigates to 'Repayment claim checkbox' page")
      RepaymentCheckboxPage.validateNavigationAgent()
      RepaymentCheckboxPage.checkbox(RepaymentCheckboxPage.GiftAid, true)
      RepaymentCheckboxPage.checkbox(RepaymentCheckboxPage.OtherIncome, true)
      RepaymentCheckboxPage.checkbox(RepaymentCheckboxPage.GASDSclaim, true)
      RepaymentCheckboxPage.clickContinue()
      Then("User navigates to 'GASDS checkbox' page")
      GASDSCheckboxPage.validateNavigationAgent()
      Then("User URL hops to 'Claims task list' page")
      ClaimsTaskListPage_InProgress.navigateToPage(ClaimsTaskListPage_InProgress.pageUrl)
      Then("User validates the 'Charities Management' Page")
      CharitiesManagementAgent.validateNavigationAgent()
    }

    Scenario(
      "User URL hops to 'Make a charity repayment claim' page whilst being on the 'Do you have a reference number' page"
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.loginAgent(HASDIRECT, Agent, "Agent", "HMRC-CHAR-AGENT", "AGENTCHARID", "DATAGUARD-R2")
      Then("User navigates to 'Manage charity repayment claims' page and validates navigation")
      CharitiesManagementAgent.validateNavigationAgent()
      And(
        "User clicks the link 'Use the charities online service' to navigate to task list 'Make a charity repayment claim' page"
      )
      CharitiesManagementAgent.clickUseTheCharitiesLink()
      Then("User navigates and validates the 'Repayment claim details' page")
      RepaymentClaimDetailsPage.validateNavigationAgent()
      RepaymentClaimDetailsPage.validateParagraphAgent()
      RepaymentClaimDetailsPage.clickContinue()
      Then("User navigates to 'HMRC charities ref number' page")
      WhatIsYourHMRCReferenceNumberPage.validateNavigationAgent()
      WhatIsYourHMRCReferenceNumberPage.enterCharitiesReferenceNumber("XF101")
      Then("User navigates to 'HMRC charities name' page")
      WhatIsTheNameOfCharityOrCASC.validateNavigationAgent()
      WhatIsTheNameOfCharityOrCASC.enterCharityName("X1")
      Then("User navigates to 'Repayment claim checkbox' page")
      RepaymentCheckboxPage.validateNavigationAgent()
      RepaymentCheckboxPage.checkbox(RepaymentCheckboxPage.GiftAid, true)
      RepaymentCheckboxPage.checkbox(RepaymentCheckboxPage.OtherIncome, true)
      RepaymentCheckboxPage.checkbox(RepaymentCheckboxPage.GASDSclaim, true)
      RepaymentCheckboxPage.clickContinue()
      Then("User navigates to 'GASDS checkbox' page")
      GASDSCheckboxPage.validateNavigationAgent()
      GASDSCheckboxPage.checkbox(GASDSCheckboxPage.GASDSConnected, true)
      GASDSCheckboxPage.checkbox(GASDSCheckboxPage.GASDSTopUp, true)
      GASDSCheckboxPage.checkbox(GASDSCheckboxPage.GASDSBuilding, true)
      GASDSCheckboxPage.clickContinue()
      Then("User navigates to 'GASDS adjustments' page")
      GiftAidSmallDonationsSchemeClaimPage.validateNavigationAgent()
      Then("User URL hops to 'Claims task list' page")
      ClaimsTaskListPage_InProgress.navigateToPage(ClaimsTaskListPage_InProgress.pageUrl)
      Then("User validates the 'Charities Management' Page")
      CharitiesManagementAgent.validateNavigationAgent()
    }

    Scenario(
      "User URL hops to 'Make a charity repayment claim' page whilst being on the 'Enter reference number' page"
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.loginAgent(HASDIRECT, Agent, "Agent", "HMRC-CHAR-AGENT", "AGENTCHARID", "DATAGUARD-R2")
      Then("User navigates to 'Manage charity repayment claims' page and validates navigation")
      CharitiesManagementAgent.validateNavigationAgent()
      And(
        "User clicks the link 'Use the charities online service' to navigate to task list 'Make a charity repayment claim' page"
      )
      CharitiesManagementAgent.clickUseTheCharitiesLink()
      Then("User navigates and validates the 'Repayment claim details' page")
      RepaymentClaimDetailsPage.validateNavigationAgent()
      RepaymentClaimDetailsPage.validateParagraphAgent()
      RepaymentClaimDetailsPage.clickContinue()
      Then("User navigates to 'HMRC charities ref number' page")
      WhatIsYourHMRCReferenceNumberPage.validateNavigationAgent()
      WhatIsYourHMRCReferenceNumberPage.enterCharitiesReferenceNumber("XF101")
      Then("User navigates to 'HMRC charities name' page")
      WhatIsTheNameOfCharityOrCASC.validateNavigationAgent()
      WhatIsTheNameOfCharityOrCASC.enterCharityName("X1")
      Then("User navigates to 'Repayment claim checkbox' page")
      RepaymentCheckboxPage.validateNavigationAgent()
      RepaymentCheckboxPage.checkbox(RepaymentCheckboxPage.GiftAid, true)
      RepaymentCheckboxPage.checkbox(RepaymentCheckboxPage.OtherIncome, true)
      RepaymentCheckboxPage.checkbox(RepaymentCheckboxPage.GASDSclaim, true)
      RepaymentCheckboxPage.clickContinue()
      Then("User navigates to 'GASDS checkbox' page")
      GASDSCheckboxPage.validateNavigationAgent()
      GASDSCheckboxPage.checkbox(GASDSCheckboxPage.GASDSConnected, true)
      GASDSCheckboxPage.checkbox(GASDSCheckboxPage.GASDSTopUp, true)
      GASDSCheckboxPage.checkbox(GASDSCheckboxPage.GASDSBuilding, true)
      GASDSCheckboxPage.clickContinue()
      Then("User navigates to 'GASDS adjustments' page")
      GiftAidSmallDonationsSchemeClaimPage.validateNavigationAgent()
      GiftAidSmallDonationsSchemeClaimPage.radioButton(GiftAidSmallDonationsSchemeClaimPage.yes)
      GiftAidSmallDonationsSchemeClaimPage.clickContinue()
      Then("User navigates to 'Do you have a claim reference number' page")
      DoYouHaveAClaimReferenceNumberPage.validateNavigationAgent()
      DoYouHaveAClaimReferenceNumberPage.radioButton(DoYouHaveAClaimReferenceNumberPage.yes)
      DoYouHaveAClaimReferenceNumberPage.clickContinue()
      Then("User navigates to 'Enter a claim reference number' page")
      WhatIsYourClaimReferenceNumberPage.validateNavigationAgent()
      Then("User URL hops to 'Claims task list' page")
      ClaimsTaskListPage_InProgress.navigateToPage(ClaimsTaskListPage_InProgress.pageUrl)
      Then("User validates the 'Charities Management' Page")
      CharitiesManagementAgent.validateNavigationAgent()
    }

    Scenario(
      "User URL hops to 'Make a charity repayment claim' page whilst being on the 'About the org CYA' page"
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.loginAgent(HASDIRECT, Agent, "Agent", "HMRC-CHAR-AGENT", "AGENTCHARID", "DATAGUARD-R2")
      Then("User navigates to 'Manage charity repayment claims' page and validates navigation")
      CharitiesManagementAgent.validateNavigationAgent()
      And(
        "User clicks the link 'Use the charities online service' to navigate to task list 'Make a charity repayment claim' page"
      )
      CharitiesManagementAgent.clickUseTheCharitiesLink()
      Then("User navigates and validates the 'Repayment claim details' page")
      RepaymentClaimDetailsPage.validateNavigationAgent()
      RepaymentClaimDetailsPage.validateParagraphAgent()
      RepaymentClaimDetailsPage.clickContinue()
      Then("User navigates to 'HMRC charities ref number' page")
      WhatIsYourHMRCReferenceNumberPage.validateNavigationAgent()
      WhatIsYourHMRCReferenceNumberPage.enterCharitiesReferenceNumber("XF101")
      Then("User navigates to 'HMRC charities name' page")
      WhatIsTheNameOfCharityOrCASC.validateNavigationAgent()
      WhatIsTheNameOfCharityOrCASC.enterCharityName("X1")
      Then("User navigates to 'Repayment claim checkbox' page")
      RepaymentCheckboxPage.validateNavigationAgent()
      RepaymentCheckboxPage.checkbox(RepaymentCheckboxPage.GiftAid, true)
      RepaymentCheckboxPage.checkbox(RepaymentCheckboxPage.OtherIncome, true)
      RepaymentCheckboxPage.checkbox(RepaymentCheckboxPage.GASDSclaim, true)
      RepaymentCheckboxPage.clickContinue()
      Then("User navigates to 'GASDS checkbox' page")
      GASDSCheckboxPage.validateNavigationAgent()
      GASDSCheckboxPage.checkbox(GASDSCheckboxPage.GASDSConnected, true)
      GASDSCheckboxPage.checkbox(GASDSCheckboxPage.GASDSTopUp, true)
      GASDSCheckboxPage.checkbox(GASDSCheckboxPage.GASDSBuilding, true)
      GASDSCheckboxPage.clickContinue()
      Then("User navigates to 'GASDS adjustments' page")
      GiftAidSmallDonationsSchemeClaimPage.validateNavigationAgent()
      GiftAidSmallDonationsSchemeClaimPage.radioButton(GiftAidSmallDonationsSchemeClaimPage.yes)
      GiftAidSmallDonationsSchemeClaimPage.clickContinue()
      Then("User navigates to 'Do you have a claim reference number' page")
      DoYouHaveAClaimReferenceNumberPage.validateNavigationAgent()
      DoYouHaveAClaimReferenceNumberPage.radioButton(DoYouHaveAClaimReferenceNumberPage.yes)
      DoYouHaveAClaimReferenceNumberPage.clickContinue()
      Then("User navigates to 'Enter a claim reference number' page")
      WhatIsYourClaimReferenceNumberPage.validateNavigationAgent()
      WhatIsYourClaimReferenceNumberPage.enterClaimReferenceNumber("123")
      Then("User navigates to 'About the org CYA ' page")
      CheckYourRepaymentClaimPage.validateNavigationAgent()
      Then("User URL hops to 'Claims task list' page")
      ClaimsTaskListPage_InProgress.navigateToPage(ClaimsTaskListPage_InProgress.pageUrl)
      Then("User validates the 'Charities Management' Page")
      CharitiesManagementAgent.validateNavigationAgent()
    }

    Scenario(
      "User URL hops to all 'About' pages whilst not submitting their answer on CYA page"
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.login(HASDIRECT, Organisation, "Organisation", "HMRC-CHAR-ORG", "CHARID", "DATAGUARD-Refresh")
      Then("User validates the navigation to the Charities Management page")
      CharitiesManagementPlaceholder.validateNavigation()
      And(
        "User clicks the link 'Use the charities online service' to navigate to task list 'Make a charity repayment claim' page"
      )
      CharitiesManagementPlaceholder.clickUseTheCharitiesLink()
      Then("User navigates to 'Provide repayment claim details'")
      ClaimsTaskListPage_Empty.validateNavigation()
      ClaimsTaskListPage_Empty.clickProvideRepaymentClaimDetails()
      Then("User navigates and validates the 'Repayment claim details' page")
      RepaymentClaimDetailsPage.validateNavigation()
      RepaymentClaimDetailsPage.validateParagraph()
      RepaymentClaimDetailsPage.clickContinue()
      Then("User navigates to 'Repayment claim checkbox' page")
      RepaymentCheckboxPage.validateNavigation()
      RepaymentCheckboxPage.checkbox(RepaymentCheckboxPage.GiftAid, true)
      RepaymentCheckboxPage.checkbox(RepaymentCheckboxPage.OtherIncome, true)
      RepaymentCheckboxPage.checkbox(RepaymentCheckboxPage.GASDSclaim, true)
      RepaymentCheckboxPage.clickContinue()
      Then("User navigates to 'GASDS checkbox' page")
      GASDSCheckboxPage.validateNavigation()
      GASDSCheckboxPage.checkbox(GASDSCheckboxPage.GASDSConnected, true)
      GASDSCheckboxPage.checkbox(GASDSCheckboxPage.GASDSTopUp, true)
      GASDSCheckboxPage.checkbox(GASDSCheckboxPage.GASDSBuilding, true)
      GASDSCheckboxPage.clickContinue()
      Then("User navigates to 'GASDS adjustments' page")
      GiftAidSmallDonationsSchemeClaimPage.validateNavigation()
      GiftAidSmallDonationsSchemeClaimPage.radioButton(GiftAidSmallDonationsSchemeClaimPage.yes)
      GiftAidSmallDonationsSchemeClaimPage.clickContinue()
      Then("User navigates to 'Do you have a claim reference number' page")
      DoYouHaveAClaimReferenceNumberPage.validateNavigation()
      DoYouHaveAClaimReferenceNumberPage.radioButton(DoYouHaveAClaimReferenceNumberPage.yes)
      DoYouHaveAClaimReferenceNumberPage.clickContinue()
      Then("User navigates to 'Enter a claim reference number' page")
      WhatIsYourClaimReferenceNumberPage.validateNavigation()
      WhatIsYourClaimReferenceNumberPage.enterClaimReferenceNumber("123")
      Then("User navigates to 'About the org CYA ' page")
      CheckYourRepaymentClaimPage.validateNavigation()
      Then("User URL hops to 'About Gift Aid Schedule' page")
      CheckYourRepaymentClaimPage.navigateToPage(AboutGiftAidSchedulePage.pageUrl)
      Then("User validates that the dataguards worked by validating R2 navigation")
      ClaimsTaskListPage_Empty.validateNavigation()
      ClaimsTaskListPage_Empty.clickBackLink()
      Then("User URL hops to 'About Other Income Schedule' and validates the dataguards")
      CheckYourRepaymentClaimPage.navigateToPage(AboutOtherIncomeSchedulePage.pageUrl)
      Then("User validates that the dataguards worked by validating R2 navigation")
      ClaimsTaskListPage_Empty.validateNavigation()
      ClaimsTaskListPage_Empty.clickBackLink()
      Then("User URL hops to 'About Community Building Schedule' and validates the dataguards")
      CheckYourRepaymentClaimPage.navigateToPage(AboutCommunityBuildingsSchedulePage.pageUrl)
      Then("User validates that the dataguards worked by validating R2 navigation")
      ClaimsTaskListPage_Empty.validateNavigation()
      ClaimsTaskListPage_Empty.clickBackLink()
      Then("User URL hops to 'About Connected Charities Schedule' and validates the dataguards")
      CheckYourRepaymentClaimPage.navigateToPage(AboutConnectedCharitiesSchedulePage.pageUrl)
      Then("User validates that the dataguards worked by validating R2 navigation")
      ClaimsTaskListPage_Empty.validateNavigation()
      ClaimsTaskListPage_Empty.clickBackLink()
      Then("User URL hops to 'About GASDS' and validates the dataguards")
      CheckYourRepaymentClaimPage.navigateToPage(AboutGASDSPage.pageUrl)
      Then("User validates that the dataguards worked by validating R2 navigation")
      ClaimsTaskListPage_Empty.validateNavigation()
      ClaimsTaskListPage_Empty.clickBackLink()
    }

    Scenario(
      "User submits claim then URL hops to all pages in the 'Repayment Claim Details' flow to validate data guards"
    ) {
      AuthWizard.login(HASDIRECT, Organisation, "Organisation", "HMRC-CHAR-ORG", "CHARID", "DG101")
      Then("User validates the navigation to the Charities Management page")
      CharitiesManagementPlaceholder.validateNavigation()
      CharitiesManagementPlaceholder.clickUseTheCharitiesLink()
      Then("User navigates to 'Make a charity repayment claim' page")
      ClaimsTaskListPage_Empty.validateNavigation()
      And("User clicks the link to navigate to 'Repayment claim details' page")
      ClaimsTaskListPage_Empty.clickProvideRepaymentClaimDetails()
      Then("User validates the 'Repayment claim details' page")
      RepaymentClaimDetailsPage.validateNavigation()
      And("User clicks continue on 'Repayment claim details' page")
      RepaymentClaimDetailsPage.clickContinue()
      Then("User navigates to 'Which type of repayment claim do you want to make?' page")
      RepaymentCheckboxPage.validateNavigation()
      And("User selects 'Tax Repayments on Gift Aid donations' checkbox and clicks continue")
      RepaymentCheckboxPage.checkbox(RepaymentCheckboxPage.GiftAid, true)
      RepaymentCheckboxPage.clickContinue()
      Then("User navigates to 'Do you have a claim reference number?' page")
      DoYouHaveAClaimReferenceNumberPage.validateNavigation()
      And("User selects 'No' and clicks continue on 'Do you have a claim reference number?' page")
      DoYouHaveAClaimReferenceNumberPage.radioButton(DoYouHaveAClaimReferenceNumberPage.yes)
      DoYouHaveAClaimReferenceNumberPage.clickContinue()
      Then("User enters a valid claim reference number and continues")
      WhatIsYourClaimReferenceNumberPage.enterClaimReferenceNumber("21")
      Then("User navigates to 'Check your repayment claim' page")
      CheckYourRepaymentClaimPage.validateNavigation()
      CheckYourRepaymentClaimPage.clickContinue()
      Then("User navigates to 'Make a charity repayment claim' page")
      ClaimsTaskListPage_InProgress.validateNavigation_AllSubheadings()
      And("User clicks the link to navigate to 'About the organisation' page")
      ClaimsTaskListPage_InProgress.clickProvideOrganisationDetails()
      AboutTheOrganisationPage.validateNavigation()
      Then("User selects continue on 'About the organisation' page")
      AboutTheOrganisationPage.clickContinue()
      And("User navigates to 'What is the name of the charity regulator?' page")
      WhatIsTheNameOfTheCharityRegulatorPage.validateNavigation()
      And("User selects they are not registered with a regulator")
      WhatIsTheNameOfTheCharityRegulatorPage.radioButton(WhatIsTheNameOfTheCharityRegulatorPage.None)
      WhatIsTheNameOfTheCharityRegulatorPage.clickContinue()
      And("User navigates to 'Why is the charity not registered with a regulator?' page")
      WhyIsTheCharityNotRegisteredPage.validateNavigation()
      And("User selects they are excepted")
      WhyIsTheCharityNotRegisteredPage.radioButton(WhyIsTheCharityNotRegisteredPage.Excepted)
      WhyIsTheCharityNotRegisteredPage.clickContinue()
      And("User navigates to 'Your charity is excepted' page")
      YourCharityIsExceptedPage.validateNavigation()
      Then("User selects continue on 'Your charity is excepted' page")
      YourCharityIsExceptedPage.clickContinue()
      And("User navigates to 'Is a corporate trustee making this claim?' page")
      IsACorporateTrusteeMakingThisClaimPage.validateNavigation()
      And("User selects a corporate trustee is making this claim")
      IsACorporateTrusteeMakingThisClaimPage.radioButton(IsACorporateTrusteeMakingThisClaimPage.yes)
      IsACorporateTrusteeMakingThisClaimPage.clickContinue()
      And("User navigates to 'Does the corporate trustee have a UK address?' page")
      DoesTheCorporateTrusteeHaveAUKAddressPage.validateNavigation()
      And("User selects a corporate trustee does not have a UK address")
      DoesTheCorporateTrusteeHaveAUKAddressPage.radioButton(DoesTheCorporateTrusteeHaveAUKAddressPage.no)
      DoesTheCorporateTrusteeHaveAUKAddressPage.clickContinue()
      And("User navigates to 'What are the corporate trustee details?' page")
      CorporateTrusteeDetailsPage.validateNavigation()
      And("User enters their Non UK Trustee details and clicks continue")
      CorporateTrusteeDetailsPage.enterNonUKTrusteeDetails("TEST TRUSTEE", "00-1-332-555-2368")
      And("User navigates to 'Check your organisation details' page")
      CheckYourOrganisationDetailsPage.validateNavigation()
      Then("User navigates to 'Make a charity repayment claim' page")
      CheckYourOrganisationDetailsPage.clickContinue()
      ClaimsTaskListPage_InProgress.validateNavigation_AllSubheadings()
      And("User clicks the link to navigate to 'Add Gift Aid schedule' page")
      ClaimsTaskListPage_InProgress.clickAddGiftAidSchedule()
      Then("User navigates to 'About Gift Aid schedule' page")
      AboutGiftAidSchedulePage.validateNavigation()
      AboutGiftAidSchedulePage.clickContinue()
      Then("User navigates to 'Upload a Gift Aid schedule' page")
      UploadAGiftAidSchedulePage.validateNavigation()
      Then("User selects a file to upload in the 'Upload a Gift Aid schedule' page")
      UploadAGiftAidSchedulePage.selectFile("GiftAidSpreadsheets/Gift-Aid-Schedule-SIMPLEPASS_MAX_ROWS_OVERCLAIMED")
      UploadAGiftAidSchedulePage.clickContinue()
      Then("User navigates to 'Your Gift Aid schedule upload' page")
      YourGiftAidScheduleUploadPage.validateNavigation()
      YourGiftAidScheduleUploadPage.waitForFileUpload()
      YourGiftAidScheduleUploadPage.clickContinue()
      Then("User navigates to 'Check your Gift Aid schedule' page")
      CheckYourGiftAidSchedulePage.validateNavigation()
      CheckYourGiftAidSchedulePage.radioButton(CheckYourGiftAidSchedulePage.no)
      CheckYourGiftAidSchedulePage.clickContinue()
      Then("User navigates to 'Successful Gift Aid Upload' page")
      GiftAidUploadSuccessfulPage.validateNavigation()
      Then("User navigates to 'Make a charity repayment claim' page")
      GiftAidUploadSuccessfulPage.clickContinue()
      ClaimsTaskListPage_InProgress.validateNavigation_AllSubheadings()
      Then("User navigates to 'What adjustments have you made to this claim?' page")
      ClaimsTaskListPage_InProgress.clickReadDeclaration()
      WhatAdjustmentsHaveYouMadeToThisClaimPage.validateNavigation()
      Then("User navigates to 'Declaration' page")
      WhatAdjustmentsHaveYouMadeToThisClaimPage.enterAdjustmentDetails("123")
      DeclarationPage.validateNavigation()
      Then("User navigates to 'Claim complete' page")
      DeclarationPage.clickConfirmAndSubmit()
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to R1.0 and checks to see if the data guard works, user should be taken to D1.3 ")
      ClaimCompletePage.navigateToPage(RepaymentClaimDetailsPage.pageUrl)
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to R1.1 and checks to see if the data guard works, user should be taken to D1.3")
      ClaimCompletePage.navigateToPage(RepaymentCheckboxPage.pageUrl)
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to R1.2 and checks to see if the data guard works, user should be taken to D1.3")
      ClaimCompletePage.navigateToPage(GASDSCheckboxPage.pageUrl)
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to R1.3 and checks to see if the data guard works, user should be taken to D1.3")
      ClaimCompletePage.navigateToPage(GiftAidSmallDonationsSchemeClaimPage.pageUrl)
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to R1.4 and checks to see if the data guard works, user should be taken to D1.3")
      ClaimCompletePage.navigateToPage(GiftAidSmallDonationsSchemeClaimPage.pageUrl)
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to R1.6 and checks to see if the data guard works, user should be taken to D1.3")
      ClaimCompletePage.navigateToPage(DoYouHaveAClaimReferenceNumberPage.pageUrl)
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to R1.7 and checks to see if the data guard works, user should be taken to D1.3")
      ClaimCompletePage.navigateToPage(WhatIsYourClaimReferenceNumberPage.pageUrl)
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to R1.8 and checks to see if the data guard works, user should be taken to D1.3")
      ClaimCompletePage.navigateToPage(CheckYourRepaymentClaimPage.pageUrl)
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to R2 and checks to see if the data guard works, user should be taken to D1.3")
      ClaimCompletePage.navigateToPage(ClaimsTaskListPage_InProgress.pageUrl)
      ClaimCompletePage.validateNavigation()
    }

    Scenario(
      "User submits claim then URL hops to all pages in the 'About The Org' flow to validate data guards"
    ) {
      AuthWizard.login(HASDIRECT, Organisation, "Organisation", "HMRC-CHAR-ORG", "CHARID", "DG101")
      Then("User validates the navigation to the Charities Management page")
      CharitiesManagementPlaceholder.validateNavigation()
      CharitiesManagementPlaceholder.clickUseTheCharitiesLink()
      Then("User navigates to 'Make a charity repayment claim' page")
      ClaimsTaskListPage_Empty.validateNavigation()
      And("User clicks the link to navigate to 'Repayment claim details' page")
      ClaimsTaskListPage_Empty.clickProvideRepaymentClaimDetails()
      Then("User validates the 'Repayment claim details' page")
      RepaymentClaimDetailsPage.validateNavigation()
      And("User clicks continue on 'Repayment claim details' page")
      RepaymentClaimDetailsPage.clickContinue()
      Then("User navigates to 'Which type of repayment claim do you want to make?' page")
      RepaymentCheckboxPage.validateNavigation()
      And("User selects 'Tax Repayments on Gift Aid donations' checkbox and clicks continue")
      RepaymentCheckboxPage.checkbox(RepaymentCheckboxPage.GiftAid, true)
      RepaymentCheckboxPage.clickContinue()
      Then("User navigates to 'Do you have a claim reference number?' page")
      DoYouHaveAClaimReferenceNumberPage.validateNavigation()
      And("User selects 'No' and clicks continue on 'Do you have a claim reference number?' page")
      DoYouHaveAClaimReferenceNumberPage.radioButton(DoYouHaveAClaimReferenceNumberPage.yes)
      DoYouHaveAClaimReferenceNumberPage.clickContinue()
      Then("User enters a valid claim reference number and continues")
      WhatIsYourClaimReferenceNumberPage.enterClaimReferenceNumber("21")
      Then("User navigates to 'Check your repayment claim' page")
      CheckYourRepaymentClaimPage.validateNavigation()
      CheckYourRepaymentClaimPage.clickContinue()
      Then("User navigates to 'Make a charity repayment claim' page")
      ClaimsTaskListPage_InProgress.validateNavigation_AllSubheadings()
      And("User clicks the link to navigate to 'About the organisation' page")
      ClaimsTaskListPage_InProgress.clickProvideOrganisationDetails()
      AboutTheOrganisationPage.validateNavigation()
      Then("User selects continue on 'About the organisation' page")
      AboutTheOrganisationPage.clickContinue()
      And("User navigates to 'What is the name of the charity regulator?' page")
      WhatIsTheNameOfTheCharityRegulatorPage.validateNavigation()
      And("User selects they are not registered with a regulator")
      WhatIsTheNameOfTheCharityRegulatorPage.radioButton(WhatIsTheNameOfTheCharityRegulatorPage.None)
      WhatIsTheNameOfTheCharityRegulatorPage.clickContinue()
      And("User navigates to 'Why is the charity not registered with a regulator?' page")
      WhyIsTheCharityNotRegisteredPage.validateNavigation()
      And("User selects they are excepted")
      WhyIsTheCharityNotRegisteredPage.radioButton(WhyIsTheCharityNotRegisteredPage.Excepted)
      WhyIsTheCharityNotRegisteredPage.clickContinue()
      And("User navigates to 'Your charity is excepted' page")
      YourCharityIsExceptedPage.validateNavigation()
      Then("User selects continue on 'Your charity is excepted' page")
      YourCharityIsExceptedPage.clickContinue()
      And("User navigates to 'Is a corporate trustee making this claim?' page")
      IsACorporateTrusteeMakingThisClaimPage.validateNavigation()
      And("User selects a corporate trustee is making this claim")
      IsACorporateTrusteeMakingThisClaimPage.radioButton(IsACorporateTrusteeMakingThisClaimPage.yes)
      IsACorporateTrusteeMakingThisClaimPage.clickContinue()
      And("User navigates to 'Does the corporate trustee have a UK address?' page")
      DoesTheCorporateTrusteeHaveAUKAddressPage.validateNavigation()
      And("User selects a corporate trustee does not have a UK address")
      DoesTheCorporateTrusteeHaveAUKAddressPage.radioButton(DoesTheCorporateTrusteeHaveAUKAddressPage.no)
      DoesTheCorporateTrusteeHaveAUKAddressPage.clickContinue()
      And("User navigates to 'What are the corporate trustee details?' page")
      CorporateTrusteeDetailsPage.validateNavigation()
      And("User enters their Non UK Trustee details and clicks continue")
      CorporateTrusteeDetailsPage.enterNonUKTrusteeDetails("TEST TRUSTEE", "00-1-332-555-2368")
      And("User navigates to 'Check your organisation details' page")
      CheckYourOrganisationDetailsPage.validateNavigation()
      Then("User navigates to 'Make a charity repayment claim' page")
      CheckYourOrganisationDetailsPage.clickContinue()
      ClaimsTaskListPage_InProgress.validateNavigation_AllSubheadings()
      And("User clicks the link to navigate to 'Add Gift Aid schedule' page")
      ClaimsTaskListPage_InProgress.clickAddGiftAidSchedule()
      Then("User navigates to 'About Gift Aid schedule' page")
      AboutGiftAidSchedulePage.validateNavigation()
      AboutGiftAidSchedulePage.clickContinue()
      Then("User navigates to 'Upload a Gift Aid schedule' page")
      UploadAGiftAidSchedulePage.validateNavigation()
      Then("User selects a file to upload in the 'Upload a Gift Aid schedule' page")
      UploadAGiftAidSchedulePage.selectFile("GiftAidSpreadsheets/Gift-Aid-Schedule-SIMPLEPASS_MAX_ROWS_OVERCLAIMED")
      UploadAGiftAidSchedulePage.clickContinue()
      Then("User navigates to 'Your Gift Aid schedule upload' page")
      YourGiftAidScheduleUploadPage.validateNavigation()
      YourGiftAidScheduleUploadPage.waitForFileUpload()
      YourGiftAidScheduleUploadPage.clickContinue()
      Then("User navigates to 'Check your Gift Aid schedule' page")
      CheckYourGiftAidSchedulePage.validateNavigation()
      CheckYourGiftAidSchedulePage.radioButton(CheckYourGiftAidSchedulePage.no)
      CheckYourGiftAidSchedulePage.clickContinue()
      Then("User navigates to 'Successful Gift Aid Upload' page")
      GiftAidUploadSuccessfulPage.validateNavigation()
      Then("User navigates to 'Make a charity repayment claim' page")
      GiftAidUploadSuccessfulPage.clickContinue()
      ClaimsTaskListPage_InProgress.validateNavigation_AllSubheadings()
      Then("User navigates to 'What adjustments have you made to this claim?' page")
      ClaimsTaskListPage_InProgress.clickReadDeclaration()
      WhatAdjustmentsHaveYouMadeToThisClaimPage.validateNavigation()
      Then("User navigates to 'Declaration' page")
      WhatAdjustmentsHaveYouMadeToThisClaimPage.enterAdjustmentDetails("123")
      DeclarationPage.validateNavigation()
      Then("User navigates to 'Claim complete' page")
      DeclarationPage.clickConfirmAndSubmit()
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to A2.0 and checks to see if the data guard works, user should be taken to D1.3 ")
      ClaimCompletePage.navigateToPage(AboutTheOrganisationPage.pageUrl)
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to A2.1 and checks to see if the data guard works, user should be taken to D1.3")
      ClaimCompletePage.navigateToPage(WhatIsTheNameOfTheCharityRegulatorPage.pageUrl)
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to A2.2 and checks to see if the data guard works, user should be taken to D1.3")
      ClaimCompletePage.navigateToPage(WhyIsTheCharityNotRegisteredPage.pageUrl)
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to A2.3 and checks to see if the data guard works, user should be taken to D1.3")
      ClaimCompletePage.navigateToPage(YourCharityIsExceptedPage.pageUrl)
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to A2.4 and checks to see if the data guard works, user should be taken to D1.3")
      ClaimCompletePage.navigateToPage(YourCharityIsExemptPage.pageUrl)
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to A2.5 and checks to see if the data guard works, user should be taken to D1.3")
      ClaimCompletePage.navigateToPage(WhatIsTheNameOfTheCharityRegulatorPage.pageUrl)
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to A2.6 and checks to see if the data guard works, user should be taken to D1.3")
      ClaimCompletePage.navigateToPage(IsACorporateTrusteeMakingThisClaimPage.pageUrl)
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to A2.7 and checks to see if the data guard works, user should be taken to D1.3")
      ClaimCompletePage.navigateToPage(DoesTheCorporateTrusteeHaveAUKAddressPage.pageUrl)
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to A2.8 and checks to see if the data guard works, user should be taken to D1.3")
      ClaimCompletePage.navigateToPage(AuthorisedOfficialDetailsPage.pageUrl)
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to A2.9 and checks to see if the data guard works, user should be taken to D1.3")
      ClaimCompletePage.navigateToPage(CorporateTrusteeDetailsPage.pageUrl)
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to A2.10 and checks to see if the data guard works, user should be taken to D1.3")
      ClaimCompletePage.navigateToPage(AuthorisedOfficialDetailsPage.pageUrl)
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to A2.11 and checks to see if the data guard works, user should be taken to D1.3")
      ClaimCompletePage.navigateToPage(CheckYourOrganisationDetailsPage.pageUrl)
      ClaimCompletePage.validateNavigation()
    }

    Scenario(
      "User submits claim then URL hops to all pages in the 'Gift Aid Schedule' flow to validate data guards"
    ) {
      AuthWizard.login(HASDIRECT, Organisation, "Organisation", "HMRC-CHAR-ORG", "CHARID", "DG101")
      Then("User validates the navigation to the Charities Management page")
      CharitiesManagementPlaceholder.validateNavigation()
      CharitiesManagementPlaceholder.clickUseTheCharitiesLink()
      Then("User navigates to 'Make a charity repayment claim' page")
      ClaimsTaskListPage_Empty.validateNavigation()
      And("User clicks the link to navigate to 'Repayment claim details' page")
      ClaimsTaskListPage_Empty.clickProvideRepaymentClaimDetails()
      Then("User validates the 'Repayment claim details' page")
      RepaymentClaimDetailsPage.validateNavigation()
      And("User clicks continue on 'Repayment claim details' page")
      RepaymentClaimDetailsPage.clickContinue()
      Then("User navigates to 'Which type of repayment claim do you want to make?' page")
      RepaymentCheckboxPage.validateNavigation()
      And("User selects 'Tax Repayments on Gift Aid donations' checkbox and clicks continue")
      RepaymentCheckboxPage.checkbox(RepaymentCheckboxPage.GiftAid, true)
      RepaymentCheckboxPage.clickContinue()
      Then("User navigates to 'Do you have a claim reference number?' page")
      DoYouHaveAClaimReferenceNumberPage.validateNavigation()
      And("User selects 'No' and clicks continue on 'Do you have a claim reference number?' page")
      DoYouHaveAClaimReferenceNumberPage.radioButton(DoYouHaveAClaimReferenceNumberPage.yes)
      DoYouHaveAClaimReferenceNumberPage.clickContinue()
      Then("User enters a valid claim reference number and continues")
      WhatIsYourClaimReferenceNumberPage.enterClaimReferenceNumber("21")
      Then("User navigates to 'Check your repayment claim' page")
      CheckYourRepaymentClaimPage.validateNavigation()
      CheckYourRepaymentClaimPage.clickContinue()
      Then("User navigates to 'Make a charity repayment claim' page")
      ClaimsTaskListPage_InProgress.validateNavigation_AllSubheadings()
      And("User clicks the link to navigate to 'About the organisation' page")
      ClaimsTaskListPage_InProgress.clickProvideOrganisationDetails()
      AboutTheOrganisationPage.validateNavigation()
      Then("User selects continue on 'About the organisation' page")
      AboutTheOrganisationPage.clickContinue()
      And("User navigates to 'What is the name of the charity regulator?' page")
      WhatIsTheNameOfTheCharityRegulatorPage.validateNavigation()
      And("User selects they are not registered with a regulator")
      WhatIsTheNameOfTheCharityRegulatorPage.radioButton(WhatIsTheNameOfTheCharityRegulatorPage.None)
      WhatIsTheNameOfTheCharityRegulatorPage.clickContinue()
      And("User navigates to 'Why is the charity not registered with a regulator?' page")
      WhyIsTheCharityNotRegisteredPage.validateNavigation()
      And("User selects they are excepted")
      WhyIsTheCharityNotRegisteredPage.radioButton(WhyIsTheCharityNotRegisteredPage.Excepted)
      WhyIsTheCharityNotRegisteredPage.clickContinue()
      And("User navigates to 'Your charity is excepted' page")
      YourCharityIsExceptedPage.validateNavigation()
      Then("User selects continue on 'Your charity is excepted' page")
      YourCharityIsExceptedPage.clickContinue()
      And("User navigates to 'Is a corporate trustee making this claim?' page")
      IsACorporateTrusteeMakingThisClaimPage.validateNavigation()
      And("User selects a corporate trustee is making this claim")
      IsACorporateTrusteeMakingThisClaimPage.radioButton(IsACorporateTrusteeMakingThisClaimPage.yes)
      IsACorporateTrusteeMakingThisClaimPage.clickContinue()
      And("User navigates to 'Does the corporate trustee have a UK address?' page")
      DoesTheCorporateTrusteeHaveAUKAddressPage.validateNavigation()
      And("User selects a corporate trustee does not have a UK address")
      DoesTheCorporateTrusteeHaveAUKAddressPage.radioButton(DoesTheCorporateTrusteeHaveAUKAddressPage.no)
      DoesTheCorporateTrusteeHaveAUKAddressPage.clickContinue()
      And("User navigates to 'What are the corporate trustee details?' page")
      CorporateTrusteeDetailsPage.validateNavigation()
      And("User enters their Non UK Trustee details and clicks continue")
      CorporateTrusteeDetailsPage.enterNonUKTrusteeDetails("TEST TRUSTEE", "00-1-332-555-2368")
      And("User navigates to 'Check your organisation details' page")
      CheckYourOrganisationDetailsPage.validateNavigation()
      Then("User navigates to 'Make a charity repayment claim' page")
      CheckYourOrganisationDetailsPage.clickContinue()
      ClaimsTaskListPage_InProgress.validateNavigation_AllSubheadings()
      And("User clicks the link to navigate to 'Add Gift Aid schedule' page")
      ClaimsTaskListPage_InProgress.clickAddGiftAidSchedule()
      Then("User navigates to 'About Gift Aid schedule' page")
      AboutGiftAidSchedulePage.validateNavigation()
      AboutGiftAidSchedulePage.clickContinue()
      Then("User navigates to 'Upload a Gift Aid schedule' page")
      UploadAGiftAidSchedulePage.validateNavigation()
      Then("User selects a file to upload in the 'Upload a Gift Aid schedule' page")
      UploadAGiftAidSchedulePage.selectFile("GiftAidSpreadsheets/Gift-Aid-Schedule-SIMPLEPASS_MAX_ROWS_OVERCLAIMED")
      UploadAGiftAidSchedulePage.clickContinue()
      Then("User navigates to 'Your Gift Aid schedule upload' page")
      YourGiftAidScheduleUploadPage.validateNavigation()
      YourGiftAidScheduleUploadPage.waitForFileUpload()
      YourGiftAidScheduleUploadPage.clickContinue()
      Then("User navigates to 'Check your Gift Aid schedule' page")
      CheckYourGiftAidSchedulePage.validateNavigation()
      CheckYourGiftAidSchedulePage.radioButton(CheckYourGiftAidSchedulePage.no)
      CheckYourGiftAidSchedulePage.clickContinue()
      Then("User navigates to 'Successful Gift Aid Upload' page")
      GiftAidUploadSuccessfulPage.validateNavigation()
      Then("User navigates to 'Make a charity repayment claim' page")
      GiftAidUploadSuccessfulPage.clickContinue()
      ClaimsTaskListPage_InProgress.validateNavigation_AllSubheadings()
      Then("User navigates to 'What adjustments have you made to this claim?' page")
      ClaimsTaskListPage_InProgress.clickReadDeclaration()
      WhatAdjustmentsHaveYouMadeToThisClaimPage.validateNavigation()
      Then("User navigates to 'Declaration' page")
      WhatAdjustmentsHaveYouMadeToThisClaimPage.enterAdjustmentDetails("123")
      DeclarationPage.validateNavigation()
      Then("User navigates to 'Claim complete' page")
      DeclarationPage.clickConfirmAndSubmit()
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to G1.0 and checks to see if the data guard works, user should be taken to D1.3 ")
      ClaimCompletePage.navigateToPage(AboutGiftAidSchedulePage.pageUrl)
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to G1.1 and checks to see if the data guard works, user should be taken to D1.3")
      ClaimCompletePage.navigateToPage(UploadAGiftAidSchedulePage.pageUrl)
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to G1.2 and checks to see if the data guard works, user should be taken to D1.3")
      ClaimCompletePage.navigateToPage(YourGiftAidScheduleUploadPage.pageUrl)
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to G1.3 and checks to see if the data guard works, user should be taken to D1.3")
      ClaimCompletePage.navigateToPage(CheckYourGiftAidSchedulePage.pageUrl)
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to G1.4 and checks to see if the data guard works, user should be taken to D1.3")
      ClaimCompletePage.navigateToPage(CheckYourGiftAidScheduleErrorPage.pageUrl)
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to G1.5 and checks to see if the data guard works, user should be taken to D1.3")
      ClaimCompletePage.navigateToPage(GiftAidUploadSuccessfulPage.pageUrl)
      ClaimCompletePage.validateNavigation()
    }

    Scenario(
      "User submits claim then URL hops to all pages in the 'Community Building Schedule' flow to validate data guards"
    ) {
      AuthWizard.login(HASDIRECT, Organisation, "Organisation", "HMRC-CHAR-ORG", "CHARID", "DG101")
      Then("User validates the navigation to the Charities Management page")
      CharitiesManagementPlaceholder.validateNavigation()
      CharitiesManagementPlaceholder.clickUseTheCharitiesLink()
      Then("User navigates to 'Make a charity repayment claim' page")
      ClaimsTaskListPage_Empty.validateNavigation()
      And("User clicks the link to navigate to 'Repayment claim details' page")
      ClaimsTaskListPage_Empty.clickProvideRepaymentClaimDetails()
      Then("User validates the 'Repayment claim details' page")
      RepaymentClaimDetailsPage.validateNavigation()
      And("User clicks continue on 'Repayment claim details' page")
      RepaymentClaimDetailsPage.clickContinue()
      Then("User navigates to 'Which type of repayment claim do you want to make?' page")
      RepaymentCheckboxPage.validateNavigation()
      And("User selects 'Tax Repayments on Gift Aid donations' checkbox and clicks continue")
      RepaymentCheckboxPage.checkbox(RepaymentCheckboxPage.GiftAid, true)
      RepaymentCheckboxPage.clickContinue()
      Then("User navigates to 'Do you have a claim reference number?' page")
      DoYouHaveAClaimReferenceNumberPage.validateNavigation()
      And("User selects 'No' and clicks continue on 'Do you have a claim reference number?' page")
      DoYouHaveAClaimReferenceNumberPage.radioButton(DoYouHaveAClaimReferenceNumberPage.yes)
      DoYouHaveAClaimReferenceNumberPage.clickContinue()
      Then("User enters a valid claim reference number and continues")
      WhatIsYourClaimReferenceNumberPage.enterClaimReferenceNumber("21")
      Then("User navigates to 'Check your repayment claim' page")
      CheckYourRepaymentClaimPage.validateNavigation()
      CheckYourRepaymentClaimPage.clickContinue()
      Then("User navigates to 'Make a charity repayment claim' page")
      ClaimsTaskListPage_InProgress.validateNavigation_AllSubheadings()
      And("User clicks the link to navigate to 'About the organisation' page")
      ClaimsTaskListPage_InProgress.clickProvideOrganisationDetails()
      AboutTheOrganisationPage.validateNavigation()
      Then("User selects continue on 'About the organisation' page")
      AboutTheOrganisationPage.clickContinue()
      And("User navigates to 'What is the name of the charity regulator?' page")
      WhatIsTheNameOfTheCharityRegulatorPage.validateNavigation()
      And("User selects they are not registered with a regulator")
      WhatIsTheNameOfTheCharityRegulatorPage.radioButton(WhatIsTheNameOfTheCharityRegulatorPage.None)
      WhatIsTheNameOfTheCharityRegulatorPage.clickContinue()
      And("User navigates to 'Why is the charity not registered with a regulator?' page")
      WhyIsTheCharityNotRegisteredPage.validateNavigation()
      And("User selects they are excepted")
      WhyIsTheCharityNotRegisteredPage.radioButton(WhyIsTheCharityNotRegisteredPage.Excepted)
      WhyIsTheCharityNotRegisteredPage.clickContinue()
      And("User navigates to 'Your charity is excepted' page")
      YourCharityIsExceptedPage.validateNavigation()
      Then("User selects continue on 'Your charity is excepted' page")
      YourCharityIsExceptedPage.clickContinue()
      And("User navigates to 'Is a corporate trustee making this claim?' page")
      IsACorporateTrusteeMakingThisClaimPage.validateNavigation()
      And("User selects a corporate trustee is making this claim")
      IsACorporateTrusteeMakingThisClaimPage.radioButton(IsACorporateTrusteeMakingThisClaimPage.yes)
      IsACorporateTrusteeMakingThisClaimPage.clickContinue()
      And("User navigates to 'Does the corporate trustee have a UK address?' page")
      DoesTheCorporateTrusteeHaveAUKAddressPage.validateNavigation()
      And("User selects a corporate trustee does not have a UK address")
      DoesTheCorporateTrusteeHaveAUKAddressPage.radioButton(DoesTheCorporateTrusteeHaveAUKAddressPage.no)
      DoesTheCorporateTrusteeHaveAUKAddressPage.clickContinue()
      And("User navigates to 'What are the corporate trustee details?' page")
      CorporateTrusteeDetailsPage.validateNavigation()
      And("User enters their Non UK Trustee details and clicks continue")
      CorporateTrusteeDetailsPage.enterNonUKTrusteeDetails("TEST TRUSTEE", "00-1-332-555-2368")
      And("User navigates to 'Check your organisation details' page")
      CheckYourOrganisationDetailsPage.validateNavigation()
      Then("User navigates to 'Make a charity repayment claim' page")
      CheckYourOrganisationDetailsPage.clickContinue()
      ClaimsTaskListPage_InProgress.validateNavigation_AllSubheadings()
      And("User clicks the link to navigate to 'Add Gift Aid schedule' page")
      ClaimsTaskListPage_InProgress.clickAddGiftAidSchedule()
      Then("User navigates to 'About Gift Aid schedule' page")
      AboutGiftAidSchedulePage.validateNavigation()
      AboutGiftAidSchedulePage.clickContinue()
      Then("User navigates to 'Upload a Gift Aid schedule' page")
      UploadAGiftAidSchedulePage.validateNavigation()
      Then("User selects a file to upload in the 'Upload a Gift Aid schedule' page")
      UploadAGiftAidSchedulePage.selectFile("GiftAidSpreadsheets/Gift-Aid-Schedule-SIMPLEPASS_MAX_ROWS_OVERCLAIMED")
      UploadAGiftAidSchedulePage.clickContinue()
      Then("User navigates to 'Your Gift Aid schedule upload' page")
      YourGiftAidScheduleUploadPage.validateNavigation()
      YourGiftAidScheduleUploadPage.waitForFileUpload()
      YourGiftAidScheduleUploadPage.clickContinue()
      Then("User navigates to 'Check your Gift Aid schedule' page")
      CheckYourGiftAidSchedulePage.validateNavigation()
      CheckYourGiftAidSchedulePage.radioButton(CheckYourGiftAidSchedulePage.no)
      CheckYourGiftAidSchedulePage.clickContinue()
      Then("User navigates to 'Successful Gift Aid Upload' page")
      GiftAidUploadSuccessfulPage.validateNavigation()
      Then("User navigates to 'Make a charity repayment claim' page")
      GiftAidUploadSuccessfulPage.clickContinue()
      ClaimsTaskListPage_InProgress.validateNavigation_AllSubheadings()
      Then("User navigates to 'What adjustments have you made to this claim?' page")
      ClaimsTaskListPage_InProgress.clickReadDeclaration()
      WhatAdjustmentsHaveYouMadeToThisClaimPage.validateNavigation()
      Then("User navigates to 'Declaration' page")
      WhatAdjustmentsHaveYouMadeToThisClaimPage.enterAdjustmentDetails("123")
      DeclarationPage.validateNavigation()
      Then("User navigates to 'Claim complete' page")
      DeclarationPage.clickConfirmAndSubmit()
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to CB1.0 and checks to see if the data guard works, user should be taken to D1.3 ")
      ClaimCompletePage.navigateToPage(AboutCommunityBuildingsSchedulePage.pageUrl)
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to CB1.1 and checks to see if the data guard works, user should be taken to D1.3")
      ClaimCompletePage.navigateToPage(UploadACommunityBuildingsSchedulePage.pageUrl)
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to CB1.2 and checks to see if the data guard works, user should be taken to D1.3")
      ClaimCompletePage.navigateToPage(YourCommunityBuildingsScheduleUploadPage.pageUrl)
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to CB1.3 and checks to see if the data guard works, user should be taken to D1.3")
      ClaimCompletePage.navigateToPage(CheckYourCommunityBuildingsSchedulePage.pageUrl)
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to CB1.4 and checks to see if the data guard works, user should be taken to D1.3")
      ClaimCompletePage.navigateToPage(CheckYourCommunityBuildingsScheduleErrorPage.pageUrl)
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to CB1.5 and checks to see if the data guard works, user should be taken to D1.3")
      ClaimCompletePage.navigateToPage(CommunityBuildingsScheduleUploadSuccessfulPage.pageUrl)
      ClaimCompletePage.validateNavigation()
    }

    Scenario(
      "User submits claim then URL hops to all pages in the 'Other Income Schedule' flow to validate data guards"
    ) {
      AuthWizard.login(HASDIRECT, Organisation, "Organisation", "HMRC-CHAR-ORG", "CHARID", "DG101")
      Then("User validates the navigation to the Charities Management page")
      CharitiesManagementPlaceholder.validateNavigation()
      CharitiesManagementPlaceholder.clickUseTheCharitiesLink()
      Then("User navigates to 'Make a charity repayment claim' page")
      ClaimsTaskListPage_Empty.validateNavigation()
      And("User clicks the link to navigate to 'Repayment claim details' page")
      ClaimsTaskListPage_Empty.clickProvideRepaymentClaimDetails()
      Then("User validates the 'Repayment claim details' page")
      RepaymentClaimDetailsPage.validateNavigation()
      And("User clicks continue on 'Repayment claim details' page")
      RepaymentClaimDetailsPage.clickContinue()
      Then("User navigates to 'Which type of repayment claim do you want to make?' page")
      RepaymentCheckboxPage.validateNavigation()
      And("User selects 'Tax Repayments on Gift Aid donations' checkbox and clicks continue")
      RepaymentCheckboxPage.checkbox(RepaymentCheckboxPage.GiftAid, true)
      RepaymentCheckboxPage.clickContinue()
      Then("User navigates to 'Do you have a claim reference number?' page")
      DoYouHaveAClaimReferenceNumberPage.validateNavigation()
      And("User selects 'No' and clicks continue on 'Do you have a claim reference number?' page")
      DoYouHaveAClaimReferenceNumberPage.radioButton(DoYouHaveAClaimReferenceNumberPage.yes)
      DoYouHaveAClaimReferenceNumberPage.clickContinue()
      Then("User enters a valid claim reference number and continues")
      WhatIsYourClaimReferenceNumberPage.enterClaimReferenceNumber("21")
      Then("User navigates to 'Check your repayment claim' page")
      CheckYourRepaymentClaimPage.validateNavigation()
      CheckYourRepaymentClaimPage.clickContinue()
      Then("User navigates to 'Make a charity repayment claim' page")
      ClaimsTaskListPage_InProgress.validateNavigation_AllSubheadings()
      And("User clicks the link to navigate to 'About the organisation' page")
      ClaimsTaskListPage_InProgress.clickProvideOrganisationDetails()
      AboutTheOrganisationPage.validateNavigation()
      Then("User selects continue on 'About the organisation' page")
      AboutTheOrganisationPage.clickContinue()
      And("User navigates to 'What is the name of the charity regulator?' page")
      WhatIsTheNameOfTheCharityRegulatorPage.validateNavigation()
      And("User selects they are not registered with a regulator")
      WhatIsTheNameOfTheCharityRegulatorPage.radioButton(WhatIsTheNameOfTheCharityRegulatorPage.None)
      WhatIsTheNameOfTheCharityRegulatorPage.clickContinue()
      And("User navigates to 'Why is the charity not registered with a regulator?' page")
      WhyIsTheCharityNotRegisteredPage.validateNavigation()
      And("User selects they are excepted")
      WhyIsTheCharityNotRegisteredPage.radioButton(WhyIsTheCharityNotRegisteredPage.Excepted)
      WhyIsTheCharityNotRegisteredPage.clickContinue()
      And("User navigates to 'Your charity is excepted' page")
      YourCharityIsExceptedPage.validateNavigation()
      Then("User selects continue on 'Your charity is excepted' page")
      YourCharityIsExceptedPage.clickContinue()
      And("User navigates to 'Is a corporate trustee making this claim?' page")
      IsACorporateTrusteeMakingThisClaimPage.validateNavigation()
      And("User selects a corporate trustee is making this claim")
      IsACorporateTrusteeMakingThisClaimPage.radioButton(IsACorporateTrusteeMakingThisClaimPage.yes)
      IsACorporateTrusteeMakingThisClaimPage.clickContinue()
      And("User navigates to 'Does the corporate trustee have a UK address?' page")
      DoesTheCorporateTrusteeHaveAUKAddressPage.validateNavigation()
      And("User selects a corporate trustee does not have a UK address")
      DoesTheCorporateTrusteeHaveAUKAddressPage.radioButton(DoesTheCorporateTrusteeHaveAUKAddressPage.no)
      DoesTheCorporateTrusteeHaveAUKAddressPage.clickContinue()
      And("User navigates to 'What are the corporate trustee details?' page")
      CorporateTrusteeDetailsPage.validateNavigation()
      And("User enters their Non UK Trustee details and clicks continue")
      CorporateTrusteeDetailsPage.enterNonUKTrusteeDetails("TEST TRUSTEE", "00-1-332-555-2368")
      And("User navigates to 'Check your organisation details' page")
      CheckYourOrganisationDetailsPage.validateNavigation()
      Then("User navigates to 'Make a charity repayment claim' page")
      CheckYourOrganisationDetailsPage.clickContinue()
      ClaimsTaskListPage_InProgress.validateNavigation_AllSubheadings()
      And("User clicks the link to navigate to 'Add Gift Aid schedule' page")
      ClaimsTaskListPage_InProgress.clickAddGiftAidSchedule()
      Then("User navigates to 'About Gift Aid schedule' page")
      AboutGiftAidSchedulePage.validateNavigation()
      AboutGiftAidSchedulePage.clickContinue()
      Then("User navigates to 'Upload a Gift Aid schedule' page")
      UploadAGiftAidSchedulePage.validateNavigation()
      Then("User selects a file to upload in the 'Upload a Gift Aid schedule' page")
      UploadAGiftAidSchedulePage.selectFile("GiftAidSpreadsheets/Gift-Aid-Schedule-SIMPLEPASS_MAX_ROWS_OVERCLAIMED")
      UploadAGiftAidSchedulePage.clickContinue()
      Then("User navigates to 'Your Gift Aid schedule upload' page")
      YourGiftAidScheduleUploadPage.validateNavigation()
      YourGiftAidScheduleUploadPage.waitForFileUpload()
      YourGiftAidScheduleUploadPage.clickContinue()
      Then("User navigates to 'Check your Gift Aid schedule' page")
      CheckYourGiftAidSchedulePage.validateNavigation()
      CheckYourGiftAidSchedulePage.radioButton(CheckYourGiftAidSchedulePage.no)
      CheckYourGiftAidSchedulePage.clickContinue()
      Then("User navigates to 'Successful Gift Aid Upload' page")
      GiftAidUploadSuccessfulPage.validateNavigation()
      Then("User navigates to 'Make a charity repayment claim' page")
      GiftAidUploadSuccessfulPage.clickContinue()
      ClaimsTaskListPage_InProgress.validateNavigation_AllSubheadings()
      Then("User navigates to 'What adjustments have you made to this claim?' page")
      ClaimsTaskListPage_InProgress.clickReadDeclaration()
      WhatAdjustmentsHaveYouMadeToThisClaimPage.validateNavigation()
      Then("User navigates to 'Declaration' page")
      WhatAdjustmentsHaveYouMadeToThisClaimPage.enterAdjustmentDetails("123")
      DeclarationPage.validateNavigation()
      Then("User navigates to 'Claim complete' page")
      DeclarationPage.clickConfirmAndSubmit()
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to OI1.0 and checks to see if the data guard works, user should be taken to D1.3 ")
      ClaimCompletePage.navigateToPage(AboutOtherIncomeSchedulePage.pageUrl)
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to OI1.1 and checks to see if the data guard works, user should be taken to D1.3")
      ClaimCompletePage.navigateToPage(UploadAnOtherIncomeSchedulePage.pageUrl)
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to OI1.2 and checks to see if the data guard works, user should be taken to D1.3")
      ClaimCompletePage.navigateToPage(YourOtherIncomeScheduleUploadPage.pageUrl)
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to OI1.3 and checks to see if the data guard works, user should be taken to D1.3")
      ClaimCompletePage.navigateToPage(CheckYourOtherIncomeSchedulePage.pageUrl)
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to OI1.4 and checks to see if the data guard works, user should be taken to D1.3")
      ClaimCompletePage.navigateToPage(CheckYourOtherIncomeScheduleErrorPage.pageUrl)
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to OI1.5 and checks to see if the data guard works, user should be taken to D1.3")
      ClaimCompletePage.navigateToPage(OtherIncomeUploadSuccessfulPage.pageUrl)
      ClaimCompletePage.validateNavigation()
    }

    Scenario(
      "User submits claim then URL hops to all pages in the 'Connected Charities Schedule' flow to validate data guards"
    ) {
      AuthWizard.login(HASDIRECT, Organisation, "Organisation", "HMRC-CHAR-ORG", "CHARID", "DG101")
      Then("User validates the navigation to the Charities Management page")
      CharitiesManagementPlaceholder.validateNavigation()
      CharitiesManagementPlaceholder.clickUseTheCharitiesLink()
      Then("User navigates to 'Make a charity repayment claim' page")
      ClaimsTaskListPage_Empty.validateNavigation()
      And("User clicks the link to navigate to 'Repayment claim details' page")
      ClaimsTaskListPage_Empty.clickProvideRepaymentClaimDetails()
      Then("User validates the 'Repayment claim details' page")
      RepaymentClaimDetailsPage.validateNavigation()
      And("User clicks continue on 'Repayment claim details' page")
      RepaymentClaimDetailsPage.clickContinue()
      Then("User navigates to 'Which type of repayment claim do you want to make?' page")
      RepaymentCheckboxPage.validateNavigation()
      And("User selects 'Tax Repayments on Gift Aid donations' checkbox and clicks continue")
      RepaymentCheckboxPage.checkbox(RepaymentCheckboxPage.GiftAid, true)
      RepaymentCheckboxPage.clickContinue()
      Then("User navigates to 'Do you have a claim reference number?' page")
      DoYouHaveAClaimReferenceNumberPage.validateNavigation()
      And("User selects 'No' and clicks continue on 'Do you have a claim reference number?' page")
      DoYouHaveAClaimReferenceNumberPage.radioButton(DoYouHaveAClaimReferenceNumberPage.yes)
      DoYouHaveAClaimReferenceNumberPage.clickContinue()
      Then("User enters a valid claim reference number and continues")
      WhatIsYourClaimReferenceNumberPage.enterClaimReferenceNumber("21")
      Then("User navigates to 'Check your repayment claim' page")
      CheckYourRepaymentClaimPage.validateNavigation()
      CheckYourRepaymentClaimPage.clickContinue()
      Then("User navigates to 'Make a charity repayment claim' page")
      ClaimsTaskListPage_InProgress.validateNavigation_AllSubheadings()
      And("User clicks the link to navigate to 'About the organisation' page")
      ClaimsTaskListPage_InProgress.clickProvideOrganisationDetails()
      AboutTheOrganisationPage.validateNavigation()
      Then("User selects continue on 'About the organisation' page")
      AboutTheOrganisationPage.clickContinue()
      And("User navigates to 'What is the name of the charity regulator?' page")
      WhatIsTheNameOfTheCharityRegulatorPage.validateNavigation()
      And("User selects they are not registered with a regulator")
      WhatIsTheNameOfTheCharityRegulatorPage.radioButton(WhatIsTheNameOfTheCharityRegulatorPage.None)
      WhatIsTheNameOfTheCharityRegulatorPage.clickContinue()
      And("User navigates to 'Why is the charity not registered with a regulator?' page")
      WhyIsTheCharityNotRegisteredPage.validateNavigation()
      And("User selects they are excepted")
      WhyIsTheCharityNotRegisteredPage.radioButton(WhyIsTheCharityNotRegisteredPage.Excepted)
      WhyIsTheCharityNotRegisteredPage.clickContinue()
      And("User navigates to 'Your charity is excepted' page")
      YourCharityIsExceptedPage.validateNavigation()
      Then("User selects continue on 'Your charity is excepted' page")
      YourCharityIsExceptedPage.clickContinue()
      And("User navigates to 'Is a corporate trustee making this claim?' page")
      IsACorporateTrusteeMakingThisClaimPage.validateNavigation()
      And("User selects a corporate trustee is making this claim")
      IsACorporateTrusteeMakingThisClaimPage.radioButton(IsACorporateTrusteeMakingThisClaimPage.yes)
      IsACorporateTrusteeMakingThisClaimPage.clickContinue()
      And("User navigates to 'Does the corporate trustee have a UK address?' page")
      DoesTheCorporateTrusteeHaveAUKAddressPage.validateNavigation()
      And("User selects a corporate trustee does not have a UK address")
      DoesTheCorporateTrusteeHaveAUKAddressPage.radioButton(DoesTheCorporateTrusteeHaveAUKAddressPage.no)
      DoesTheCorporateTrusteeHaveAUKAddressPage.clickContinue()
      And("User navigates to 'What are the corporate trustee details?' page")
      CorporateTrusteeDetailsPage.validateNavigation()
      And("User enters their Non UK Trustee details and clicks continue")
      CorporateTrusteeDetailsPage.enterNonUKTrusteeDetails("TEST TRUSTEE", "00-1-332-555-2368")
      And("User navigates to 'Check your organisation details' page")
      CheckYourOrganisationDetailsPage.validateNavigation()
      Then("User navigates to 'Make a charity repayment claim' page")
      CheckYourOrganisationDetailsPage.clickContinue()
      ClaimsTaskListPage_InProgress.validateNavigation_AllSubheadings()
      And("User clicks the link to navigate to 'Add Gift Aid schedule' page")
      ClaimsTaskListPage_InProgress.clickAddGiftAidSchedule()
      Then("User navigates to 'About Gift Aid schedule' page")
      AboutGiftAidSchedulePage.validateNavigation()
      AboutGiftAidSchedulePage.clickContinue()
      Then("User navigates to 'Upload a Gift Aid schedule' page")
      UploadAGiftAidSchedulePage.validateNavigation()
      Then("User selects a file to upload in the 'Upload a Gift Aid schedule' page")
      UploadAGiftAidSchedulePage.selectFile("GiftAidSpreadsheets/Gift-Aid-Schedule-SIMPLEPASS_MAX_ROWS_OVERCLAIMED")
      UploadAGiftAidSchedulePage.clickContinue()
      Then("User navigates to 'Your Gift Aid schedule upload' page")
      YourGiftAidScheduleUploadPage.validateNavigation()
      YourGiftAidScheduleUploadPage.waitForFileUpload()
      YourGiftAidScheduleUploadPage.clickContinue()
      Then("User navigates to 'Check your Gift Aid schedule' page")
      CheckYourGiftAidSchedulePage.validateNavigation()
      CheckYourGiftAidSchedulePage.radioButton(CheckYourGiftAidSchedulePage.no)
      CheckYourGiftAidSchedulePage.clickContinue()
      Then("User navigates to 'Successful Gift Aid Upload' page")
      GiftAidUploadSuccessfulPage.validateNavigation()
      Then("User navigates to 'Make a charity repayment claim' page")
      GiftAidUploadSuccessfulPage.clickContinue()
      ClaimsTaskListPage_InProgress.validateNavigation_AllSubheadings()
      Then("User navigates to 'What adjustments have you made to this claim?' page")
      ClaimsTaskListPage_InProgress.clickReadDeclaration()
      WhatAdjustmentsHaveYouMadeToThisClaimPage.validateNavigation()
      Then("User navigates to 'Declaration' page")
      WhatAdjustmentsHaveYouMadeToThisClaimPage.enterAdjustmentDetails("123")
      DeclarationPage.validateNavigation()
      Then("User navigates to 'Claim complete' page")
      DeclarationPage.clickConfirmAndSubmit()
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to CC1.0 and checks to see if the data guard works, user should be taken to D1.3 ")
      ClaimCompletePage.navigateToPage(AboutConnectedCharitiesSchedulePage.pageUrl)
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to CC1.1 and checks to see if the data guard works, user should be taken to D1.3")
      ClaimCompletePage.navigateToPage(UploadAConnectedCharitiesSchedulePage.pageUrl)
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to CC1.2 and checks to see if the data guard works, user should be taken to D1.3")
      ClaimCompletePage.navigateToPage(YourConnectedCharitiesScheduleUploadPage.pageUrl)
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to CC1.3 and checks to see if the data guard works, user should be taken to D1.3")
      ClaimCompletePage.navigateToPage(CheckYourConnectedCharitiesSchedulePage.pageUrl)
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to CC1.4 and checks to see if the data guard works, user should be taken to D1.3")
      ClaimCompletePage.navigateToPage(CheckYourConnectedCharitiesScheduleErrorPage.pageUrl)
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to CC1.5 and checks to see if the data guard works, user should be taken to D1.3")
      ClaimCompletePage.navigateToPage(ConnectedCharitiesUploadSuccessfulPage.pageUrl)
      ClaimCompletePage.validateNavigation()
    }

    Scenario(
      "User submits claim then URL hops to all pages in the 'GASDS' flow to validate data guards"
    ) {
      AuthWizard.login(HASDIRECT, Organisation, "Organisation", "HMRC-CHAR-ORG", "CHARID", "DG101")
      Then("User validates the navigation to the Charities Management page")
      CharitiesManagementPlaceholder.validateNavigation()
      CharitiesManagementPlaceholder.clickUseTheCharitiesLink()
      Then("User navigates to 'Make a charity repayment claim' page")
      ClaimsTaskListPage_Empty.validateNavigation()
      And("User clicks the link to navigate to 'Repayment claim details' page")
      ClaimsTaskListPage_Empty.clickProvideRepaymentClaimDetails()
      Then("User validates the 'Repayment claim details' page")
      RepaymentClaimDetailsPage.validateNavigation()
      And("User clicks continue on 'Repayment claim details' page")
      RepaymentClaimDetailsPage.clickContinue()
      Then("User navigates to 'Which type of repayment claim do you want to make?' page")
      RepaymentCheckboxPage.validateNavigation()
      And("User selects 'Tax Repayments on Gift Aid donations' checkbox and clicks continue")
      RepaymentCheckboxPage.checkbox(RepaymentCheckboxPage.GiftAid, true)
      RepaymentCheckboxPage.clickContinue()
      Then("User navigates to 'Do you have a claim reference number?' page")
      DoYouHaveAClaimReferenceNumberPage.validateNavigation()
      And("User selects 'No' and clicks continue on 'Do you have a claim reference number?' page")
      DoYouHaveAClaimReferenceNumberPage.radioButton(DoYouHaveAClaimReferenceNumberPage.yes)
      DoYouHaveAClaimReferenceNumberPage.clickContinue()
      Then("User enters a valid claim reference number and continues")
      WhatIsYourClaimReferenceNumberPage.enterClaimReferenceNumber("21")
      Then("User navigates to 'Check your repayment claim' page")
      CheckYourRepaymentClaimPage.validateNavigation()
      CheckYourRepaymentClaimPage.clickContinue()
      Then("User navigates to 'Make a charity repayment claim' page")
      ClaimsTaskListPage_InProgress.validateNavigation_AllSubheadings()
      And("User clicks the link to navigate to 'About the organisation' page")
      ClaimsTaskListPage_InProgress.clickProvideOrganisationDetails()
      AboutTheOrganisationPage.validateNavigation()
      Then("User selects continue on 'About the organisation' page")
      AboutTheOrganisationPage.clickContinue()
      And("User navigates to 'What is the name of the charity regulator?' page")
      WhatIsTheNameOfTheCharityRegulatorPage.validateNavigation()
      And("User selects they are not registered with a regulator")
      WhatIsTheNameOfTheCharityRegulatorPage.radioButton(WhatIsTheNameOfTheCharityRegulatorPage.None)
      WhatIsTheNameOfTheCharityRegulatorPage.clickContinue()
      And("User navigates to 'Why is the charity not registered with a regulator?' page")
      WhyIsTheCharityNotRegisteredPage.validateNavigation()
      And("User selects they are excepted")
      WhyIsTheCharityNotRegisteredPage.radioButton(WhyIsTheCharityNotRegisteredPage.Excepted)
      WhyIsTheCharityNotRegisteredPage.clickContinue()
      And("User navigates to 'Your charity is excepted' page")
      YourCharityIsExceptedPage.validateNavigation()
      Then("User selects continue on 'Your charity is excepted' page")
      YourCharityIsExceptedPage.clickContinue()
      And("User navigates to 'Is a corporate trustee making this claim?' page")
      IsACorporateTrusteeMakingThisClaimPage.validateNavigation()
      And("User selects a corporate trustee is making this claim")
      IsACorporateTrusteeMakingThisClaimPage.radioButton(IsACorporateTrusteeMakingThisClaimPage.yes)
      IsACorporateTrusteeMakingThisClaimPage.clickContinue()
      And("User navigates to 'Does the corporate trustee have a UK address?' page")
      DoesTheCorporateTrusteeHaveAUKAddressPage.validateNavigation()
      And("User selects a corporate trustee does not have a UK address")
      DoesTheCorporateTrusteeHaveAUKAddressPage.radioButton(DoesTheCorporateTrusteeHaveAUKAddressPage.no)
      DoesTheCorporateTrusteeHaveAUKAddressPage.clickContinue()
      And("User navigates to 'What are the corporate trustee details?' page")
      CorporateTrusteeDetailsPage.validateNavigation()
      And("User enters their Non UK Trustee details and clicks continue")
      CorporateTrusteeDetailsPage.enterNonUKTrusteeDetails("TEST TRUSTEE", "00-1-332-555-2368")
      And("User navigates to 'Check your organisation details' page")
      CheckYourOrganisationDetailsPage.validateNavigation()
      Then("User navigates to 'Make a charity repayment claim' page")
      CheckYourOrganisationDetailsPage.clickContinue()
      ClaimsTaskListPage_InProgress.validateNavigation_AllSubheadings()
      And("User clicks the link to navigate to 'Add Gift Aid schedule' page")
      ClaimsTaskListPage_InProgress.clickAddGiftAidSchedule()
      Then("User navigates to 'About Gift Aid schedule' page")
      AboutGiftAidSchedulePage.validateNavigation()
      AboutGiftAidSchedulePage.clickContinue()
      Then("User navigates to 'Upload a Gift Aid schedule' page")
      UploadAGiftAidSchedulePage.validateNavigation()
      Then("User selects a file to upload in the 'Upload a Gift Aid schedule' page")
      UploadAGiftAidSchedulePage.selectFile("GiftAidSpreadsheets/Gift-Aid-Schedule-SIMPLEPASS_MAX_ROWS_OVERCLAIMED")
      UploadAGiftAidSchedulePage.clickContinue()
      Then("User navigates to 'Your Gift Aid schedule upload' page")
      YourGiftAidScheduleUploadPage.validateNavigation()
      YourGiftAidScheduleUploadPage.waitForFileUpload()
      YourGiftAidScheduleUploadPage.clickContinue()
      Then("User navigates to 'Check your Gift Aid schedule' page")
      CheckYourGiftAidSchedulePage.validateNavigation()
      CheckYourGiftAidSchedulePage.radioButton(CheckYourGiftAidSchedulePage.no)
      CheckYourGiftAidSchedulePage.clickContinue()
      Then("User navigates to 'Successful Gift Aid Upload' page")
      GiftAidUploadSuccessfulPage.validateNavigation()
      Then("User navigates to 'Make a charity repayment claim' page")
      GiftAidUploadSuccessfulPage.clickContinue()
      ClaimsTaskListPage_InProgress.validateNavigation_AllSubheadings()
      Then("User navigates to 'What adjustments have you made to this claim?' page")
      ClaimsTaskListPage_InProgress.clickReadDeclaration()
      WhatAdjustmentsHaveYouMadeToThisClaimPage.validateNavigation()
      Then("User navigates to 'Declaration' page")
      WhatAdjustmentsHaveYouMadeToThisClaimPage.enterAdjustmentDetails("123")
      DeclarationPage.validateNavigation()
      Then("User navigates to 'Claim complete' page")
      DeclarationPage.clickConfirmAndSubmit()
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to S2.1 and checks to see if the data guard works, user should be taken to D1.3 ")
      ClaimCompletePage.navigateToPage(AboutGASDSPage.pageUrl)
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to S2.2 and checks to see if the data guard works, user should be taken to D1.3")
      ClaimCompletePage.navigateToPage(WhatIsTheAdjustmentAmountForGiftAidPreviouslyOverclaimedPage.pageUrl)
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to S2.3 and checks to see if the data guard works, user should be taken to D1.3")
      ClaimCompletePage.navigateToPage(CheckYourGASDSAdjustmentAmountPage.pageUrl)
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to S2.4/S2.8/S2.12 and checks to see if the data guard works, user should be taken to D1.3")
      ClaimCompletePage.navigateToPage(WhichTaxYearAreYouClaimingForPage.pageUrl + "/1")
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to S2.5/S2.9/S2.13 and checks to see if the data guard works, user should be taken to D1.3")
      ClaimCompletePage.navigateToPage(WhatDonationAmountAreYouClaimingUnderGASDSPage.pageUrl + "/1")
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to S2.6/S2.10/S2.14 and checks to see if the data guard works, user should be taken to D1.3")
      ClaimCompletePage.navigateToPage(CheckYourClaimDetailsForTaxYearPage.pageUrl + "/1")
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to S2.7/S2.11/S2.15 and checks to see if the data guard works, user should be taken to D1.3")
      ClaimCompletePage.navigateToPage(YouHaveAddedAClaimForXTaxYearPage.pageUrl)
      ClaimCompletePage.validateNavigation()
      Then("User URL hops to S2.16 and checks to see if the data guard works, user should be taken to D1.3")
      ClaimCompletePage.navigateToPage(CheckYourGASDSDonationDetailsPage.pageUrl)
      ClaimCompletePage.validateNavigation()
    }

  }
}
