/*
 * Copyright 2026 HM Revenue & Customs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package uk.gov.hmrc.ui.specs

import org.scalatest.featurespec.AnyFeatureSpec
import org.scalatest.verbs.ShouldVerb
import org.scalatest.{BeforeAndAfterAll, BeforeAndAfterEach, GivenWhenThen}
import uk.gov.hmrc.selenium.webdriver.{Browser, ScreenshotOnFailure}
import uk.gov.hmrc.ui.pages.*
import uk.gov.hmrc.ui.util.Users.LoginTypes.HASDIRECT
import uk.gov.hmrc.ui.util.Users.UserTypes.Organisation

class OrgE2EJourneySpec
    extends AnyFeatureSpec
    with BaseSpec
    with GivenWhenThen
    with ShouldVerb
    with BeforeAndAfterAll
    with BeforeAndAfterEach
    with Browser
    with ScreenshotOnFailure {

  Feature("Charities - Organisation - E2E journeys") {
    Scenario(
      "User navigates through a full Org user journey - No Regulator - Trustee - UK Address - All ODS - Submit"
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.login(HASDIRECT, Organisation, "Organisation", "HMRC-CHAR-ORG", "CHARID", "IT00071")
      Then("User navigates to 'Manage charity repayment claims' page and validates navigation")
      CharitiesManagementPlaceholder.validateNavigation()
      And(
        "User clicks the link 'Use the charities online service' to navigate to task list 'Make a charity repayment claim' page"
      )
      CharitiesManagementPlaceholder.clickUseTheCharitiesLink()
      Then("User navigates to 'Make a charity repayment claim' page")
      ClaimsTaskListPage_Empty.validateNavigation()
      And("User clicks the link to navigate to 'Repayment claim details' page")
      ClaimsTaskListPage_Empty.clickProvideRepaymentClaimDetails()
      Then("User validates the 'Repayment claim details' page")
      RepaymentClaimDetailsPage.validateNavigation()
      And("User clicks continue on 'Repayment claim details' page")
      RepaymentClaimDetailsPage.clickContinue()
      Then("User navigates to 'Which type of repayment claim do you want to make?' page")
      RepaymentCheckboxPage.validateNavigation()
      And("User selects all 3 checkboxes and clicks continue")
      RepaymentCheckboxPage.checkbox(RepaymentCheckboxPage.GiftAid, true)
      RepaymentCheckboxPage.checkbox(RepaymentCheckboxPage.GASDSclaim, true)
      RepaymentCheckboxPage.checkbox(RepaymentCheckboxPage.OtherIncome, true)
      RepaymentCheckboxPage.clickContinue()
      And("User navigates to 'Gift Aid Small Donations Scheme (GASDS) details' checkbox page")
      GASDSCheckboxPage.validateNavigation()
      And("User selects all 3 checkboxes and clicks continue")
      GASDSCheckboxPage.checkbox(GASDSCheckboxPage.GASDSTopUp, true)
      GASDSCheckboxPage.checkbox(GASDSCheckboxPage.GASDSBuilding, true)
      GASDSCheckboxPage.checkbox(GASDSCheckboxPage.GASDSConnected, true)
      GASDSCheckboxPage.clickContinue()
      Then("User navigates to 'Gift Aid Small Donations Scheme claim' page")
      GiftAidSmallDonationsSchemeClaimPage.validateNavigation()
      And("User selects 'Yes' and clicks continue on 'Gift Aid Small Donations Scheme claim' page")
      GiftAidSmallDonationsSchemeClaimPage.radioButton(GiftAidSmallDonationsSchemeClaimPage.yes)
      GiftAidSmallDonationsSchemeClaimPage.clickContinue()
      Then("User navigates to 'Do you have a claim reference number?' page")
      DoYouHaveAClaimReferenceNumberPage.validateNavigation()
      And("User selects 'Yes' and clicks continue on 'Do you have a claim reference number?' page")
      DoYouHaveAClaimReferenceNumberPage.radioButton(DoYouHaveAClaimReferenceNumberPage.yes)
      DoYouHaveAClaimReferenceNumberPage.clickContinue()
      And("User navigates to 'What is your claim reference number?' page")
      WhatIsYourClaimReferenceNumberPage.validateNavigation()
      And("User enters their claim reference number and clicks continue")
      WhatIsYourClaimReferenceNumberPage.enterClaimReferenceNumber("TESTREF123")
      Then("User navigates to 'Check your repayment claim' page")
      CheckYourRepaymentClaimPage.validateNavigation()
      Then("User navigates to 'Make a charity repayment claim' page")
      CheckYourRepaymentClaimPage.clickContinue()
      ClaimsTaskListPage_InProgress.validateNavigation_AllSubheadings()
      And("User clicks the link to navigate to 'About the organisation' page")
      ClaimsTaskListPage_InProgress.clickProvideOrganisationDetails()
      AboutTheOrganisationPage.validateNavigation()
      Then("User selects continue on 'About the organisation' page")
      AboutTheOrganisationPage.clickContinue()
      And("User navigates to 'What is the name of the charity regulator?' page")
      WhatIsTheNameOfTheCharityRegulatorPage.validateNavigation()
      And("User clicks 'Charity is not registered with a regulator' radio button option")
      WhatIsTheNameOfTheCharityRegulatorPage.radioButton(WhatIsTheNameOfTheCharityRegulatorPage.None)
      And("User clicks 'Continue' button")
      WhatIsTheNameOfTheCharityRegulatorPage.clickContinue()
      And("User navigates to 'Why is the charity not registered with a regulator?' page")
      WhyIsTheCharityNotRegisteredPage.validateNavigation()
      And("User selects they are 'Excepted' radio button option")
      WhyIsTheCharityNotRegisteredPage.radioButton(WhyIsTheCharityNotRegisteredPage.Excepted)
      And("User clicks 'Continue' button")
      WhyIsTheCharityNotRegisteredPage.clickContinue()
      And("User navigates to 'Your charity is excepted' page")
      YourCharityIsExceptedPage.validateNavigation()
      Then("User selects continue on 'Your charity is excepted' page")
      YourCharityIsExceptedPage.clickContinue()
      And("User navigates to 'Is a corporate trustee making this claim?' page")
      IsACorporateTrusteeMakingThisClaimPage.validateNavigation()
      And("User selects a corporate trustee is making this claim")
      IsACorporateTrusteeMakingThisClaimPage.radioButton(IsACorporateTrusteeMakingThisClaimPage.yes)
      IsACorporateTrusteeMakingThisClaimPage.clickContinue()
      And("User navigates to 'Does the corporate trustee have a UK address?' page")
      DoesTheCorporateTrusteeHaveAUKAddressPage.validateNavigation()
      And("User selects a corporate trustee does have a UK address")
      DoesTheCorporateTrusteeHaveAUKAddressPage.radioButton(DoesTheCorporateTrusteeHaveAUKAddressPage.yes)
      DoesTheCorporateTrusteeHaveAUKAddressPage.clickContinue()
      And("User navigates to 'What are the corporate trustee details?' page")
      CorporateTrusteeDetailsPage.validateNavigation()
      And("User enters their Non UK Trustee details and clicks continue")
      CorporateTrusteeDetailsPage.enterUKTrusteeDetails("TEST TRUSTEE", "01632 960999", "WG7 7FU")
      And("User navigates to 'Check your organisation details' page")
      CheckYourOrganisationDetailsPage.validateNavigation()
      And("User navigates to 'Make a charity repayment claim' task list page")
      CheckYourOrganisationDetailsPage.clickContinue()
      ClaimsTaskListPage_InProgress.validateNavigation_AllSubheadings()
      And("User clicks the link to navigate to 'About Gift Aid Small Donations Scheme schedule' page")
      ClaimsTaskListPage_InProgress.clickProvideGASDSDetails()
      And("User Validates the navigation to 'About Gift Aid Small Donations Scheme schedule' page")
      AboutGASDSPage.validateNavigation()
      Then("User navigates to 'What is the adjustment amount for Gift Aid previously overclaimed?' page")
      AboutGASDSPage.clickContinue()
      WhatIsTheAdjustmentAmountForGiftAidPreviouslyOverclaimedPage.validateNavigation()
      Then("User navigates to 'Check your GASDS adjustment amount' page")
      WhatIsTheAdjustmentAmountForGiftAidPreviouslyOverclaimedPage.enterAdjustmentAmountValue("123.45")
      And("Validates Navigation of the 'Check your GASDS adjustment amount' page")
      CheckYourGASDSAdjustmentAmountPage.validateNavigation()
      Then("User navigates to 'Which tax year are you claiming for?' year 1 page")
      CheckYourGASDSAdjustmentAmountPage.clickContinue()
      WhichTaxYearAreYouClaimingForPage.validateNavigation1()
      Then(
        s"User inputs " + WhichTaxYearAreYouClaimingForPage.earliestTaxYear + " on 'Which tax year are you claiming for?' page"
      )
      WhichTaxYearAreYouClaimingForPage.enterValidTaxYear(WhichTaxYearAreYouClaimingForPage.earliestTaxYear)
      Then("User navigates to 'What donation amount are you claiming, in pounds?' for the first year page")
      WhatDonationAmountAreYouClaimingUnderGASDSPage.validateNavigation_Year1()
      Then(
        "User inputs a value on 'What donation amount are you claiming under GASDS, in pounds?' for the first year page"
      )
      WhatDonationAmountAreYouClaimingUnderGASDSPage.enterDonationAmount("1.11")
      Then("User navigates to 'Check your claim details for tax year 1' page")
      CheckYourClaimDetailsForTaxYearPage.validateNavigation1()
      Then("User navigates to 'You have added a claim for 1 tax year' page")
      CheckYourClaimDetailsForTaxYearPage.clickContinue()
      YouHaveAddedAClaimForXTaxYearPage.validateNavigation1()
      Then("User selects 'Yes' on 'You have added a claim for 1 tax year' page to add another tax year")
      YouHaveAddedAClaimForXTaxYearPage.radioButton(YouHaveAddedAClaimForXTaxYearPage.yes)
      YouHaveAddedAClaimForXTaxYearPage.clickContinue()
      Then("User navigates to 'Which tax year are you claiming for?' year 2 page")
      WhichTaxYearAreYouClaimingForPage.validateNavigation2()
      Then(
        s"User on 'Which tax year are you claiming for?' page inputs: " + WhichTaxYearAreYouClaimingForPage.secondEarliestTaxYear
      )
      WhichTaxYearAreYouClaimingForPage.enterValidTaxYear(WhichTaxYearAreYouClaimingForPage.secondEarliestTaxYear)
      Then("User navigates to 'What donation amount are you claiming under GASDS, in pounds?' for the second year page")
      WhatDonationAmountAreYouClaimingUnderGASDSPage.validateNavigation_Year2()
      Then(
        "User inputs a value on 'What donation amount are you claiming under GASDS, in pounds?' for the second year page"
      )
      WhatDonationAmountAreYouClaimingUnderGASDSPage.enterDonationAmount("2.22")
      Then("User navigates to 'Check your claim details for tax year 2' page")
      CheckYourClaimDetailsForTaxYearPage.validateNavigation2()
      Then("User navigates to 'You have added a claim for 2 tax years' page")
      CheckYourClaimDetailsForTaxYearPage.clickContinue()
      YouHaveAddedAClaimForXTaxYearPage.validateNavigation2()
      Then("User selects 'Yes' on 'You have added a claim for 2 tax year' page to add another tax year")
      YouHaveAddedAClaimForXTaxYearPage.radioButton(YouHaveAddedAClaimForXTaxYearPage.yes)
      YouHaveAddedAClaimForXTaxYearPage.clickContinue()
      Then("User navigates to 'Which tax year are you claiming for?' year 3 page")
      WhichTaxYearAreYouClaimingForPage.validateNavigation3()
      Then(
        s"User navigates to 'Which tax year are you claiming for?' page and inputs: " + WhichTaxYearAreYouClaimingForPage.recentTaxYear
      )
      WhichTaxYearAreYouClaimingForPage.enterValidTaxYear(WhichTaxYearAreYouClaimingForPage.recentTaxYear)
      Then("User navigates to 'What donation amount are you claiming under GASDS, in pounds?' for the third year page")
      WhatDonationAmountAreYouClaimingUnderGASDSPage.validateNavigation_Year3()
      Then(
        "User inputs a value on 'What donation amount are you claiming under GASDS, in pounds?' for the third year page"
      )
      WhatDonationAmountAreYouClaimingUnderGASDSPage.enterDonationAmount("3.33")
      Then("User navigates to 'Check your claim details for tax year 3' page")
      CheckYourClaimDetailsForTaxYearPage.validateNavigation3()
      Then("User navigates to 'You have added a claim for 3 tax years' page")
      CheckYourClaimDetailsForTaxYearPage.clickContinue()
      YouHaveAddedAClaimForXTaxYearPage.validateNavigation3()
      Then("User selects to remove the 2nd tax year from 'You have added a claim for 3 tax years' page")
      YouHaveAddedAClaimForXTaxYearPage.clickRemoveRow2Link()
      Then("User navigates to 'Do you want to remove the claim for tax year 2025?' page")
      RemoveClaimForTaxYearPage.validateNavigation2()
      Then("User confirms to remove the 2nd tax year from 'You have added a claim for 3 tax years' page")
      RemoveClaimForTaxYearPage.radioButton(RemoveClaimForTaxYearPage.yes)
      Then("User navigates to 'You have added a claim for 2 tax years' page")
      RemoveClaimForTaxYearPage.clickContinue()
      YouHaveAddedAClaimForXTaxYearPage.validateNavigation2()
      Then("User selects 'No' on 'You have added a claim for 2 tax year' page to add another tax year")
      YouHaveAddedAClaimForXTaxYearPage.radioButton(YouHaveAddedAClaimForXTaxYearPage.no)
      YouHaveAddedAClaimForXTaxYearPage.clickContinue()
      Then("User navigates to 'Check your GASDS donation details' page and validates page details")
      CheckYourGASDSDonationDetailsPage.validateNavigation()
      Then("User Clicks 'Change' Link of GASDS Previously overclaimed Adjustment Amount")
      CheckYourGASDSDonationDetailsPage.clickChangeGASDSAdjustmentAmount()
      And("User navigates to 'Check Your GASDS Adjustment Amount page' and validates Navigation")
      CheckYourGASDSAdjustmentAmountPage.validateChangeNavigation()
      Then("User Clicks CONTINUE to reach directly to 'Check your GASDS Donation details' Page")
      CheckYourGASDSAdjustmentAmountPage.clickContinue()
      And("Validates Navigation of Check your GASDS Donation Details Page")
      CheckYourGASDSDonationDetailsPage.validateNavigation()
      Then("User Clicks 'Change' Link of GASDS Number of Tax Years Added ")
      CheckYourGASDSDonationDetailsPage.clickChangeGASDSTaxYears()
      Then("User navigates to 'You have added a claim for 2 tax years' page")
      YouHaveAddedAClaimForXTaxYearPage.validateNavigation2()
      Then("User selects 'No' on 'You have added a claim for 2 tax year' page to add another tax year")
      YouHaveAddedAClaimForXTaxYearPage.radioButton(YouHaveAddedAClaimForXTaxYearPage.no)
      YouHaveAddedAClaimForXTaxYearPage.clickContinue()
      Then("User navigates to 'Check your GASDS donation details' page and validates page details")
      CheckYourGASDSDonationDetailsPage.validateNavigation()
      Then("User clicks CONTINUE to reach task list: 'Make a repayment Claim' Page")
      CheckYourGASDSDonationDetailsPage.clickConfirmAndSubmit()
      And("User validates navigation to 'Make a repayment Claim' Page")
      ClaimsTaskListPage_InProgress.validateNavigation_AllSubheadings()
      And("User clicks the link to navigate to 'Add Gift Aid schedule' page")
      ClaimsTaskListPage_InProgress.clickAddGiftAidSchedule()
      Then("User navigates to 'About Gift Aid schedule' page")
      AboutGiftAidSchedulePage.validateNavigation()
      AboutGiftAidSchedulePage.clickContinue()
      Then("User navigates to 'Upload a Gift Aid schedule' page")
      UploadAGiftAidSchedulePage.validateNavigation()
      Then("User navigates to the Charities Management service and then to the claim in progress to view its statuses")
      UploadAGiftAidSchedulePage.clickServiceNavLink()
      CharitiesManagementPlaceholder.validateNavigation()
      And(
        "User clicks the link 'Continue claim' to navigate to task list 'Make a charity repayment claim' page"
      )
      CharitiesManagementPlaceholder.clickContinueClaimLink()
      ClaimsTaskListPage_InProgress.validateNavigation_AllSubheadings()
      And("User clicks the link to navigate to 'Add Gift Aid schedule' page")
      ClaimsTaskListPage_InProgress.clickAddGiftAidSchedule()
      Then("User navigates to 'About Gift Aid schedule' page")
      AboutGiftAidSchedulePage.validateNavigation()
      AboutGiftAidSchedulePage.clickContinue()
      Then("User navigates to 'Upload a Gift Aid schedule' page")
      UploadAGiftAidSchedulePage.validateNavigation()
      Then("User selects a file to upload in the 'Upload a Gift Aid schedule' page")
      UploadAGiftAidSchedulePage.selectFile("GiftAidSpreadsheets/Gift-Aid-Schedule-SIMPLEFAIL")
      UploadAGiftAidSchedulePage.clickContinue()
      Then("User navigates to 'Your Gift Aid schedule upload' page")
      YourGiftAidScheduleUploadPage.validateNavigation()
      YourGiftAidScheduleUploadPage.waitForFileUpload()
      YourGiftAidScheduleUploadPage.clickContinue()
      Then("User navigates to 'There is a problem with the data in your Gift Aid schedule' page")
      CheckYourGiftAidScheduleErrorPage.validateNavigation()
      And("User selects 'Delete Schedule' on 'There is a problem with the data in your Gift Aid schedule' page")
      CheckYourGiftAidScheduleErrorPage.clickDeleteScheduleLink()
      Then("User navigates to 'Do you want to delete this Gift Aid schedule?' page")
      DeleteGiftAidSchedulePage.validateNavigation()
      And("User selects 'Yes' and clicks continue on 'Do you want to delete this Gift Aid schedule?' page")
      DeleteGiftAidSchedulePage.radioButton(DeleteGiftAidSchedulePage.yes)
      DeleteGiftAidSchedulePage.clickContinue()
      Then("User navigates to 'Make a charity repayment claim' page")
      ClaimsTaskListPage_InProgress.validateNavigation_AllSubheadings()
      Then("User navigates to 'About Gift Aid schedule' page")
      ClaimsTaskListPage_InProgress.clickAddGiftAidSchedule()
      AboutGiftAidSchedulePage.validateNavigation()
      AboutGiftAidSchedulePage.clickContinue()
      Then("User navigates to 'Upload a Gift Aid schedule' page")
      UploadAGiftAidSchedulePage.validateNavigation()
      Then("User selects a file to upload in the 'Upload a Gift Aid schedule' page")
      UploadAGiftAidSchedulePage.selectFile("GiftAidSpreadsheets/Gift-Aid-Schedule-SIMPLEPASS_MAX_ROWS_EXCEPTED")
      UploadAGiftAidSchedulePage.clickContinue()
      Then("User navigates to 'Your Gift Aid schedule upload' page")
      YourGiftAidScheduleUploadPage.validateNavigation()
      YourGiftAidScheduleUploadPage.waitForFileUpload()
      YourGiftAidScheduleUploadPage.clickContinue()
      Then("User navigates to 'Check your Gift Aid schedule' page")
      CheckYourGiftAidSchedulePage.validateNavigation()
      Then("User selects 'no' to if they want to upload a new schedule on the 'Check your Gift Aid schedule' page")
      CheckYourGiftAidSchedulePage.radioButton(CheckYourGiftAidSchedulePage.no)
      CheckYourGiftAidSchedulePage.clickContinue()
      Then("User navigates to 'Successful Gift Aid Upload' page")
      GiftAidUploadSuccessfulPage.validateNavigation()
      Then("User navigates to 'Make a charity repayment claim' page")
      GiftAidUploadSuccessfulPage.clickContinue()
      ClaimsTaskListPage_InProgress.validateNavigation_AllSubheadings()
      ClaimsTaskListPage_InProgress.clickAddOtherIncomeSchedule()
      Then("User navigates to 'About Other Income schedule' page")
      AboutOtherIncomeSchedulePage.validateNavigation()
      AboutOtherIncomeSchedulePage.clickContinue()
      Then("User navigates to 'Upload an Other Income schedule' page")
      UploadAnOtherIncomeSchedulePage.validateNavigation()
      Then("User selects a file to upload in the 'Upload an Other Income schedule' page")
      UploadAnOtherIncomeSchedulePage.selectFile("OtherIncomeSpreadsheets/Other-Income-Schedule-BadData")
      UploadAnOtherIncomeSchedulePage.clickContinue()
      Then("User navigates to 'Your Other Income schedule upload' page")
      YourOtherIncomeScheduleUploadPage.validateNavigation()
      YourOtherIncomeScheduleUploadPage.waitForFileUpload()
      YourOtherIncomeScheduleUploadPage.clickContinue()
      Then("User navigates to 'Problem with your Other Income schedule data' page and validates page")
      CheckYourOtherIncomeScheduleErrorPage.validateNavigation()
      Then("User clicks on the Delete Schedule link and reaches the Delete Schedule WRN 1.0 page")
      CheckYourOtherIncomeScheduleErrorPage.clickDeleteScheduleLink()
      Then("User validates navigation of Delete Schedule WRN 1.0 page")
      DeleteOtherIncomeSchedulePage.validateNavigation()
      Then("User clicks back to reach 'problem with your Other Income schedule' page")
      DeleteOtherIncomeSchedulePage.clickBackLink()
      Then("User reaches the 'problem with your Other Income schedule page' and validates the navigation")
      CheckYourOtherIncomeScheduleErrorPage.validateNavigation()
      Then(
        "User clicks on 'Attach an updated Other Income schedule' that deletes the invalid ODS and navigates to" +
          " 'upload a Other Income schedule page O1.1' "
      )
      CheckYourOtherIncomeScheduleErrorPage.clickAttachUpdatedSchedule()
      Then("User validates navigation of 'upload a Other Income schedule page O1.1' ")
      UploadAnOtherIncomeSchedulePage.validateNavigation()
      Then("User selects a file to upload in the 'Upload a Other Income schedule' page")
      UploadAnOtherIncomeSchedulePage.selectFile("OtherIncomeSpreadsheets/Other-Income-Schedule-GoodData")
      UploadAnOtherIncomeSchedulePage.clickContinue()
      Then("User navigates to 'Your Other Income schedule upload' page")
      YourOtherIncomeScheduleUploadPage.validateNavigation()
      YourOtherIncomeScheduleUploadPage.waitForFileUpload()
      YourOtherIncomeScheduleUploadPage.clickContinue()
      Then("User navigates to 'Check your Other Income schedule' page")
      CheckYourOtherIncomeSchedulePage.validateNavigation()
      Then("User selects the 'no' to upload another spreadsheet on the 'Check your Other Income schedule' page")
      CheckYourOtherIncomeSchedulePage.radioButton(CheckYourOtherIncomeSchedulePage.no)
      CheckYourOtherIncomeSchedulePage.clickContinue()
      Then("User navigates and validates 'Successful Other Income Upload' page")
      OtherIncomeUploadSuccessfulPage.validateNavigation()
      Then("User navigates to 'Make a charity repayment claim' page")
      OtherIncomeUploadSuccessfulPage.clickContinue()
      ClaimsTaskListPage_InProgress.validateNavigation_AllSubheadings()
      And("User clicks the link to navigate to 'Add Community Buildings schedule' page")
      ClaimsTaskListPage_InProgress.clickAddCommunityBuildingsSchedule()
      Then("User navigates to 'About Community Buildings schedule' page")
      AboutCommunityBuildingsSchedulePage.validateNavigation()
      Then("User navigates to 'Upload a Community Buildings schedule' page")
      AboutCommunityBuildingsSchedulePage.clickContinue()
      UploadACommunityBuildingsSchedulePage.validateNavigation()
      Then("User selects a file to upload in the 'Upload a Community Buildings schedule' page")
      UploadACommunityBuildingsSchedulePage.selectFile(
        "CommunityBuildingsSpreadsheets/community-buildings-excel-BadData"
      )
      UploadACommunityBuildingsSchedulePage.clickContinue()
      Then("User navigates to 'Your Community Buildings schedule upload' page")
      YourCommunityBuildingsScheduleUploadPage.validateNavigation()
      YourCommunityBuildingsScheduleUploadPage.waitForFileUpload()
      YourCommunityBuildingsScheduleUploadPage.clickContinue()
      Then("User navigates to 'Check your Community Buildings schedule' page")
      CheckYourCommunityBuildingsScheduleErrorPage.validateNavigation()
      Then("User clicks on the Delete Schedule link and reaches the Delete Schedule WRN 1.2 page")
      CheckYourCommunityBuildingsScheduleErrorPage.clickDeleteScheduleLink()
      Then("User validates navigation of Delete Schedule WRN 1.2 page")
      DeleteGASDSCommunityBuildingsSchedulePage.validateNavigation()
      Then("User clicks back to reach 'problem with your CBS' page")
      DeleteGASDSCommunityBuildingsSchedulePage.clickBackLink()
      Then("User reaches the 'problem with your CBS page' and validates the navigation")
      CheckYourCommunityBuildingsScheduleErrorPage.validateNavigation()
      Then(
        "User clicks on 'Attach an updated Community Buildings schedule' that deletes the invalid ODS and navigates to" +
          " 'upload a CBS page B1.1' "
      )
      CheckYourCommunityBuildingsScheduleErrorPage.clickAttachUpdatedSchedule()
      Then("User validates navigation of 'upload a CBS page B1.1'")
      UploadACommunityBuildingsSchedulePage.validateNavigation()
      Then("User selects the service navigation to return to the initial dashboard")
      UploadACommunityBuildingsSchedulePage.clickServiceNavLink()
      CharitiesManagementPlaceholder.validateNavigation()
      And(
        "User clicks the link 'Continue claim' to navigate to task list 'Make a charity repayment claim' page"
      )
      CharitiesManagementPlaceholder.clickContinueClaimLink()
      ClaimsTaskListPage_InProgress.validateNavigation_AllSubheadings()
      And("User clicks the link to navigate to 'Add Community Buildings schedule' page")
      ClaimsTaskListPage_InProgress.clickAddCommunityBuildingsSchedule()
      Then("User navigates to 'About Community Buildings schedule' page")
      AboutCommunityBuildingsSchedulePage.validateNavigation()
      Then("User navigates to 'Upload a Community Buildings schedule' page")
      AboutCommunityBuildingsSchedulePage.clickContinue()
      UploadACommunityBuildingsSchedulePage.validateNavigation()
      Then("User selects a file to upload in the 'Upload a Community Buildings schedule' page")
      UploadACommunityBuildingsSchedulePage.selectFile(
        "CommunityBuildingsSpreadsheets/CommunityBuildingsPassRows"
      )
      UploadACommunityBuildingsSchedulePage.clickContinue()
      Then("User navigates to 'Your Community Buildings schedule upload' page")
      YourCommunityBuildingsScheduleUploadPage.validateNavigation()
      YourCommunityBuildingsScheduleUploadPage.waitForFileUpload()
      YourCommunityBuildingsScheduleUploadPage.clickContinue()
      Then("User navigates to 'Check your Community Buildings schedule' page")
      CheckYourCommunityBuildingsSchedulePage.validateNavigation()
      Then("User selects the 'no' to upload another spreadsheet on the 'Check your Community Buildings schedule' page")
      CheckYourCommunityBuildingsSchedulePage.radioButton(CheckYourCommunityBuildingsSchedulePage.no)
      CheckYourCommunityBuildingsSchedulePage.clickContinue()
      Then("User navigates and validates 'Successful Community Buildings Upload' page")
      CommunityBuildingsScheduleUploadSuccessfulPage.validateNavigation()
      Then("User navigates to 'Make a charity repayment claim' page")
      CommunityBuildingsScheduleUploadSuccessfulPage.clickContinue()
      ClaimsTaskListPage_InProgress.validateNavigation_AllSubheadings()
      And("User clicks the link to navigate to 'Add Connected Charities schedule' page")
      ClaimsTaskListPage_InProgress.clickAddConnectedCharitiesSchedule()
      Then("User navigates to 'About Connected Charities schedule' page")
      AboutConnectedCharitiesSchedulePage.validateNavigation()
      AboutConnectedCharitiesSchedulePage.clickContinue()
      Then("User navigates to 'Upload a Connected Charities schedule' page")
      UploadAConnectedCharitiesSchedulePage.validateNavigation()
      Then("User selects a file to upload in the 'Upload a Connected Charities schedule' page")
      UploadAConnectedCharitiesSchedulePage.selectFile(
        "ConnectedCharitiesSpreadsheets/Connected-Charities-schedule-Excel-BadData"
      )
      UploadAConnectedCharitiesSchedulePage.clickContinue()
      Then("User navigates to 'Your Connected Charities schedule upload' page")
      YourConnectedCharitiesScheduleUploadPage.validateNavigation()
      YourConnectedCharitiesScheduleUploadPage.waitForFileUpload()
      YourConnectedCharitiesScheduleUploadPage.clickContinue()
      Then("User navigates to 'Problem with your Connected Charities schedule data' page and validates page")
      CheckYourConnectedCharitiesScheduleErrorPage.validateNavigation()
      Then("User clicks on the Delete Schedule link and reaches the Delete Schedule WRN 1.3 page")
      CheckYourConnectedCharitiesScheduleErrorPage.clickDeleteScheduleLink()
      Then("User validates navigation of Delete Schedule WRN 1.3 page")
      DeleteGASDSConnectedCharitiesSchedulePage.validateNavigation()
      Then("User clicks back to reach 'problem with your Connected Charities schedule' page")
      DeleteGASDSConnectedCharitiesSchedulePage.clickBackLink()
      Then("User reaches the 'problem with your Connected Charities schedule page' and validates the navigation")
      CheckYourConnectedCharitiesScheduleErrorPage.validateNavigation()
      Then(
        "User clicks on 'Attach an updated Connected Charities schedule' that deletes the invalid ODS and navigates to" +
          " 'upload a Connected Charities schedule page CC1.1' "
      )
      CheckYourConnectedCharitiesScheduleErrorPage.clickAttachUpdatedSchedule()
      Then("User validates navigation of 'upload a Connected Charities schedule page CC1.1' ")
      UploadAConnectedCharitiesSchedulePage.validateNavigation()
      Then("User selects a file to upload in the 'Upload a Connected Charities schedule' page")
      UploadAConnectedCharitiesSchedulePage.selectFile(
        "ConnectedCharitiesSpreadsheets/Connected-Charities-schedule-Excel-GoodData"
      )
      UploadAConnectedCharitiesSchedulePage.clickContinue()
      Then("User navigates to 'Your Connected Charities upload' page")
      YourConnectedCharitiesScheduleUploadPage.validateNavigation()
      YourConnectedCharitiesScheduleUploadPage.waitForFileUpload()
      YourConnectedCharitiesScheduleUploadPage.clickContinue()
      Then("User navigates to 'Check your Connected Charities schedule' page")
      CheckYourConnectedCharitiesSchedulePage.validateNavigation()
      Then("User selects the 'no' to upload another spreadsheet on the 'Check your Connected Charities schedule' page")
      CheckYourConnectedCharitiesSchedulePage.radioButton(CheckYourConnectedCharitiesSchedulePage.no)
      CheckYourConnectedCharitiesSchedulePage.clickContinue()
      Then("User navigates and validates 'Successful Connected Charities Upload' page")
      ConnectedCharitiesUploadSuccessfulPage.validateNavigation()
      Then("User navigates to 'Make a charity repayment claim' page")
      ConnectedCharitiesUploadSuccessfulPage.clickContinue()
      ClaimsTaskListPage_InProgress.validateNavigation_AllSubheadings()
      Then("User navigates to 'What adjustments have you made to this claim?' page")
      ClaimsTaskListPage_InProgress.clickReadDeclaration()
      RegisteringYourCharityWithRegulatorPage_Excepted.validateNavigation()
      Then("User navigates back to 'Make a charity repayment claim' page")
      RegisteringYourCharityWithRegulatorPage_Excepted.navigateToPage(ClaimsTaskListPage_InProgress.pageUrl)
      ClaimsTaskListPage_InProgress.validateNavigation_AllSubheadings()
      Then("User navigates to 'Check your organisation details' page")
      ClaimsTaskListPage_InProgress.clickCheckYourOrganisationDetails()
      CheckYourOrganisationDetailsPage.validateNavigation()
      And("User clicks the link to navigate to 'Why is the charity not registered with a regulator?' page")
      CheckYourOrganisationDetailsPage.clickChangeRegisteredWithRegulator()
      WhyIsTheCharityNotRegisteredPage.validateChangeNavigation()
      And("User selects they are 'Low Income' radio button option")
      WhyIsTheCharityNotRegisteredPage.radioButton(WhyIsTheCharityNotRegisteredPage.LowIncome)
      WhyIsTheCharityNotRegisteredPage.clickContinue()
      Then("User navigates to 'Check your organisation details' page")
      CheckYourOrganisationDetailsPage.validateNavigation()
      And("User navigates to 'Make a charity repayment claim' task list page")
      CheckYourOrganisationDetailsPage.clickContinue()
      ClaimsTaskListPage_InProgress.validateNavigation_AllSubheadings()
      Then("User navigates to 'About Gift Aid schedule' page")
      ClaimsTaskListPage_InProgress.clickAddGiftAidSchedule()
      Then("User navigates to 'Your Gift Aid schedule upload' page")
      YourGiftAidScheduleUploadPage.validateNavigation()
      YourGiftAidScheduleUploadPage.clickContinue()
      Then("User navigates to 'Check your Gift Aid schedule' page")
      CheckYourGiftAidSchedulePage.validateNavigation()
      Then("User selects 'no' to if they want to upload a new schedule on the 'Check your Gift Aid schedule' page")
      CheckYourGiftAidSchedulePage.radioButton(CheckYourGiftAidSchedulePage.yes)
      CheckYourGiftAidSchedulePage.clickContinue()
      Then("User navigates to 'Update your Gift Aid Schedule' page ")
      UpdateGiftAidSchedulePage.validateNavigation()
      UpdateGiftAidSchedulePage.clickContinue()
      And("User selects 'Yes' and clicks continue on 'Update your Gift Aid Schedule' page")
      UpdateGiftAidSchedulePage.radioButton(UpdateGiftAidSchedulePage.yes)
      UpdateGiftAidSchedulePage.clickContinue()
      Then("User navigates to 'Upload a Gift Aid schedule' page")
      UploadAGiftAidSchedulePage.validateNavigation()
      Then("User selects a file to upload in the 'Upload a Gift Aid schedule' page")
      UploadAGiftAidSchedulePage.selectFile("GiftAidSpreadsheets/Gift-Aid-Schedule-SIMPLEPASS_MAX_ROWS_LOW_INCOME")
      UploadAGiftAidSchedulePage.clickContinue()
      Then("User navigates to 'Your Gift Aid schedule upload' page")
      YourGiftAidScheduleUploadPage.validateNavigation()
      YourGiftAidScheduleUploadPage.waitForFileUpload()
      YourGiftAidScheduleUploadPage.clickContinue()
      Then("User navigates to 'Check your Gift Aid schedule' page")
      CheckYourGiftAidSchedulePage.validateNavigation()
      Then("User selects 'no' to if they want to upload a new schedule on the 'Check your Gift Aid schedule' page")
      CheckYourGiftAidSchedulePage.radioButton(CheckYourGiftAidSchedulePage.no)
      CheckYourGiftAidSchedulePage.clickContinue()
      Then("User navigates to 'Successful Gift Aid Upload' page")
      GiftAidUploadSuccessfulPage.validateNavigation()
      Then("User navigates to 'Make a charity repayment claim' page")
      GiftAidUploadSuccessfulPage.clickContinue()
      ClaimsTaskListPage_InProgress.validateNavigation_AllSubheadings()
      Then("User navigates to 'What adjustments have you made to this claim?' page")
      ClaimsTaskListPage_InProgress.clickReadDeclaration()
      RegisteringYourCharityWithRegulatorPage_LowIncome.validateNavigation()
      And("User validates 'Registering your charity with a regulator' page elements")
      RegisteringYourCharityWithRegulatorPage_LowIncome.validatePageContent()
      And("User selects 'no' and clicks continue on 'Registering your charity with a regulator' page")
      RegisteringYourCharityWithRegulatorPage_LowIncome.radioButton(
        RegisteringYourCharityWithRegulatorPage_LowIncome.no
      )
      RegisteringYourCharityWithRegulatorPage_LowIncome.clickContinue()
      Then("User navigates to 'What adjustments have you made to this claim?' page elements")
      WhatAdjustmentsHaveYouMadeToThisClaimPage.validateNavigation()
      Then("User inputs details on 'Declaration' page")
      WhatAdjustmentsHaveYouMadeToThisClaimPage.enterAdjustmentDetails("TEST ADJUSTMENT INPUT")
      DeclarationPage.validateNavigation()
      Then("User navigates to 'Claim complete' page")
      DeclarationPage.clickConfirmAndSubmit()
      ClaimCompletePage.validateNavigation()
      Then("User navigates to 'Charity repayment claim summary' page")
      ClaimCompletePage.clickPrintClaimSummaryLink()
      And("User validates Gift Aid, Other Income and Adjustment Headings on Page")
      CharityRepaymentClaimSummaryPage.validateNavigation()
    }

    Scenario(
      "User navigates through a full Org user journey - No Regulator - Exempt - Official - UK Address - GA ODS - Delete Claim"
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.login(HASDIRECT, Organisation, "Organisation", "HMRC-CHAR-ORG", "CHARID", "IT00072")
      Then("User navigates to 'Manage charity repayment claims' page and validates navigation")
      CharitiesManagementPlaceholder.validateNavigation()
      And(
        "User clicks the link 'Use the charities online service' to navigate to task list 'Make a charity repayment claim' page"
      )
      CharitiesManagementPlaceholder.clickUseTheCharitiesLink()
      Then("User navigates to 'Make a charity repayment claim' page")
      ClaimsTaskListPage_Empty.validateNavigation()
      And("User clicks the link to navigate to 'Repayment claim details' page")
      ClaimsTaskListPage_Empty.clickProvideRepaymentClaimDetails()
      Then("User validates the 'Repayment claim details' page")
      RepaymentClaimDetailsPage.validateNavigation()
      And("User clicks continue on 'Repayment claim details' page")
      RepaymentClaimDetailsPage.clickContinue()
      Then("User navigates to 'Which type of repayment claim do you want to make?' page")
      RepaymentCheckboxPage.validateNavigation()
      And("User selects all GA checkbox and clicks continue")
      RepaymentCheckboxPage.checkbox(RepaymentCheckboxPage.GiftAid, true)
      RepaymentCheckboxPage.clickContinue()
      Then("User navigates to 'Do you have a claim reference number?' page")
      DoYouHaveAClaimReferenceNumberPage.validateNavigation()
      And("User selects 'Yes' and clicks continue on 'Do you have a claim reference number?' page")
      DoYouHaveAClaimReferenceNumberPage.radioButton(DoYouHaveAClaimReferenceNumberPage.yes)
      DoYouHaveAClaimReferenceNumberPage.clickContinue()
      And("User navigates to 'What is your claim reference number?' page")
      WhatIsYourClaimReferenceNumberPage.validateNavigation()
      And("User enters their claim reference number and clicks continue")
      WhatIsYourClaimReferenceNumberPage.enterClaimReferenceNumber("TESTREF123")
      Then("User navigates to 'Check your repayment claim' page")
      CheckYourRepaymentClaimPage.validateNavigation()
      Then("User navigates to 'Make a charity repayment claim' page")
      CheckYourRepaymentClaimPage.clickContinue()
      ClaimsTaskListPage_InProgress.validateNavigation_AllSubheadings()
      And("User clicks the link to navigate to 'About the organisation' page")
      ClaimsTaskListPage_InProgress.clickProvideOrganisationDetails()
      AboutTheOrganisationPage.validateNavigation()
      Then("User selects continue on 'About the organisation' page")
      AboutTheOrganisationPage.clickContinue()
      And("User navigates to 'What is the name of the charity regulator?' page")
      WhatIsTheNameOfTheCharityRegulatorPage.validateNavigation()
      And("User clicks 'Charity is not registered with a regulator' radio button option")
      WhatIsTheNameOfTheCharityRegulatorPage.radioButton(WhatIsTheNameOfTheCharityRegulatorPage.None)
      And("User clicks 'Continue' button")
      WhatIsTheNameOfTheCharityRegulatorPage.clickContinue()
      And("User navigates to 'Why is the charity not registered with a regulator?' page")
      WhyIsTheCharityNotRegisteredPage.validateNavigation()
      And("User clicks 'Charity is not registered with a regulator' radio button option")
      WhyIsTheCharityNotRegisteredPage.radioButton(WhyIsTheCharityNotRegisteredPage.Exempt)
      And("User clicks 'Continue' button")
      WhyIsTheCharityNotRegisteredPage.clickContinue()
      And("User navigates to 'Your charity is exempt' page")
      YourCharityIsExemptPage.validateNavigation()
      Then("User selects continue on 'Your charity is exempt' page")
      YourCharityIsExemptPage.clickContinue()
      And("User navigates to 'Is a corporate trustee making this claim?' page")
      IsACorporateTrusteeMakingThisClaimPage.validateNavigation()
      And("User selects an authorised official is making this claim")
      IsACorporateTrusteeMakingThisClaimPage.radioButton(IsACorporateTrusteeMakingThisClaimPage.no)
      IsACorporateTrusteeMakingThisClaimPage.clickContinue()
      And("User navigates to 'Does the authorised official have a UK address?' page")
      DoesTheAuthorisedOfficialHaveAUKAddressPage.validateNavigation()
      And("User selects that the authorised official does have a UK address")
      DoesTheAuthorisedOfficialHaveAUKAddressPage.radioButton(DoesTheAuthorisedOfficialHaveAUKAddressPage.yes)
      DoesTheAuthorisedOfficialHaveAUKAddressPage.clickContinue()
      And("User navigates to 'What are the authorised official details?' page")
      AuthorisedOfficialDetailsPage.validateNavigation()
      And("User enters their UK Authorised Official details and clicks continue")
      AuthorisedOfficialDetailsPage.enterUKAuthOfficialDetails(
        "TEST",
        "TESTFORENAME",
        "TESTSURNAME",
        "01632 960999",
        "WG7 7FU"
      )
      And("User navigates to 'Check your organisation details' page")
      CheckYourOrganisationDetailsPage.validateNavigation()
      And("User navigates to 'Make a charity repayment claim' task list page")
      CheckYourOrganisationDetailsPage.clickContinue()
      ClaimsTaskListPage_InProgress.validateNavigation_AllSubheadings()
      Then("User navigates to 'Are you sure you want to delete this repayment claim?' page")
      ClaimsTaskListPage_InProgress.clickDeleteClaim()
      DeleteRepaymentClaimPage.validateNavigation()
      And(
        "User selects 'Yes' and clicks continue on 'Are you sure you want to delete this repayment claim?' page"
      )
      DeleteRepaymentClaimPage.radioButton(DeleteRepaymentClaimPage.yes)
      DeleteRepaymentClaimPage.clickContinue()
      Then("User navigates to 'Manage charity repayment claims' page and validates navigation")
      CharitiesManagementPlaceholder.validateNavigation()
    }

    Scenario(
      "User navigates through a full Org user journey - Regulator - Auth Official - UK Address - GA ODS - Delete Claim"
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.login(HASDIRECT, Organisation, "Organisation", "HMRC-CHAR-ORG", "CHARID", "IT00073")
      Then("User navigates to 'Manage charity repayment claims' page and validates navigation")
      CharitiesManagementPlaceholder.validateNavigation()
      And(
        "User clicks the link 'Use the charities online service' to navigate to task list 'Make a charity repayment claim' page"
      )
      CharitiesManagementPlaceholder.clickUseTheCharitiesLink()
      Then("User navigates to 'Make a charity repayment claim' page")
      ClaimsTaskListPage_Empty.validateNavigation()
      And("User clicks the link to navigate to 'Repayment claim details' page")
      ClaimsTaskListPage_Empty.clickProvideRepaymentClaimDetails()
      Then("User validates the 'Repayment claim details' page")
      RepaymentClaimDetailsPage.validateNavigation()
      And("User clicks continue on 'Repayment claim details' page")
      RepaymentClaimDetailsPage.clickContinue()
      Then("User navigates to 'Which type of repayment claim do you want to make?' page")
      RepaymentCheckboxPage.validateNavigation()
      And("User selects all GA checkbox and clicks continue")
      RepaymentCheckboxPage.checkbox(RepaymentCheckboxPage.GiftAid, true)
      RepaymentCheckboxPage.clickContinue()
      Then("User navigates to 'Do you have a claim reference number?' page")
      DoYouHaveAClaimReferenceNumberPage.validateNavigation()
      And("User selects 'Yes' and clicks continue on 'Do you have a claim reference number?' page")
      DoYouHaveAClaimReferenceNumberPage.radioButton(DoYouHaveAClaimReferenceNumberPage.yes)
      DoYouHaveAClaimReferenceNumberPage.clickContinue()
      And("User navigates to 'What is your claim reference number?' page")
      WhatIsYourClaimReferenceNumberPage.validateNavigation()
      And("User enters their claim reference number and clicks continue")
      WhatIsYourClaimReferenceNumberPage.enterClaimReferenceNumber("TESTREF123")
      Then("User navigates to 'Check your repayment claim' page")
      CheckYourRepaymentClaimPage.validateNavigation()
      Then("User navigates to 'Make a charity repayment claim' page")
      CheckYourRepaymentClaimPage.clickContinue()
      ClaimsTaskListPage_InProgress.validateNavigation_AllSubheadings()
      And("User clicks the link to navigate to 'About the organisation' page")
      ClaimsTaskListPage_InProgress.clickProvideOrganisationDetails()
      AboutTheOrganisationPage.validateNavigation()
      Then("User selects continue on 'About the organisation' page")
      AboutTheOrganisationPage.clickContinue()
      And("User navigates to 'What is the name of the charity regulator?' page")
      WhatIsTheNameOfTheCharityRegulatorPage.validateNavigation()
      And("User clicks 'Charity is not registered with a regulator' radio button option")
      WhatIsTheNameOfTheCharityRegulatorPage.radioButton(WhatIsTheNameOfTheCharityRegulatorPage.Scot)
      And("User clicks 'Continue' button")
      WhatIsTheNameOfTheCharityRegulatorPage.clickContinue()
      And("User navigates to 'What is the charity regulator number?' page")
      WhatIsYourCharityRegulatorNumberPage.validateNavigation()
      And("User inputs a Charity Regulator number")
      WhatIsYourCharityRegulatorNumberPage.enterCharityRegulatorNumber("123456")
      And("User navigates to 'Is a corporate trustee making this claim?' page")
      IsACorporateTrusteeMakingThisClaimPage.validateNavigation()
      And("User selects a corporate trustee is making this claim")
      IsACorporateTrusteeMakingThisClaimPage.radioButton(IsACorporateTrusteeMakingThisClaimPage.yes)
      IsACorporateTrusteeMakingThisClaimPage.clickContinue()
      And("User navigates to 'Does the corporate trustee have a UK address?' page")
      DoesTheCorporateTrusteeHaveAUKAddressPage.validateNavigation()
      And("User selects a corporate trustee does not have a UK address")
      DoesTheCorporateTrusteeHaveAUKAddressPage.radioButton(DoesTheCorporateTrusteeHaveAUKAddressPage.no)
      DoesTheCorporateTrusteeHaveAUKAddressPage.clickContinue()
      And("User navigates to 'What are the corporate trustee details?' page")
      CorporateTrusteeDetailsPage.validateNavigation()
      And("User enters their Non UK Trustee details and clicks continue")
      CorporateTrusteeDetailsPage.enterNonUKTrusteeDetails("TEST TRUSTEE", "00-1-332-555-2368")
      And("User navigates to 'Check your organisation details' page")
      CheckYourOrganisationDetailsPage.validateNavigation()
      Then("User selects the link to change their regulator details on the 'CYA Organisation Details' page")
      CheckYourOrganisationDetailsPage.clickChangeCharityRegulatorName()
      And("User navigates to 'What is the name of the charity regulator?' page")
      WhatIsTheNameOfTheCharityRegulatorPage.validateChangeNavigation()
      And("User clicks 'Charity is not registered with a regulator' radio button option")
      WhatIsTheNameOfTheCharityRegulatorPage.radioButton(WhatIsTheNameOfTheCharityRegulatorPage.EngWal)
      And("User clicks 'Continue' button")
      WhatIsTheNameOfTheCharityRegulatorPage.clickContinue()
      And("User navigates to 'What is the charity regulator number?' page")
      WhatIsYourCharityRegulatorNumberPage.validateChangeNavigation()
      And("User clicks 'Continue' button")
      WhatIsYourCharityRegulatorNumberPage.clickContinue()
      And("User navigates to 'Check your organisation details' page")
      CheckYourOrganisationDetailsPage.validateNavigation()
      And("User navigates to 'Make a charity repayment claim' task list page")
      CheckYourOrganisationDetailsPage.clickContinue()
      ClaimsTaskListPage_InProgress.validateNavigation_AllSubheadings()
      And("User clicks the link to navigate to 'Repayment claim details' page")
      ClaimsTaskListPage_InProgress.clickCheckYourOrganisationDetails()
      And("User navigates to 'Check your organisation details' page")
      CheckYourOrganisationDetailsPage.validateNavigation()
      Then("User selects the link to change who is making this claim on the 'CYA Organisation Details' page")
      CheckYourOrganisationDetailsPage.clickChangeCorporateTrusteeClaim()
      And("User navigates to 'Is a corporate trustee making this claim?' page")
      IsACorporateTrusteeMakingThisClaimPage.validateChangeNavigation()
      And("User selects a corporate trustee is not making this claim")
      IsACorporateTrusteeMakingThisClaimPage.radioButton(IsACorporateTrusteeMakingThisClaimPage.no)
      IsACorporateTrusteeMakingThisClaimPage.clickContinue()
      And("User navigates to 'Does the authorised official have a UK address?' page")
      DoesTheAuthorisedOfficialHaveAUKAddressPage.validateChangeNavigation()
      And("User selects that the authorised official does not have a UK address")
      DoesTheAuthorisedOfficialHaveAUKAddressPage.radioButton(DoesTheAuthorisedOfficialHaveAUKAddressPage.no)
      DoesTheAuthorisedOfficialHaveAUKAddressPage.clickContinue()
      And("User enters their UK Authorised Official details and clicks continue")
      AuthorisedOfficialDetailsPage.enterNonUKAuthOfficialDetails(
        "TEST",
        "TESTFORENAME",
        "TESTSURNAME",
        "01632 960999"
      )
      And("User navigates to 'Check your organisation details' page")
      CheckYourOrganisationDetailsPage.validateNavigation()
      And("User navigates to 'Make a charity repayment claim' task list page")
      CheckYourOrganisationDetailsPage.clickContinue()
    }

    Scenario(
      "User navigates to the 'Update Repayment Claim Details' page and validates the page elements"
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.login(HASDIRECT, Organisation, "Organisation", "HMRC-CHAR-ORG", "CHARID", "IT00074")
      Then("User navigates to 'Manage charity repayment claims' page and validates navigation")
      CharitiesManagementPlaceholder.validateNavigation()
      And(
        "User clicks the link 'Use the charities online service' to navigate to task list 'Make a charity repayment claim' page"
      )
      CharitiesManagementPlaceholder.clickUseTheCharitiesLink()
      Then("User navigates to 'Make a charity repayment claim' page")
      ClaimsTaskListPage_Empty.validateNavigation()
      And("User clicks the link to navigate to 'Repayment claim details' page")
      ClaimsTaskListPage_Empty.clickProvideRepaymentClaimDetails()
      Then("User validates the 'Repayment claim details' page")
      RepaymentClaimDetailsPage.validateNavigation()
      And("User clicks continue on 'Repayment claim details' page")
      RepaymentClaimDetailsPage.clickContinue()
      Then("User navigates to 'Repayment claim Type?' page")
      RepaymentCheckboxPage.validateNavigation()
      And("User selects 'Other Income' and 'Gift Aid' checkboxes and clicks continue")
      RepaymentCheckboxPage.checkbox(RepaymentCheckboxPage.GASDSclaim, true)
      RepaymentCheckboxPage.checkbox(RepaymentCheckboxPage.GiftAid, true)
      RepaymentCheckboxPage.clickContinue()
      Then("User navigates to 'Gift Aid Small Donations Scheme (GASDS) details' checkbox page")
      GASDSCheckboxPage.validateNavigation()
      And("User selects 'GASDS top-up' checkbox and clicks continue")
      GASDSCheckboxPage.checkbox(GASDSCheckboxPage.GASDSTopUp, true)
      GASDSCheckboxPage.clickContinue()
      Then("User navigates to 'Gift Aid Small Donations Scheme claim' page")
      GiftAidSmallDonationsSchemeClaimPage.validateNavigation()
      And("User selects 'No' and clicks continue on 'Gift Aid Small Donations Scheme claim' page")
      GiftAidSmallDonationsSchemeClaimPage.radioButton(GiftAidSmallDonationsSchemeClaimPage.no)
      GiftAidSmallDonationsSchemeClaimPage.clickContinue()
      Then("User navigates to 'Do you have a claim reference number?' page")
      DoYouHaveAClaimReferenceNumberPage.validateNavigation()
      And("User selects 'No' and clicks continue on 'Do you have a claim reference number?' page")
      DoYouHaveAClaimReferenceNumberPage.radioButton(DoYouHaveAClaimReferenceNumberPage.no)
      DoYouHaveAClaimReferenceNumberPage.clickContinue()
      Then("User navigates to 'Check your repayment claim' page")
      CheckYourRepaymentClaimPage.validateNavigation()
      Then("User navigates to 'Make a charity repayment claim' page")
      CheckYourRepaymentClaimPage.clickContinue()
      ClaimsTaskListPage_InProgress.validateNavigation_AllSubheadings()
      And("User clicks the link to navigate back to 'Provide repayment claim details' page")
      ClaimsTaskListPage_InProgress.clickCheckYourRepaymentClaimDetails()
      Then("User navigates to 'Check your repayment claim' page")
      CheckYourRepaymentClaimPage.validateNavigation()
      CheckYourRepaymentClaimPage.clickChangeRepaymentClaimType()
      Then("User navigates to 'Repayment claim type' page and un selects 'GASDS' checkbox and clicks continue")
      RepaymentCheckboxPage.checkbox(RepaymentCheckboxPage.GASDSclaim, false)
      RepaymentCheckboxPage.clickContinue()
      Then("User navigates to 'Update repayment claim details' Page")
      UpdateRepaymentClaimDetails.validateNavigation()
      UpdateRepaymentClaimDetails.radioButton(UpdateRepaymentClaimDetails.yes)
      UpdateRepaymentClaimDetails.clickContinue()
      Then("User navigates to 'Check your repayment claim' page")
      CheckYourRepaymentClaimPage.validateNavigation()
    }

    Scenario(
      "User navigates to the 'Check your organisation details' page with missing information and validates correct warning screen is displayed on submission"
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.login(
        HASDIRECT,
        Organisation,
        "Organisation",
        "HMRC-CHAR-ORG",
        "CHARID",
        "IT00075"
      )
      Then("User navigates to 'Manage charity repayment claims' page and validates navigation")
      CharitiesManagementPlaceholder.validateNavigation()
      And(
        "User clicks the link 'Use the charities online service' to navigate to task list 'Make a charity repayment claim' page"
      )
      CharitiesManagementPlaceholder.clickUseTheCharitiesLink()
      Then("User navigates to 'Make a charity repayment claim' page")
      ClaimsTaskListPage_Empty.validateNavigation()
      And("User clicks the link to navigate to 'Repayment claim details' page")
      ClaimsTaskListPage_Empty.clickProvideRepaymentClaimDetails()
      Then("User validates the 'Repayment claim details' page")
      RepaymentClaimDetailsPage.validateNavigation()
      And("User clicks continue on 'Repayment claim details' page")
      RepaymentClaimDetailsPage.clickContinue()
      Then("User navigates to 'Which type of repayment claim do you want to make?' page")
      RepaymentCheckboxPage.validateNavigation()
      And("User selects 'Tax repayments on Gift Aid donations' checkbox and clicks continue")
      RepaymentCheckboxPage.checkbox(RepaymentCheckboxPage.GiftAid, true)
      RepaymentCheckboxPage.clickContinue()
      Then("User navigates to 'Do you have a claim reference number?' page")
      DoYouHaveAClaimReferenceNumberPage.validateNavigation()
      And("User selects 'No' and clicks continue on 'Do you have a claim reference number?' page")
      DoYouHaveAClaimReferenceNumberPage.radioButton(DoYouHaveAClaimReferenceNumberPage.no)
      DoYouHaveAClaimReferenceNumberPage.clickContinue()
      Then("User navigates to 'Check your repayment claim' page")
      CheckYourRepaymentClaimPage.validateNavigation()
      CheckYourRepaymentClaimPage.clickContinue()
      Then("User navigates to 'Make a charity repayment claim' page")
      ClaimsTaskListPage_InProgress.validateNavigation_AllSubheadings()
      And("User clicks the link to navigate to 'About the organisation' page")
      ClaimsTaskListPage_InProgress.clickProvideOrganisationDetails()
      AboutTheOrganisationPage.validateNavigation()
      Then("User selects continue on 'About the organisation' page")
      AboutTheOrganisationPage.clickContinue()
      And("User navigates to 'What is the name of the charity regulator?' page")
      WhatIsTheNameOfTheCharityRegulatorPage.validateNavigation()
      And("User selects they are not registered with a regulator")
      WhatIsTheNameOfTheCharityRegulatorPage.radioButton(WhatIsTheNameOfTheCharityRegulatorPage.None)
      WhatIsTheNameOfTheCharityRegulatorPage.clickContinue()
      And("User navigates to 'Why is the charity not registered with a regulator?' page")
      WhyIsTheCharityNotRegisteredPage.validateNavigation()
      And("User selects they are excepted")
      WhyIsTheCharityNotRegisteredPage.radioButton(WhyIsTheCharityNotRegisteredPage.Excepted)
      WhyIsTheCharityNotRegisteredPage.clickContinue()
      And("User navigates to 'Your charity is excepted' page")
      YourCharityIsExceptedPage.validateNavigation()
      Then("User selects continue on 'Your charity is excepted' page")
      YourCharityIsExceptedPage.clickContinue()
      And("User navigates to 'Is a corporate trustee making this claim?' page")
      IsACorporateTrusteeMakingThisClaimPage.validateNavigation()
      And("User selects a corporate trustee is making this claim")
      IsACorporateTrusteeMakingThisClaimPage.radioButton(IsACorporateTrusteeMakingThisClaimPage.yes)
      IsACorporateTrusteeMakingThisClaimPage.clickContinue()
      And("User navigates to 'Does the corporate trustee have a UK address?' page")
      DoesTheCorporateTrusteeHaveAUKAddressPage.validateNavigation()
      And("User selects a corporate trustee does not have a UK address")
      DoesTheCorporateTrusteeHaveAUKAddressPage.radioButton(DoesTheCorporateTrusteeHaveAUKAddressPage.no)
      DoesTheCorporateTrusteeHaveAUKAddressPage.clickContinue()
      And("User navigates to 'What are the corporate trustee details?' page")
      CorporateTrusteeDetailsPage.validateNavigation()
      And("User enters their Non UK Trustee details and clicks continue")
      CorporateTrusteeDetailsPage.enterNonUKTrusteeDetails("TEST TRUSTEE", "00-1-332-555-2368")
      CheckYourOrganisationDetailsPage.validateNavigation()
      Then("User then changes details on 'Check your organisation details' page")
      CheckYourOrganisationDetailsPage.clickChangeCorporateTrusteeUKAddress()
      And("User navigates to 'Does the corporate trustee have a UK address?' page")
      DoesTheCorporateTrusteeHaveAUKAddressPage.validateChangeNavigation()
      And("User selects a corporate trustee does have a UK address")
      DoesTheCorporateTrusteeHaveAUKAddressPage.radioButton(DoesTheCorporateTrusteeHaveAUKAddressPage.yes)
      DoesTheCorporateTrusteeHaveAUKAddressPage.clickContinue()
      And("User does not enter the required Postcode value and jumps to the 'Check your organisation details' page")
      CorporateTrusteeDetailsPage.validateChangeNavigation()
      CheckYourOrganisationDetailsPage.navigateToPage(CheckYourOrganisationDetailsPage.pageUrl)
      CheckYourOrganisationDetailsPage.validateNavigation()
      Then("User attempts to submit with missing details on 'Check your organisation details' page")
      CheckYourOrganisationDetailsPage.clickContinue()
      And("User navigates to 'This claim cannot be setup' page")
      ThisClaimCannotBeSetupPage_Organisation.validateNavigation()
    }

    Scenario(
      "User navigates to the 'Check your repayment claim' page with missing information and validates correct warning screen is displayed on submission"
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.login(HASDIRECT, Organisation, "Organisation", "HMRC-CHAR-ORG", "CHARID", "IT00076")
      Then("User navigates to 'Manage charity repayment claims' page and validates navigation")
      CharitiesManagementPlaceholder.validateNavigation()
      And(
        "User clicks the link 'Use the charities online service' to navigate to task list 'Make a charity repayment claim' page"
      )
      CharitiesManagementPlaceholder.clickUseTheCharitiesLink()
      Then("User navigates to 'Make a charity repayment claim' page")
      ClaimsTaskListPage_Empty.validateNavigation()
      And("User clicks the link to navigate to 'Repayment claim details' page")
      ClaimsTaskListPage_Empty.clickProvideRepaymentClaimDetails()
      Then("User validates the 'Repayment claim details' page")
      RepaymentClaimDetailsPage.validateNavigation()
      And("User clicks continue on 'Repayment claim details' page")
      RepaymentClaimDetailsPage.clickContinue()
      Then("User navigates to 'Which type of repayment claim do you want to make?' page")
      RepaymentCheckboxPage.validateNavigation()
      And("User selects 'Gift Aid' checkbox and clicks continue")
      RepaymentCheckboxPage.checkbox(RepaymentCheckboxPage.GiftAid, true)
      RepaymentCheckboxPage.clickContinue()
      Then("User navigates to 'Do you have a claim reference number?' page")
      DoYouHaveAClaimReferenceNumberPage.validateNavigation()
      And("User selects 'No' and clicks continue on 'Do you have a claim reference number?' page")
      DoYouHaveAClaimReferenceNumberPage.radioButton(DoYouHaveAClaimReferenceNumberPage.no)
      DoYouHaveAClaimReferenceNumberPage.clickContinue()
      Then("User navigates to 'Check your repayment claim' page")
      CheckYourRepaymentClaimPage.validateNavigation()
      Then("User then changes details on 'Check your organisation details' page")
      CheckYourRepaymentClaimPage.clickChangeRepaymentClaimType()
      And(
        "User unselects 'Tax repayments on Gift Aid donations' checkbox selects 'Top up payments for donations under the Gift Aid Small Donations Scheme' checkbox and clicks continue"
      )
      RepaymentCheckboxPage.checkbox(RepaymentCheckboxPage.GiftAid, false)
      RepaymentCheckboxPage.checkbox(RepaymentCheckboxPage.GASDSclaim, true)
      RepaymentCheckboxPage.clickContinue()
      And("User navigates to 'Gift Aid Small Donations Scheme (GASDS) details' checkbox page in change mode")
      GASDSCheckboxPage.validateChangeNavigation()
      And("User does not enter the required values and jumps to the 'Check your repayment details' page")
      CheckYourRepaymentClaimPage.navigateToPage(CheckYourRepaymentClaimPage.pageUrl)
      Then("User attempts to submit with missing details on 'Check your repayment details' page")
      CheckYourRepaymentClaimPage.clickContinue()
      And("User navigates to 'This claim cannot be setup' page")
      ThisClaimCannotBeSetupPage_Repayment.validateNavigation()
    }

    Scenario(
      "User navigates a GASDS Journey for multiple years and verifies 'Check your GASDS donation details' page"
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.login(HASDIRECT, Organisation, "Organisation", "HMRC-CHAR-ORG", "CHARID", "IT00077")
      Then("User navigates to 'Manage charity repayment claims' page and validates navigation")
      CharitiesManagementPlaceholder.validateNavigation()
      And(
        "User clicks the link 'Use the charities online service' to navigate to task list 'Make a charity repayment claim' page"
      )
      CharitiesManagementPlaceholder.clickUseTheCharitiesLink()
      Then("User navigates to 'Make a charity repayment claim' page")
      ClaimsTaskListPage_Empty.validateNavigation()
      And("User clicks the link to navigate to 'Repayment claim details' page")
      ClaimsTaskListPage_Empty.clickProvideRepaymentClaimDetails()
      Then("User validates the 'Repayment claim details' page")
      RepaymentClaimDetailsPage.validateNavigation()
      And("User clicks continue on 'Repayment claim details' page")
      RepaymentClaimDetailsPage.clickContinue()
      Then("User navigates to 'Which type of repayment claim do you want to make?' page")
      RepaymentCheckboxPage.validateNavigation()
      And(
        "User selects 'Top up payments for donations under the Gift Aid Small Donations Scheme' checkbox and clicks continue"
      )
      RepaymentCheckboxPage.checkbox(RepaymentCheckboxPage.GASDSclaim, true)
      RepaymentCheckboxPage.clickContinue()
      And("User navigates to 'Gift Aid Small Donations Scheme (GASDS) details' checkbox page")
      GASDSCheckboxPage.validateNavigation()
      And("User selects 'GASDS top-up' checkbox and clicks continue")
      GASDSCheckboxPage.checkbox(GASDSCheckboxPage.GASDSTopUp, true)
      GASDSCheckboxPage.clickContinue()
      Then("User navigates to 'Gift Aid Small Donations Scheme claim' page")
      GiftAidSmallDonationsSchemeClaimPage.validateNavigation()
      And("User selects 'Yes' and clicks continue on 'Gift Aid Small Donations Scheme claim' page")
      GiftAidSmallDonationsSchemeClaimPage.radioButton(GiftAidSmallDonationsSchemeClaimPage.yes)
      GiftAidSmallDonationsSchemeClaimPage.clickContinue()
      Then("User navigates to 'Do you have a claim reference number?' page")
      DoYouHaveAClaimReferenceNumberPage.validateNavigation()
      And("User selects 'No' and clicks continue on 'Do you have a claim reference number?' page")
      DoYouHaveAClaimReferenceNumberPage.radioButton(DoYouHaveAClaimReferenceNumberPage.no)
      DoYouHaveAClaimReferenceNumberPage.clickContinue()
      Then("User navigates to 'Check your repayment claim' page")
      CheckYourRepaymentClaimPage.validateNavigation()
      CheckYourRepaymentClaimPage.clickContinue()
      Then("User navigates to 'Make a charity repayment claim' page")
      ClaimsTaskListPage_InProgress.validateNavigation_AboutClaimAndDeclaration()
      And("User clicks the link to navigate to 'About Gift Aid Small Donations Scheme schedule' page")
      ClaimsTaskListPage_InProgress.clickProvideGASDSDetails()
      And("User Validates the navigation to 'About Gift Aid Small Donations Scheme schedule' page")
      AboutGASDSPage.validateNavigation()
      Then("User navigates to 'What is the adjustment amount for Gift Aid previously overclaimed?' page")
      AboutGASDSPage.clickContinue()
      WhatIsTheAdjustmentAmountForGiftAidPreviouslyOverclaimedPage.validateNavigation()
      Then("User navigates to 'Check your GASDS adjustment amount' page")
      WhatIsTheAdjustmentAmountForGiftAidPreviouslyOverclaimedPage.enterAdjustmentAmountValue("123.45")
      CheckYourGASDSAdjustmentAmountPage.validateNavigation()
      Then("User navigates to 'Which tax year are you claiming for?' year 1 page")
      CheckYourGASDSAdjustmentAmountPage.clickContinue()
      WhichTaxYearAreYouClaimingForPage.validateNavigation1()
      Then(
        s"User navigates to 'Which tax year are you claiming for?' page and inputs: " + WhichTaxYearAreYouClaimingForPage.earliestTaxYear
      )
      WhichTaxYearAreYouClaimingForPage.enterValidTaxYear(WhichTaxYearAreYouClaimingForPage.earliestTaxYear)
      Then("User navigates to 'What donation amount are you claiming under GASDS, in pounds?' for the first year page")
      WhatDonationAmountAreYouClaimingUnderGASDSPage.validateNavigation_Year1()
      Then(
        "User inputs a value on 'What donation amount are you claiming under GASDS, in pounds?' for the first year page"
      )
      WhatDonationAmountAreYouClaimingUnderGASDSPage.enterDonationAmount("543.21")
      Then("User navigates to 'Check your claim details for tax year 1' page")
      CheckYourClaimDetailsForTaxYearPage.validateNavigation1()
      Then("User navigates to 'You have added a claim for 1 tax year' page")
      CheckYourClaimDetailsForTaxYearPage.clickContinue()
      YouHaveAddedAClaimForXTaxYearPage.validateNavigation1()
      Then("User selects 'Yes' on 'You have added a claim for 1 tax year' page to add another tax year")
      YouHaveAddedAClaimForXTaxYearPage.radioButton(YouHaveAddedAClaimForXTaxYearPage.yes)
      YouHaveAddedAClaimForXTaxYearPage.clickContinue()
      Then("User navigates to 'Which tax year are you claiming for?' year 2 page")
      WhichTaxYearAreYouClaimingForPage.validateNavigation2()
      Then(
        s"User navigates to 'Which tax year are you claiming for?' page and inputs: " + WhichTaxYearAreYouClaimingForPage.secondEarliestTaxYear
      )
      WhichTaxYearAreYouClaimingForPage.enterValidTaxYear(WhichTaxYearAreYouClaimingForPage.secondEarliestTaxYear)
      Then("User navigates to 'What donation amount are you claiming under GASDS, in pounds?' for the second year page")
      WhatDonationAmountAreYouClaimingUnderGASDSPage.validateNavigation_Year2()
      Then(
        "User inputs a value on 'What donation amount are you claiming under GASDS, in pounds?' for the second year page"
      )
      WhatDonationAmountAreYouClaimingUnderGASDSPage.enterDonationAmount("111.11")
      Then("User navigates to 'Check your claim details for tax year 2' page")
      CheckYourClaimDetailsForTaxYearPage.validateNavigation2()
      Then("User navigates to 'You have added a claim for 2 tax years' page")
      CheckYourClaimDetailsForTaxYearPage.clickContinue()
      YouHaveAddedAClaimForXTaxYearPage.validateNavigation2()
      Then("User selects 'Yes' on 'You have added a claim for 2 tax year' page to add another tax year")
      YouHaveAddedAClaimForXTaxYearPage.radioButton(YouHaveAddedAClaimForXTaxYearPage.no)
      YouHaveAddedAClaimForXTaxYearPage.clickContinue()
      CheckYourGASDSDonationDetailsPage.validateNavigation()
      Then("User Clicks 'Change' Link of GASDS Number of tax years added")
      CheckYourGASDSDonationDetailsPage.clickChangeGASDSTaxYears()
      Then("User navigates to 'You have added a claim for 2 tax years' page")
      YouHaveAddedAClaimForXTaxYearPage.validateNavigation2()
      Then("User selects 'No' on 'You have added a claim for 2 tax year' page to add another tax year")
      YouHaveAddedAClaimForXTaxYearPage.radioButton(YouHaveAddedAClaimForXTaxYearPage.yes)
      YouHaveAddedAClaimForXTaxYearPage.clickContinue()
      Then("User navigates to 'Which tax year are you claiming for?' year 3 page")
      WhichTaxYearAreYouClaimingForPage.validateNavigation3()
      Then(
        s"User navigates to 'Which tax year are you claiming for?' page and inputs: " + WhichTaxYearAreYouClaimingForPage.recentTaxYear
      )
      WhichTaxYearAreYouClaimingForPage.enterValidTaxYear(WhichTaxYearAreYouClaimingForPage.recentTaxYear)
      Then("User navigates to 'What donation amount are you claiming under GASDS, in pounds?' for the third year page")
      WhatDonationAmountAreYouClaimingUnderGASDSPage.validateNavigation_Year3()
      And("User does not enter the required values and jumps to the 'Check your GASDS donation details' page")
      CheckYourGASDSDonationDetailsPage.navigateToPage(CheckYourGASDSDonationDetailsPage.pageUrl)
      Then("User attempts to submit with missing details on 'Check your repayment details' page")
      CheckYourGASDSDonationDetailsPage.clickConfirmAndSubmit()
      And("User navigates to 'This claim cannot be setup' page")
      ThisClaimCannotBeSetupPage_GASDS.validateNavigation()
    }

    Scenario(
      "User navigates to the 'Page not found' page which would display on incorrect navigations"
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.login(HASDIRECT, Organisation, "Organisation", "HMRC-CHAR-ORG", "CHARID", "IT00078")
      Then("User navigates to 'Manage charity repayment claims' page and validates navigation")
      CharitiesManagementPlaceholder.validateNavigation()
      And(
        "User clicks the link 'Use the charities online service' to navigate to task list 'Make a charity repayment claim' page"
      )
      CharitiesManagementPlaceholder.clickUseTheCharitiesLink()
      Then("User navigates to 'Make a charity repayment claim' page")
      ClaimsTaskListPage_Empty.validateNavigation()
      And("User clicks the link to navigate to 'Repayment claim details' page")
      ClaimsTaskListPage_Empty.clickProvideRepaymentClaimDetails()
      Then("User navigates to 'Make a charity repayment claim' page")
      ClaimsTaskListPage_Empty.navigateToPage(Error_PageNotFoundPage.pageUrl)
      Then("User validates the 'Page not found' page")
      Error_PageNotFoundPage.validateNavigation()
    }

    Scenario(
      "User navigates to the 'Access Denied' page which would display on incorrect navigations"
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.login(HASDIRECT, Organisation, "Organisation", "HMRC-CHAR-ORG", "CHARID", "IT00079")
      Then("User navigates to 'Manage charity repayment claims' page and validates navigation")
      CharitiesManagementPlaceholder.validateNavigation()
      And(
        "User clicks the link 'Use the charities online service' to navigate to task list 'Make a charity repayment claim' page"
      )
      CharitiesManagementPlaceholder.clickUseTheCharitiesLink()
      Then("User navigates to 'Make a charity repayment claim' page")
      ClaimsTaskListPage_Empty.validateNavigation()
      And("User clicks the link to navigate to 'Repayment claim details' page")
      ClaimsTaskListPage_Empty.clickProvideRepaymentClaimDetails()
      Then("User navigates to 'Make a charity repayment claim' page")
      ClaimsTaskListPage_Empty.navigateToPage(AccessDeniedErrorPage.pageUrl)
      Then("User validates the 'Page not found' page")
      AccessDeniedErrorPage.validateNavigation()
    }

    Scenario(
      "User uploads, updates, then deletes OI, CB and CC spreadhseets"
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.login(HASDIRECT, Organisation, "Organisation", "HMRC-CHAR-ORG", "CHARID", "IT00080")
      Then("User navigates to 'Manage charity repayment claims' page and validates navigation")
      CharitiesManagementPlaceholder.validateNavigation()
      And(
        "User clicks the link 'Use the charities online service' to navigate to task list 'Make a charity repayment claim' page"
      )
      CharitiesManagementPlaceholder.clickUseTheCharitiesLink()
      Then("User navigates to 'Make a charity repayment claim' page")
      ClaimsTaskListPage_Empty.validateNavigation()
      And("User clicks the link to navigate to 'Repayment claim details' page")
      ClaimsTaskListPage_Empty.clickProvideRepaymentClaimDetails()
      Then("User validates the 'Repayment claim details' page")
      RepaymentClaimDetailsPage.validateNavigation()
      And("User clicks continue on 'Repayment claim details' page")
      RepaymentClaimDetailsPage.clickContinue()
      Then("User navigates to 'Which type of repayment claim do you want to make?' page")
      RepaymentCheckboxPage.validateNavigation()
      And("User selects all 3 checkboxes and clicks continue")
      RepaymentCheckboxPage.checkbox(RepaymentCheckboxPage.GASDSclaim, true)
      RepaymentCheckboxPage.checkbox(RepaymentCheckboxPage.OtherIncome, true)
      RepaymentCheckboxPage.clickContinue()
      And("User navigates to 'Gift Aid Small Donations Scheme (GASDS) details' checkbox page")
      GASDSCheckboxPage.validateNavigation()
      And("User selects all 3 checkboxes and clicks continue")
      GASDSCheckboxPage.checkbox(GASDSCheckboxPage.GASDSBuilding, true)
      GASDSCheckboxPage.checkbox(GASDSCheckboxPage.GASDSConnected, true)
      GASDSCheckboxPage.clickContinue()
      Then("User navigates to 'Gift Aid Small Donations Scheme claim' page")
      GiftAidSmallDonationsSchemeClaimPage.validateNavigation()
      And("User selects 'Yes' and clicks continue on 'Gift Aid Small Donations Scheme claim' page")
      GiftAidSmallDonationsSchemeClaimPage.radioButton(GiftAidSmallDonationsSchemeClaimPage.yes)
      GiftAidSmallDonationsSchemeClaimPage.clickContinue()
      Then("User navigates to 'Do you have a claim reference number?' page")
      DoYouHaveAClaimReferenceNumberPage.validateNavigation()
      And("User selects 'No' and clicks continue on 'Do you have a claim reference number?' page")
      DoYouHaveAClaimReferenceNumberPage.radioButton(DoYouHaveAClaimReferenceNumberPage.no)
      DoYouHaveAClaimReferenceNumberPage.clickContinue()
      Then("User navigates to 'Check your repayment claim' page")
      CheckYourRepaymentClaimPage.validateNavigation()
      Then("User navigates to 'Make a charity repayment claim' page")
      CheckYourRepaymentClaimPage.clickContinue()
      And("User clicks the link to navigate to 'Add Other Income schedule' page")
      ClaimsTaskListPage_InProgress.clickAddOtherIncomeSchedule()
      Then("User navigates to 'About Other Income schedule' page")
      AboutOtherIncomeSchedulePage.validateNavigation()
      AboutOtherIncomeSchedulePage.clickContinue()
      Then("User navigates to 'Upload a Other Income schedule' page")
      UploadAnOtherIncomeSchedulePage.validateNavigation()
      Then("User selects a file to upload in the 'Upload a Other Income schedule' page")
      UploadAnOtherIncomeSchedulePage.selectFile("OtherIncomeSpreadsheets/Other-Income-Schedule-GoodData")
      UploadAnOtherIncomeSchedulePage.clickContinue()
      Then("User navigates to 'Your Other Income schedule upload' page")
      YourOtherIncomeScheduleUploadPage.validateNavigation()
      YourOtherIncomeScheduleUploadPage.waitForFileUpload()
      YourOtherIncomeScheduleUploadPage.clickContinue()
      Then("User navigates to 'Check your Other Income schedule' page")
      CheckYourOtherIncomeSchedulePage.validateNavigation()
      CheckYourOtherIncomeSchedulePage.radioButton(CheckYourOtherIncomeSchedulePage.yes)
      CheckYourOtherIncomeSchedulePage.clickContinue()
      Then("User navigates to 'Update Other Income schedule' page")
      UpdateOtherIncomeSchedulePage.validateNavigation()
      UpdateOtherIncomeSchedulePage.clickContinue()
      And("User selects 'No' and clicks continue on 'Update your Other Income Schedule' page")
      UpdateOtherIncomeSchedulePage.radioButton(UpdateOtherIncomeSchedulePage.yes)
      UpdateOtherIncomeSchedulePage.clickContinue()
      Then("User navigates to 'Upload a Other Income schedule' page")
      UploadAnOtherIncomeSchedulePage.validateNavigation()
      Then("User selects a file to upload in the 'Upload a Other Income schedule' page")
      UploadAnOtherIncomeSchedulePage.selectFile("OtherIncomeSpreadsheets/Other-Income-Schedule-BadData")
      UploadAnOtherIncomeSchedulePage.clickContinue()
      Then("User navigates to 'Your Other Income schedule upload' page")
      YourOtherIncomeScheduleUploadPage.validateNavigation()
      YourOtherIncomeScheduleUploadPage.waitForFileUpload()
      YourOtherIncomeScheduleUploadPage.clickContinue()
      Then("User navigates to 'Problem with your Other Income schedule data' page and validates page")
      CheckYourOtherIncomeScheduleErrorPage.validateNavigation()
      Then("User clicks on the Delete Schedule link and reaches the Delete Schedule WRN 1.0 page")
      CheckYourOtherIncomeScheduleErrorPage.clickDeleteScheduleLink()
      Then("User validates navigation of Delete Schedule WRN 1.0 page")
      DeleteOtherIncomeSchedulePage.validateNavigation()
      And("User selects 'Yes' and clicks continue on 'Do you want to delete this Other Income schedule?' page")
      DeleteOtherIncomeSchedulePage.radioButton(DeleteOtherIncomeSchedulePage.yes)
      DeleteOtherIncomeSchedulePage.clickContinue()
      Then("User navigates to 'Make a charity repayment claim' page")
      ClaimsTaskListPage_InProgress.validateNavigation_AllSubheadings()
      And("User clicks the link to navigate to 'Add Community Buildings schedule' page")
      ClaimsTaskListPage_InProgress.clickAddCommunityBuildingsSchedule()
      Then("User navigates to 'About Community buildings schedule' page")
      AboutCommunityBuildingsSchedulePage.validateNavigation()
      AboutCommunityBuildingsSchedulePage.clickContinue()
      Then("User navigates to 'Upload a Community Buildings schedule' page")
      UploadACommunityBuildingsSchedulePage.validateNavigation()
      Then("User selects a file to upload in the 'Upload a Community Buildings schedule' page")
      UploadACommunityBuildingsSchedulePage.selectFile(
        "CommunityBuildingsSpreadsheets/CommunityBuildingsPassRows"
      )
      UploadACommunityBuildingsSchedulePage.clickContinue()
      Then("User navigates to 'Your Community Buildings schedule upload' page")
      YourCommunityBuildingsScheduleUploadPage.validateNavigation()
      YourCommunityBuildingsScheduleUploadPage.waitForFileUpload()
      YourCommunityBuildingsScheduleUploadPage.clickContinue()
      Then("User navigates to 'Check your Community Buildings schedule' page")
      CheckYourCommunityBuildingsSchedulePage.validateNavigation()
      CheckYourCommunityBuildingsSchedulePage.radioButton(CheckYourCommunityBuildingsSchedulePage.yes)
      CheckYourCommunityBuildingsSchedulePage.clickContinue()
      Then("User navigates to 'Update Community Buildings schedule' page")
      UpdateCommunityBuildingSchedulePage.validateNavigation()
      UpdateCommunityBuildingSchedulePage.clickContinue()
      And("User selects 'Yes' and clicks continue on 'Update your Community Buildings Schedule' page")
      UpdateCommunityBuildingSchedulePage.radioButton(UpdateCommunityBuildingSchedulePage.yes)
      UpdateCommunityBuildingSchedulePage.clickContinue()
      Then("User navigates to 'Upload a Community Buildings schedule' page")
      UploadACommunityBuildingsSchedulePage.validateNavigation()
      Then("User selects a file to upload in the 'Upload a Community Buildings schedule' page")
      UploadACommunityBuildingsSchedulePage.selectFile(
        "CommunityBuildingsSpreadsheets/community-buildings-excel-BadData"
      )
      UploadACommunityBuildingsSchedulePage.clickContinue()
      Then("User navigates to 'Your Community Buildings schedule upload' page")
      YourCommunityBuildingsScheduleUploadPage.validateNavigation()
      YourCommunityBuildingsScheduleUploadPage.waitForFileUpload()
      YourCommunityBuildingsScheduleUploadPage.clickContinue()
      Then("User navigates to 'Problem with your Community Buildings schedule data' page and validates page")
      CheckYourCommunityBuildingsScheduleErrorPage.validateNavigation()
      Then("User clicks on the Delete Schedule link and reaches the Delete Schedule WRN 1.0 page")
      CheckYourCommunityBuildingsScheduleErrorPage.clickDeleteScheduleLink()
      Then("User validates navigation of Delete Schedule WRN 1.0 page")
      DeleteGASDSCommunityBuildingsSchedulePage.validateNavigation()
      And("User selects 'Yes' and clicks continue on 'Do you want to delete this Community Buildings schedule?' page")
      DeleteGASDSCommunityBuildingsSchedulePage.radioButton(DeleteGASDSCommunityBuildingsSchedulePage.yes)
      DeleteGASDSCommunityBuildingsSchedulePage.clickContinue()
      Then("User navigates to 'Make a charity repayment claim' page")
      ClaimsTaskListPage_InProgress.validateNavigation_AllSubheadings()
      And("User clicks the link to navigate to 'Add Connected Charities schedule' page")
      ClaimsTaskListPage_InProgress.clickAddConnectedCharitiesSchedule()
      Then("User navigates to 'About Connected Charities schedule' page")
      AboutConnectedCharitiesSchedulePage.validateNavigation()
      AboutConnectedCharitiesSchedulePage.clickContinue()
      Then("User navigates to 'Upload a Connected Charities schedule' page")
      UploadAConnectedCharitiesSchedulePage.validateNavigation()
      Then("User selects a file to upload in the 'Upload a Connected Charities schedule' page")
      UploadAConnectedCharitiesSchedulePage.selectFile(
        "ConnectedCharitiesSpreadsheets/Connected-Charities-schedule-Excel-GoodData"
      )
      UploadAConnectedCharitiesSchedulePage.clickContinue()
      Then("User navigates to 'Your Connected Charities schedule upload' page")
      YourConnectedCharitiesScheduleUploadPage.validateNavigation()
      YourConnectedCharitiesScheduleUploadPage.waitForFileUpload()
      YourConnectedCharitiesScheduleUploadPage.clickContinue()
      Then("User navigates to 'Check your Connected Charities schedule' page")
      CheckYourConnectedCharitiesSchedulePage.validateNavigation()
      CheckYourConnectedCharitiesSchedulePage.radioButton(CheckYourCommunityBuildingsSchedulePage.yes)
      CheckYourConnectedCharitiesSchedulePage.clickContinue()
      Then("User navigates to 'Update Connected Charities schedule' page")
      UpdateConnectedCharitiesSchedulePage.validateNavigation()
      And("User selects 'Yes' and clicks continue on 'Update your Connected Charities Schedule' page")
      UpdateConnectedCharitiesSchedulePage.radioButton(UpdateConnectedCharitiesSchedulePage.yes)
      UpdateConnectedCharitiesSchedulePage.clickContinue()
      Then("User navigates to 'Upload a Connected Charities schedule' page")
      UploadAConnectedCharitiesSchedulePage.validateNavigation()
      Then("User selects a file to upload in the 'Upload a Connected Charities schedule' page")
      UploadAConnectedCharitiesSchedulePage.selectFile(
        "ConnectedCharitiesSpreadsheets/Connected-Charities-schedule-Excel-BadData"
      )
      UploadAConnectedCharitiesSchedulePage.clickContinue()
      Then("User navigates to 'Your Connected Charities schedule upload' page")
      YourConnectedCharitiesScheduleUploadPage.validateNavigation()
      YourConnectedCharitiesScheduleUploadPage.waitForFileUpload()
      YourConnectedCharitiesScheduleUploadPage.clickContinue()
      Then("User navigates to 'Problem with your Connected Charities schedule data' page and validates page")
      CheckYourConnectedCharitiesScheduleErrorPage.validateNavigation()
      Then("User clicks on the Delete Schedule link and reaches the Delete Schedule WRN 1.0 page")
      CheckYourConnectedCharitiesScheduleErrorPage.clickDeleteScheduleLink()
      Then("User validates navigation of Delete Schedule WRN 1.0 page")
      DeleteGASDSConnectedCharitiesSchedulePage.validateNavigation()
      And("User selects 'Yes' and clicks continue on 'Do you want to delete this Connected Charities schedule?' page")
      DeleteGASDSConnectedCharitiesSchedulePage.radioButton(DeleteGASDSConnectedCharitiesSchedulePage.yes)
      DeleteGASDSConnectedCharitiesSchedulePage.clickContinue()
      Then("User navigates to 'Make a charity repayment claim' page")
      ClaimsTaskListPage_InProgress.validateNavigation_AllSubheadings()
    }
  }
}
